### ISSUE TITLE
日历日期与实际不匹配

### ISSUE THREAD

**Issue by doonnoop** [treadpit/wx_calendar#103]
2019年4月26日应该是周五，但是显示是周四，整体日期都错后了一天。
![image](https://user-images.githubusercontent.com/25371624/56828920-6395ee80-6830-11e9-837f-65790d2eacbc.png)

**Comment by treadpit** [comment]
具体是做了什么操作呢？试了下master代码没有这个问题

![image](https://user-images.githubusercontent.com/10692855/56844752-107f7280-68e8-11e9-9954-7aac49221895.png)

**Comment by treadpit** [comment]
无回复，暂时关闭
