### ISSUE TITLE
请教conf里多个事件使用相同的代码段，怎么把这段代码独立出来？

### ISSUE THREAD

**Issue by 3xxx** [treadpit/wx_calendar#105]
比如代码如下：重复的代码A怎样单独放到一个方法里？非常感谢您。
const conf = {

 whenChangeMonth: (current, next) => {
  //执行代码A：查询打卡记录
    wx.request({
      url: config.url + '/checkin',
     ……
   })
 }
 afterCalendarRender(ctx) {
   //执行代码A：查询打卡记录
    wx.request({
      url: config.url + '/checkin',
     ……
   })
 }
}

**Comment by treadpit** [comment]
这个是具体的JS问题，这个看你具体定义在哪里都行

**Comment by heroofchina** [comment]
这个本身和插件没有任何关系是使用原生js的问题 你可以把request封装下 ，传入不同的参数 就可以了
