### ISSUE TITLE
关于日期格式

### ISSUE THREAD

**Issue by daoying1994** [treadpit/wx_calendar#106]
插件用着不错，但是项目中测试出一个问题
日期格式 月份或者日子 少个零 有时候才有效
![test](https://user-images.githubusercontent.com/17850021/56873181-24031880-6a63-11e9-9ecc-fd3c236aedb7.png)

enableDays(['2019-05-03','2019-5-4','2019-05-5','2019-5-06','2019-05-07']);

**Comment by treadpit** [comment]
已修复

**Comment by Youcongcong** [comment]
这个问题 自已全部专成没有0的
