### ISSUE TITLE
单选支持取消选中

### ISSUE THREAD

**Issue by Youcongcong** [treadpit/wx_calendar#109]
选日期第二次点击可以取消选中吗

**Comment by treadpit** [comment]
@Youcongcong 多选模式下支持

**Comment by Youcongcong** [comment]
> @Youcongcong 多选模式下支持

你好 是单选的

**Comment by treadpit** [comment]
这是出于什么需求考虑的？

**Comment by Youcongcong** [comment]
是这样的 整个日历上如果只有一个日期可选。用户选了 就不可以取消了

**Comment by treadpit** [comment]
这个我增加个配置项吧

**Comment by Youcongcong** [comment]
> 这个我增加个配置项吧

感谢作者提供非常实用的软件

**Comment by pengqiangGGG** [comment]
怎么在一个页面上把当前月份的日期和下一月份的日期都显示出来，就是显示两个月的日期
