### ISSUE TITLE
jump跳转到指定日期失败

### ISSUE THREAD

**Issue by huyouheng** [treadpit/wx_calendar#113]
> onShow: function(){
     initCalendar();
    jump(2019,4,4);
}

Cannot read property 'year' of undefined;at "pages/profile/index" page lifeCycleMethod onShow function
TypeError: Cannot read property 'year' of undefined

**Comment by treadpit** [comment]
`initCalendar()` 和 ` jump()` 是同步执行的，jump的时候日历数据还未准备好，请参考文档，可以设置 `defaultDay`，或者在 `afterCalendarRender()` 中使用 `jump()` 函数
