### ISSUE TITLE
关于初始化和显示的问题

### ISSUE THREAD

**Issue by SimonaYan** [treadpit/wx_calendar#119]
先感谢大神的代码，想问一下Read Me里的“引入组件”和“初始化”是要添加在哪里的？
不添加好像to do list和date picker就用不了，拜托帮忙解答下，谢谢！

**Comment by wukun666** [comment]
date picker 用不了,我也遇到了这个问题,请问解决了吗

**Comment by treadpit** [comment]
没太明白你不知道添加在哪里是什么意思？页面上引入日历可参考代码参考里的`/pages/calendarComponent/` 文件夹下的相关示例

**Comment by SimonaYan** [comment]
不好意思，因为我也刚学没多久，就是是要按下面这段操作才能让代码生效吗？这些代码是要加在哪里呢？
“1. 引入组件 

在页面  json  文件中配置组件
{
  "usingComponents": {
    "calendar": "../../component/calendar/index"
  }
}
json

在页面  wxml  中引入组件
<calendar calendar="{{calendar}}" gesture="{{gesture}}"></calendar>
xml

  2. 日历组件初始化 
import initCalendar from '../../component/calendar/main.js';
const conf = {
  onShow: function() {
    initCalendar(); // 使用默认配置初始化日历
  }
};
Page(conf);

”

**Comment by treadpit** [comment]
建议你先看下小程序的文档，梳理下小程序一个页面到底包含哪些部分

另外你看了我说的那个文件夹么，那文件夹就是一个完整的页面了。
- `json` 加在页面的 `json` 文件里
- `wxml`加在页面的 `wxml` 文件里
- `js` 加在 `js` 文件里面

**Comment by SimonaYan** [comment]
Dear,
是加在app.目录下面还是加在index或者calendar下面。。？再次感谢！

**Comment by treadpit** [comment]
日历用在哪个页面，哪个页面初始化
