### ISSUE TITLE
日期选择器 Template显示空白

### ISSUE THREAD

**Issue by WilburZiWong** [treadpit/wx_calendar#127]
您好，我按照您

> https://treadpit.github.io/wx_calendar/?id=_1-%E5%BC%95%E5%85%A5wxml%E5%8F%8Awxss1
这个网页的方法引入template，在开发工具上显示空白，也没报错，请问是什么原因呢？

**Comment by zjlovezj** [comment]
作者建议 “建议使用组件方式引入，模板引入方式未维护”

https://github.com/treadpit/wx_calendar/tree/component/docs

**Comment by WilburZiWong** [comment]
> 作者建议 “建议使用组件方式引入，模板引入方式未维护”
> 
> https://github.com/treadpit/wx_calendar/tree/component/docs

日历我是通过组件导入的，请问下日期选择器怎么通过组件导入呢？谢谢

**Comment by WilburZiWong** [comment]
> 作者建议 “建议使用组件方式引入，模板引入方式未维护”
> 
> https://github.com/treadpit/wx_calendar/tree/component/docs

我尝试了一下，失败了，麻烦您能告诉我怎么导入能成功显示么

**Comment by zjlovezj** [comment]
https://github.com/treadpit/wx_calendar/tree/release/1.0.0/docs

**Comment by WilburZiWong** [comment]
> https://github.com/treadpit/wx_calendar/tree/release/1.0.0/docs
> 
> 你可能看的过时文档，我刚才也弄了半天。看上面的文档能解决。

是看这个文档，还是用导入模板的方法么

**Comment by zjlovezj** [comment]
看文档

**Comment by treadpit** [comment]
显示空白是否有抛错，页面是否有数据，有调试过么？

若仍然未解决，`reopen` 该 `issue`，暂时先关闭
