### ISSUE TITLE
能否增加一个周/月视图的切换

### ISSUE THREAD

**Issue by wifi9984** [treadpit/wx_calendar#13]
像MIUI自带日历的那种，默认展示月历视图，通过监听滑动，切换到周历视图，节省屏幕空间

**Comment by treadpit** [comment]
大概了解了一下，是指向上滑动的时候就切换成只显示当前选中日期那一排？

**Comment by wifi9984** [comment]
是滴~

**Comment by treadpit** [comment]
这个可能模板使用者也得改动了，滑动监听的应该是整个页面，得自己给最外层 `view` 绑定事件，然后调用日历组件内部暴露的函数

**Comment by lishaoh** [comment]
我也需要一个周月视图切换功能，能节省屏幕空间，老大，靠你了😁

**Comment by treadpit** [comment]
@wifi9984 @lishaoh 周月视图切换参考 README 中 `switchView('week')` 方法，目前做了把当前月按周、月视图切换，切换月份的话会使用月视图
