### ISSUE TITLE
怎么控制只显示本月的天数

### ISSUE THREAD

**Issue by qwqw521531** [treadpit/wx_calendar#130]
现在的情况是显示的是 上个月灰色不可点击的天数 + 本月的天数  + 下月灰色不可点击的天数

----  怎么控制只显示本月的天数  上个月 和 下个月 的天数 都不显示

**Comment by treadpit** [comment]
@qwqw521531  [参考文档 配置 `onlyShowCurrentMonth` 选项](https://treadpit.github.io/wx_calendar/?id=_3-%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE)
