### ISSUE TITLE
onTapDay事件不生效

### ISSUE THREAD

**Issue by qq229338869** [treadpit/wx_calendar#134]
![image](https://user-images.githubusercontent.com/30120123/60422456-a7391a00-9c1e-11e9-8b9a-00dd6f981278.png)
![image](https://user-images.githubusercontent.com/30120123/60422651-0860ed80-9c1f-11e9-922c-d365e4ae4c3d.png)
![image](https://user-images.githubusercontent.com/30120123/60422529-c89a0600-9c1e-11e9-876b-19e3ea773583.png)
我运行一个小程序demo，想直接使用onTapDay事件，但是这个按照文档设置完了之后afterTapDay，whenChangeMonth，afterCalendarRender可以正常使用，onTapDay不能使用？

**Comment by treadpit** [comment]
已修复，该事件需要配置选项，请参考文档 [配置 takeoverTap 为真](https://treadpit.github.io/wx_calendar/?id=_3-%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE)

**Comment by qq229338869** [comment]
> 已修复，该事件需要配置选项，请参考文档 [配置 takeoverTap 为真](https://treadpit.github.io/wx_calendar/?id=_3-%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE)

好的，我去试试
