### ISSUE TITLE
IOS 日期格式不兼容，解决方案替换成/$

### ISSUE THREAD

**Issue by gonghuiyuan516** [treadpit/wx_calendar#137]
IOS 日期格式不兼容，解决方案替换成/$

例如`${+year}-${+month}-${+day}`;   替换成`${+year}/${+month}/${+day}`;

将库里面的所有 -$ 替换成 /$ 即可。

**Comment by treadpit** [comment]
关联issue #106 

日历是处理了这个问题的，你这个是用的哪个组件哪种情况下有这个问题？

**Comment by treadpit** [comment]
无反馈，先关闭
