### ISSUE TITLE
支持每周第一天为周一排列

### ISSUE THREAD

**Issue by qwqw521531** [treadpit/wx_calendar#139]
现在的日历展示实现是  日 一  二  三  四  五  六   这种排列方式是国外的排列方式

需要怎么更改  展示成 国内的 展示方式   一   二  三  四  五  六  日 的形式

**Comment by treadpit** [comment]
[参考文档配置](https://treadpit.github.io/wx_calendar/?id=_3-%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE) `firstDayOfWeek: 'Mon'` 参数
