### ISSUE TITLE
切换到周视图待办事项失效

### ISSUE THREAD

**Issue by haogg1996** [treadpit/wx_calendar#141]
在月视图下设置待办事项，然后切换到周视图，此时左右滑动切换周时设置的待办事项会不显示

**Comment by haogg1996** [comment]
修复方法，在initSelectedDay方法中：
`    const todoLabelsCol = todoLabels.map(d => `${d.year}-${Number.parseInt(d.month)}-${Number.parseInt(d.day)}`);`
` if (selectedDayStr.includes(`${item.year}+${Number.parseInt(item.month)}+${Number.parseInt(item.day)}`)) `
因为todoLabels中的month都是有0填充空位的，后面的includes里面item的month是没有0填充的，所以导致2019-07-11不等于2019-7-11

**Comment by haogg1996** [comment]
修复方法，在initSelectedDay方法中：
```
const todoLabelsCol = todoLabels.map(d =>${d.year}-${Number.parseInt(d.month)}-${Number.parseInt(d.day)});
if (selectedDayStr.includes(${item.year}+${Number.parseInt(item.month)}+${Number.parseInt(item.day)}))
```
因为todoLabels中的month都是有0填充空位的，后面的includes里面item的month是没有0填充的，所以导致2019-07-11不等于2019-7-11

**Comment by treadpit** [comment]
是使用日历组件出现这个问题的？我试了下没有出现这个问题，但这里判断确实不够严谨

**Comment by haogg1996** [comment]
> 是使用日历组件出现这个问题的？我试了下没有出现这个问题，但这里判断确实不够严谨

是的，可能是我从后台取得日期然后设置待办事项，导致日期数字格式不一致

**Comment by treadpit** [comment]
好的，我这里处理下，感谢反馈
