### ISSUE TITLE
关于week view和selected Days的问题

### ISSUE THREAD

**Issue by coldestlin** [treadpit/wx_calendar#143]
感谢作者开发这个精美的日历库，但引入使用后遇到不少问题，不知道是不是哪里设置错误（看完了文档，没仔细看源代码的实现）：

引入方法： 使用component方式引入
组件版本：当前日期master branch的最新版本（总觉得我用的版本跟issue里其他人不一样)
小程序版本库: 2.5.2

### 关于week view的问题
1. 切换week view之后，无法一直保持week view？ 点击顶部的<和《 `都会再次激活month模式，而且在month触发事件中写switchView('week’)无法成功。需要一种奇怪的方式切换才能回到weekview模式：
```
  this.calendar.switchView('month');
    setTimeout(()=>{
      this.calendar.switchView('week');
    }, 800)
```

2. 在 afterCalendarRender(e)之后触发switchView('week')，无效。在这里设置clearTodoLabels并setTodolabels也无效。
3. this.calendar.jump操作之后，weekview模式会变得无效，再次设置switchView也无法切换成功。
4. 在week view的时候，顶部的<和《这种筛选日期的方式可以隐藏掉吗？ 想要在week view的时候只支持滑动。

5. 发现switch View有时候只切换了一半，比如下图中jumpto是7月8号，结果是1号到6号的日期都被隐藏了，可是14号到31号的并没有。

![image](https://user-images.githubusercontent.com/19356579/61761681-00e9ca00-ae02-11e9-8f83-696a9accbeab.png)

### 关于选择日期的问题

1. 如何消除多选模式下选择的所有日期，文档里没有暴露出类似clearSelectedDays这种方法，只有labels有clearTodoLabels。
2. 开启multi模式的时候，点击多个日期没有出现点击标记，只有切换月份，再切换回来的时候才能看到，看起来是没有及时刷新？ 不开启multi模式，点击后也没看到红点在及时的切换。

### 关于todoLabels
1. 文档中todoLabels可以设置text备注，但是好像没有作用？ 我以为是点击的时候会显示设置的text.

**Comment by haorendashu** [comment]
我也在 week view 下遇到了不少问题，补充一下：

week view下，滑动到下一个月后重新打开 month view，日历自动选择了当月的第一天。或者说如果week view下显示的如果不是当前月，打开后都会自动选择当前月的第一天。期望：不自动选择。

**Comment by coldestlin** [comment]
还有新的问题, 只要存在jump的操作, 当前页面的 todoLabels 标记就被清空了...

**Comment by treadpit** [comment]
周视图开发的时候参考的是小米日历周视图日历的表现，这种模式下不能切换年月份，没有做相关逻辑，这里忘了做限制及说明。

**Comment by treadpit** [comment]
周视图模式头部操作已做逻辑控制，参考最新文档中：

```js
{
   hideHeadOnWeekMode: true, // 周视图模式是否隐藏日历头部
   showHandlerOnWeekMode: true, // 周视图模式是否显示日历头部操作栏，hideHeadOnWeekMode 优先级高于此配置
}
```

**Comment by coldestlin** [comment]
上面提到的关于选择日期的问题不知道有解答吗,  单选模式下如何取消选择状态,多选模式下如何批量取消, 有没有暴露函数出来?

**Comment by treadpit** [comment]
1. 单选模式下取消日期选择请参考文档配置 `inverse`
2. 取消选中所有日期已提供API，同步最新 `master` 代码，调用如下API即可：

```js
  this.calendar.cancelAllSelectedDay();
```

**Comment by haorendashu** [comment]
还有一个问题：
例如周模式下选择了7月31日，切换回去月模式，自动选择了当月的第一天。也就是说如果周模式下滑动到了其他月份的话，切换回去月模式，都会自动选择这个这个月的第一天。

**Comment by treadpit** [comment]
@haorendashu 好的，是个bug
