### ISSUE TITLE
选中日期时候待办事件隐藏了  如何让他不隐藏呢

### ISSUE THREAD

**Issue by BinHQing** [treadpit/wx_calendar#144]
setSelectedDays 选中日期后 待办事件隐藏了如何让他选中之后不隐藏呢

**Comment by BinHQing** [comment]
noDefault: true  返回页面再次进来还是回选择啊

**Comment by treadpit** [comment]
1. 目前代办事项点击后会默认隐藏代办标记。
2. 再次返回页面是指什么情况，另外看下页面逻辑是否再次返回后 `noDefault` 值发生了变化

**Comment by coldestlin** [comment]
应该跟我遇到的一样, 设置了代办事项, 但是只要jump一次, 代办事项就都被隐藏了.  jump先,再设置代办事项,也无法设置成功.

使用场景是这样的: 想要在打开的时候,自动跳转到最近一次代办事项,可能是几个月前.

**Comment by treadpit** [comment]
this.calendar.jump 及 this.calendar.setTodoLabels 是否是在日历初始化完成 (`afterCalendarRender` 方法内 )才调用的? @coldestlin

**Comment by coldestlin** [comment]
不是, 是在`onLoad`或者`onReady`里调用的. 事实上`afterCalendarRender` 方法根本无法调用...

尝试放在afterCalendarRender: 
```
/**
   * 日历初次渲染完成后触发事件，如设置事件标记
   */
  afterCalendarRender(e) {
    console.log('afterCalendarRender', e);
    this.calendar.jump(2019, 7, 12)   
  },
```

![image](https://user-images.githubusercontent.com/19356579/62261875-5436ca80-b449-11e9-896e-d68034a4b2dc.png)

**Comment by treadpit** [comment]
能否提供最小demo，试了下如下代码没有问题：

```js
const todos = [
  {
    year: '2019',
    month: '7',
    day: '15'
  },
  {
    year: 2019,
    month: 7,
    day: 18,
    todoText: '待办'
  }
];

const conf = {
  data: {
    calendarConfig: {}
  },
  afterCalendarRender(e) {
    this.calendar.setTodoLabels({
      circle: true,
      days: todos
    });
    this.calendar.jump(2019, 7, 21);
  }
};

Page(conf);
```

**Comment by treadpit** [comment]
![testimg](https://user-images.githubusercontent.com/10692855/62262170-564d5900-b44a-11e9-9573-4bcb336c6cb2.gif)

**Comment by coldestlin** [comment]
我下载的是几天前的master版本, 看了你的測試demo我又下载了master列表最新的源码,afterCalendar的触发终于可以识别this.calendar了,應該被修復了. ((輸入法突然變繁體了..)

跳轉和label的顯示問題我嘗試了幾遍後解決了,感謝作者~~

### jump後label無效的原因


jump後label無效,切換月份後再切換回來後,重新展示. 

![image](https://user-images.githubusercontent.com/19356579/62264563-f909d580-b452-11e9-8af8-e47ea5d91e40.png)

![image](https://user-images.githubusercontent.com/19356579/62262591-d3c59900-b44b-11e9-9d6e-1a3bff1ccca1.png)

反復嘗試後, 終於找到之前設置jump後setlabels無效的原因, 可能也是哪個地方觸發的小bug: 

 我用```   let [year, month, day] = latestDt.split('-');``` 得到的是字符串類型, 設置jump('2019', '07', '21')後可以跳轉成功,但是labels就消失了, 修改爲數字之後,一切就正常了. 

```

// pages/demo/demo.js

const todos = [
  {
    year: '2019',
    month: '7',
    day: '15'
  },
  {
    year: 2019,
    month: 7,
    day: 18,
    todoText: '待办'
  }
];

const conf = {
  data: {
    calendarConfig: {}
  },
  afterCalendarRender(e) {
    this.calendar.setTodoLabels({
      circle: true,
      days: todos
    });
    this.calendar.jump('2019','07', '21');

  },
  onLaunch: function () {
    // this.calendar.setTodoLabels({
    //   circle: true,
    //   days: todos
    // });
    // this.calendar.jump(2019, 7, 22);
  },

  onReady: function(){
   
  }
};

Page(conf);

```


ps: 不過todoLabels中的 todoText不知道有什麼用,點擊後也沒看到哪裏有新的提示... 

```
   {
        year: 2019,
        month: 7,
        day: 18,
        todoText: '待办'
      }
```

###  給其他人的tips: 

如果在onLoad中設置labels和todo, 則依然無法顯示labels, 這時候calendar應該還未渲染完成,  在onReady中則沒有問題, 具體看上面被注釋掉的代碼.

**Comment by treadpit** [comment]
好的，`todoText` 字数过多显示问题应该是个bug，没有处理这种样式，在页面初始化时，如果要操作日历API最好是在 `afterCalendarRender ` 之后

**Comment by BinHQing** [comment]
this.calendar.cancelAllSelectedDay();  取消所有选中没有效果 找不到这个事件啊
![image](https://user-images.githubusercontent.com/35362146/62341448-02a84180-b516-11e9-93d8-ba027f56bb3b.png)

**Comment by treadpit** [comment]
@BinHQing 是最新 `master` 代码么？这边试了下没有问题，如果还有问题请新开 `issue` 并提供最小`demo` 利于复现
