### ISSUE TITLE
在组件中引入日历组件

### ISSUE THREAD

**Issue by ChendayUP** [treadpit/wx_calendar#145]
设置this.calendar.setSelectedDays(toSet)时报错,
![WX20190730-115905](https://user-images.githubusercontent.com/20022523/62099692-84536180-b2c1-11e9-9a79-47db38fb6a2f.png)
请问在什么时候引入呢?

**Comment by treadpit** [comment]
文档中的 `this` 指向的是 `Page`，你在组件中调用该方法，`this` 指向的是你自己的组件，而非 `Page`

**Comment by ChendayUP** [comment]
那我应该如何正确初始化呢?

**Comment by treadpit** [comment]
引入组件就已经初始化了，如果是在页面调用 `API`，可直接使用 `this.calendar.jump() ` 等操作。

如果 `this` 不指向当前页面，也有两种方式：

1. 可以[参考文档事件调用的第二种方式](https://treadpit.github.io/wx_calendar/?id=%E6%97%A5%E5%8E%86%E4%BA%8B%E4%BB%B6%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)

2. 使用微信小程序提供的全局方法 `getCurrentPages()` 来获取当前页面实例，调用挂在在该页面实例上的 `API` 即可

**Comment by ChendayUP** [comment]
第二个方法使用报错
<img width="644" alt="QQ20190804-170144@2x" src="https://user-images.githubusercontent.com/20022523/62421771-b86fbd80-b6d9-11e9-9a2d-68e0ddfecc4a.png">
![QQ20190804-170212](https://user-images.githubusercontent.com/20022523/62421773-bdcd0800-b6d9-11e9-8e89-83b3aea70d96.png)
手动引入方法成功

**Comment by treadpit** [comment]
请仔细阅读微信官方文档，了解 `getCurrentPages()`  的使用方法的及其返回值是什么。
