### ISSUE TITLE
待办标记真机调试位置发生偏移

### ISSUE THREAD

**Issue by nuaajiangteng** [treadpit/wx_calendar#148]
模拟器里面是正确，真机调试出现位置偏移
![WechatIMG14](https://user-images.githubusercontent.com/29668874/62287814-810cd100-b48d-11e9-8eef-8746343bc238.jpeg)

**Comment by treadpit** [comment]
@nuaajiangteng 已修复，同步最新 `master` 代码试下

**Comment by nuaajiangteng** [comment]
@treadpit 可以了，感谢

**Comment by nuaajiangteng** [comment]
感谢大佬，可以了




------------------ 原始邮件 ------------------
发件人: "imfu"<notifications@github.com>;
发送时间: 2019年8月2日(星期五) 下午2:01
收件人: "treadpit/wx_calendar"<wx_calendar@noreply.github.com>;
抄送: "江腾"<872235113@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [treadpit/wx_calendar] 待办标记真机调试位置发生偏移 (#148)




@nuaajiangteng 已修复，同步最新 master 代码试下
