### ISSUE TITLE
用TypeScript时，怎么得到calendar

### ISSUE THREAD

**Issue by dtianyu** [treadpit/wx_calendar#154]
用TypeScript时，调用this.calendar.setTodoLabels({})报错
需要如何正确得到this.calendar

**Comment by treadpit** [comment]
报错是指方法报错还是typescript类型提示错误，如果是方法报错，是什么错误呢

**Comment by dtianyu** [comment]
感谢回复，问题找到了，需要在onReady()中调用。
组件很不错。
