### ISSUE TITLE
如何在onLoad中和onShow中取到this.calendar对象

### ISSUE THREAD

**Issue by Zfang0620ls** [treadpit/wx_calendar#164]

**Comment by Zfang0620ls** [comment]
this.calendar打印是undefined。需要在页面一进来的时候就获取禁止选中的日期并设置，但是取不到日历对象。

**Comment by Zfang0620ls** [comment]
手动引入解决了

**Comment by treadpit** [comment]
日历组件提供了 `afterCalendarRender ` 方法，日历渲染完成才会绑定相应的事件。

所以在 `onLoad` 或 `onShow` 里面去调用方法可能会存在问题。
