### ISSUE TITLE
Cannot read property 'firstDayOfWeek' of null

### ISSUE THREAD

**Issue by studiousryan** [treadpit/wx_calendar#169]
在 JSON 中配置 及 WXML 文件中引入后，编译报错。
![1567199235197](https://user-images.githubusercontent.com/19586353/64051305-3b871500-cbad-11e9-93a7-6b3fc4ce17f2.jpg)

**Comment by treadpit** [comment]
引用之后有做其他操作么？

**Comment by treadpit** [comment]
@studiousryan 已修复，同步 `master` 即可
