### ISSUE TITLE
希望增加每天有无事件的功能，即如日期有事件信息在日历相应日期下显示一个圆点。

### ISSUE THREAD

**Issue by caohaidong** [treadpit/wx_calendar#17]
首先感谢作者的辛苦。
希望能增加以下功能：
1.日历视图中相应日期有无事件的标志，可设置参数开启或关闭；
2.增加对日历视图背景、文字、选中时等状态颜色自定义主题的功能。
再次感谢作者。

**Comment by 6H5** [comment]
感谢作者的辛苦。
不过我很渴望能够和自己的数据绑定，就是在日历中每天显示的当然的一条数据。

**Comment by treadpit** [comment]
@caohaidong  感谢反馈，"有无事件的标志" 的标志是指比如：有事件的话就在当前日期下边类似加点标记之类的么？关于自定义选中状态等正在开发中。

**Comment by treadpit** [comment]
@6H5 你好，没太明白 “在日历中每天显示的当然的一条数据” 的意思？

**Comment by caohaidong** [comment]
@treadpit 是的，有事件的话就在当前日期下边类似加点或其他标记。谢谢，辛苦了。
