### ISSUE TITLE
关于初始加载周视图的问题

### ISSUE THREAD

**Issue by nifengiii** [treadpit/wx_calendar#171]
初始加载周视图后 周视图变成了8天的日期
![image](https://user-images.githubusercontent.com/38681363/64232362-69a98380-cf24-11e9-94d5-7634a1ef01ea.png)

![image](https://user-images.githubusercontent.com/38681363/64232386-74641880-cf24-11e9-831b-dfc293d88f81.png)

**Comment by nifengiii** [comment]
而且星期与农历显示错位

**Comment by treadpit** [comment]
在哪里初始化周视图的呢？能否提供相关最小复现demo，测试了master代码是没有复现该问题

![image](https://user-images.githubusercontent.com/10692855/64260556-a9d92800-cf5d-11e9-9bf2-3ae9f05b15ef.png)

**Comment by nifengiii** [comment]
您这边把Sun改成Mon 默认按照周一开始 就会出现周日期为8天的bug

**Comment by nifengiii** [comment]
再就是您这边能提供一下周月视图切换按钮的js吗 因为自己这边这个功能还没有完善 想借鉴一下您的

**Comment by treadpit** [comment]
周视图问题已修复。

> 再就是您这边能提供一下周月视图切换按钮的js吗 因为自己这边这个功能还没有完善 想借鉴一下您的

这个是指什么意思呢？

**Comment by nifengiii** [comment]
这边已经解决了，谢谢您的修复与回答

**Comment by treadpit** [comment]
好的 👍
