### ISSUE TITLE
设置firstDayOfWeek的BUG

### ISSUE THREAD

**Issue by yzphp** [treadpit/wx_calendar#173]
设置firstDayOfWeek时，切换周模式日期与星期对不上 滑动之后才对的上

**Comment by treadpit** [comment]
具体的操作是什么，能否提供出现此问题的操作步骤及最小复现demo。

![image](https://user-images.githubusercontent.com/10692855/64421903-48d46000-d0d5-11e9-83d1-00e5510240c9.png)

**Comment by yzphp** [comment]
我换上最新版，这个问题已经不存在。辛苦了！谢谢！
有一个小建议就是周试图的时候滑动可以获取当前周的信息

**Comment by treadpit** [comment]
OK。

> 有一个小建议就是周试图的时候滑动可以获取当前周的信息

下个版本会带上获取当前日历面板显示的日期

**Comment by treadpit** [comment]
@yzphp  

同步 `master` 代码，[参考文档配置onSwipe](https://treadpit.github.io/wx_calendar/?id=_3-%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE) ，调用函数 [getCalendarDates()](https://treadpit.github.io/wx_calendar/?id=_13-%E8%8E%B7%E5%8F%96%E5%BD%93%E5%89%8D%E6%97%A5%E5%8E%86%E9%9D%A2%E6%9D%BF%E6%97%A5%E6%9C%9F) 可获取当前周信息

**Comment by yzphp** [comment]
我试了这个功能挺好用的，附加建议
1、农历的输入可以设置默认值，
2、滑动周能获取到滑动之后的周数据，其实就像whenChangeMonth，有一个当前周信息也有一个滑动之后的日期信息   这样可能就很完美了！

**Comment by treadpit** [comment]
> 1. 滑动周能获取到滑动之后的周数据

这个之前没提交，现在同步 `master`，需配置:

```xml
 bind:whenChangeWeek="whenChangeWeek"
```

即可在`whenChangeWeek(e)` 中拿到：

![image](https://user-images.githubusercontent.com/10692855/64508404-f2069a80-d30f-11e9-806c-62d7112e7dd3.png)


> 2. 农历的输入可以设置默认值。

这个不太清楚表达的是什么意思。

#### 另外如果是其他bug或者支持麻烦新开 `issue`。
