### ISSUE TITLE
你好，问下如何只给当天的日期加样式？

### ISSUE THREAD

**Issue by humm000** [treadpit/wx_calendar#182]

**Comment by treadpit** [comment]
没太明白你的意思

**Comment by humm000** [comment]
就是比如今天是20号，我想在20号小号加个点的样式，明天21号，标记的点就在21号下面，只控制当天日期的样式显示


| |
胡苗苗
邮箱：humiao_268@163.com
|

签名由 网易邮箱大师 定制

在2019年09月20日 22:59，imfu 写道：

没太明白你的意思

**Comment by treadpit** [comment]
每次进入日历设置当天为待办就行呀

**Comment by humm000** [comment]
嗯，我现在做的是打卡功能，打卡的标记我按照的就是代办。就是加的一个需求需要在当天的时间下面标记和点，也用待办的话，不会冲突吧
| |
胡苗苗
邮箱：humiao_268@163.com
|

签名由 网易邮箱大师 定制

在2019年09月20日 23:13，imfu 写道：

每次进入日历设置当天为待办就行呀

**Comment by treadpit** [comment]
冲突是指选中样式和待办标记不能同时显示么？ 

如果是这个问题，设置待办时可[参考文档](https://treadpit.github.io/wx_calendar/?id=_9-1-%E8%AE%BE%E7%BD%AE%E5%BE%85%E5%8A%9E%E4%BA%8B%E9%A1%B9)配置属性 `showLabelAlways`

```js
this.calendar.setTodoLabels({
 ...,
 showLabelAlways: true, // 点击时是否显示待办事项（圆点/文字），在 circle 为 true 及当日历配置showLunar 为 true 时，此配置失效
  days: []
});
```

**Comment by humm000** [comment]
非常感谢，我明天抓紧再试一下，感谢感谢


| |
胡苗苗
邮箱：humiao_268@163.com
|

签名由 网易邮箱大师 定制

在2019年09月20日 23:46，imfu 写道：

冲突是指选中样式和待办标记不能同时显示么？

如果是这个问题，设置待办时可参考文档配置属性 showLabelAlways

this.calendar.setTodoLabels({

 ...,

 showLabelAlways:true, // 点击时是否显示待办事项（圆点/文字），在 circle 为 true 及当日历配置showLunar 为 true 时，此配置失效

  days: []

});

**Comment by humm000** [comment]
这个方法我还用不到，然后我现在试着设置可选日期范围，为什么enableArea一直报错

**Comment by treadpit** [comment]
报错具体是指什么错误？

![image](https://user-images.githubusercontent.com/10692855/65366405-f6a74900-dc55-11e9-8e7b-fe8dab56b1ac.png)

**Comment by humm000** [comment]
我用的第二个那个日历，Template示例

**Comment by treadpit** [comment]
> 我用的第二个那个日历，Template示例

template 已经没有维护了，另外你是怎么调用的，能否贴下代码，我这边试了下没有抛错

**Comment by humm000** [comment]
enableArea(['2019-09-20', '2019-10-28']);




| |
胡苗苗
邮箱：humiao_268@163.com
|

签名由 网易邮箱大师 定制

在2019年09月21日 10:12，imfu 写道：

我用的第二个那个日历，Template示例

template 已经没有维护了，另外你是怎么调用的，能否贴下代码，我这边试了下没有抛错

**Comment by treadpit** [comment]
调用方法是没有问题的，报错是什么错误？

**Comment by humm000** [comment]
VM139793:1 thirdScriptError
enableArea is not defined;at api request success callback function
ReferenceError: enableArea is not defined




| |
胡苗苗
邮箱：humiao_268@163.com
|

签名由 网易邮箱大师 定制

在2019年09月21日 10:22，imfu 写道：

调用方法是没有问题的，报错是什么错误？

**Comment by treadpit** [comment]
是在日历还没渲染完成就调用这个方法了？

**Comment by humm000** [comment]
相当于一进来就调用了，不过我是看方法里就写在这个位置，直接打开注释的




| |
胡苗苗
邮箱：humiao_268@163.com
|

签名由 网易邮箱大师 定制

在2019年09月21日 10:26，imfu 写道：

是在日历还没渲染完成就调用这个方法了？

**Comment by treadpit** [comment]
你 `debug` 看下呢，目前我这边试了下没有问题

![image](https://user-images.githubusercontent.com/10692855/65366816-8d2a3900-dc5b-11e9-9294-ad60a705750c.png)

**Comment by humm000** [comment]
![1569033636674](https://user-images.githubusercontent.com/55486088/65366865-4f79e000-dc5c-11e9-80af-006b4ac25b8a.jpg)
![1569033688315](https://user-images.githubusercontent.com/55486088/65366892-a1bb0100-dc5c-11e9-91e2-15df0acd3b4d.jpg)
我下载来的源码，直接打开的话，也是这个报错

**Comment by treadpit** [comment]
那你看下你调用的这个方法是否真的没有定义呢？看起来是找不到这个方法

**Comment by humm000** [comment]
js里是有的，不过我还是看不太懂具体的方法，不好下手😅




| |
胡苗苗
邮箱：humiao_268@163.com
|

签名由 网易邮箱大师 定制

在2019年09月21日 11:58，imfu 写道：

那你看下你调用的这个方法是否真的没有定义呢？看起来是找不到这个方法

**Comment by treadpit** [comment]
这里还没走到日历js的具体的方法里面，调用的时候还没有引入该函数

**Comment by humm000** [comment]
那我应该具体怎么改，才能正常用这个方法呐


| |
胡苗苗
邮箱：humiao_268@163.com
|

签名由 网易邮箱大师 定制

在2019年09月21日 13:46，imfu 写道：

这里还没走到日历js的具体的方法里面，调用的时候还没有引入该函数

**Comment by treadpit** [comment]
这个要具体分析你的代码才知道了，因为你这里都还没有进入到这个小程序js库里面。可以找朋友帮忙看看，实在搞不定的话，私聊我吧，就不在这里讨论了。

**Comment by humm000** [comment]
好的，谢谢了！我要加您微信吗


| |
胡苗苗
邮箱：humiao_268@163.com
|

签名由 网易邮箱大师 定制

在2019年09月21日 14:28，imfu 写道：

这个要具体分析你的代码才知道了，因为你这里都还没有进入到这个小程序js库里面。可以找朋友帮忙看看，实在搞不定的话，私聊我吧，就不在这里讨论了。

**Comment by treadpit** [comment]
你查看下邮件
