### ISSUE TITLE
待办事项设置了，但没有显示。

### ISSUE THREAD

**Issue by lexiang** [treadpit/wx_calendar#187]
![屏幕截图(5)](https://user-images.githubusercontent.com/28833985/65524429-5cc6f100-df20-11e9-9fb1-3be4675ddf83.png)
数据都有呀，为什么不显示标记。
`afterCalendarRender(event) {
    console.log("afterCalendarRender", event);
    this.calendar.setTodoLabels({
      pos: "bottom", // 待办点标记位置 ['top', 'bottom']
      dotColor: "#40", // 待办点标记颜色
      circle: false, // 待办圆圈标记设置（如圆圈标记已签到日期），该设置与点标记设置互斥
      showLabelAlways: true, // 点击时是否显示待办事项（圆点/文字），在 circle 为 true 及当日历配置 showLunar 为 true 时，此配置失效
      days: [{
        year: 2019,
        month: 9,
        date: 19,
        todoText: "有课"
      }]
    });
  },`

**Comment by lexiang** [comment]
搞明白了，自己的问题。

**Comment by 491134648** [comment]
怎么解决的呢，我怕也是这种
