### ISSUE TITLE
关于事件标记的问题

### ISSUE THREAD

**Issue by azxj** [treadpit/wx_calendar#19]
第一个问题是，事件标记只能设置在当前月嘛？我试了设置其他月份的事件标记，都是没有显示出来的；
第二个问题是，setTodoLabels方法为什么不能在**非initCalendar的地方**调用呢？如果不能的话，要怎么实现**动态更新有事件标记的日期**呢？
最后表达一下对作者的感谢之情~帮了我挺大忙的

**Comment by treadpit** [comment]
你好，
第一个问题，可以设置多个月份的。
第二个问题，提供了单独的事件可以动态更新的。
我试了下`master`分支，是没问题的，详情见下图，不知道是不是你要的效果：

![screen_shot](https://user-images.githubusercontent.com/10692855/40593511-809af772-625b-11e8-8ff3-02017620a7d9.gif)

**Comment by azxj** [comment]
@treadpit 好的非常感谢，之前我用法上有错误所以没有成功，现在可以了，但是还有一个问题是，之前设置过的事件标记是没办法取消掉的吗？我用空数组调用`setTodoLabels`，之前的事件标记并没有消失，也就是只能新增标记而不能删除标记。
我翻了一下你的源码，然后现在是采取直接调用`this.data.calendar.todoLabels = [];`，然后重新渲染calendar的方式来删除标记。

**Comment by treadpit** [comment]
@azxj 你好，这里会提供一个删除的方法，因为单独调用也不太可能每次全部重新写入，还是采用增量的，所以删除的方法会单独出来，今天我把这个方法添上，如果你着急的话，可以自己先扩展一下哈

**Comment by azxj** [comment]
好的，非常感谢！

**Comment by treadpit** [comment]
@azxj  新增了两个函数，`deleteTodoLabels([])`，` clearTodoLabels()`，已合并至 `maser` 分支
