### ISSUE TITLE
时间戳是服务器返回，请问如何将时间传入组件

### ISSUE THREAD

**Issue by XieShangZheng** [treadpit/wx_calendar#191]
首先感谢大神代码，我的日期时间是根据后台接口返回的，请问日历的年月日如何根据后台返回的今日时间设置。

遇到的问题，现在是获取的日期是本地的，但是用户的手机日期如果不准确的话，日历就不准了。

需求，传入当月日期，日历根据传入的日期展示当月日期。

例如：传入 201909 展示 201909月份的日期

**Comment by treadpit** [comment]
展示指定月份数据，在日历渲染完成，调用 `jump` 函数即可

``js
this.calendar.jump(2018, 6); // 跳转至某月
this.calendar.jump(2018, 6, 6); // 跳转至某日
```

**Comment by XieShangZheng** [comment]
对对对，昨天提问完，又去翻了翻代码，在文档里最后找到了。谢谢大神！
