### ISSUE TITLE
关于  setSelectedDays 的问题

### ISSUE THREAD

**Issue by onetyb** [treadpit/wx_calendar#204]
a页面设置 this.calendar.setSelectedDays() 后，进入b页面 用navigateBack返回a页面，a页面就无法使用 this.calendar.setSelectedDays()，现在我需要更新默认日期，请问有什么方法吗？

**Comment by treadpit** [comment]
这个是业务的实现问题哈，页面通过 `back` 方式返回会触发 `onShow`，你可以去这里去做判断处理，重新弄调用 `this.calendar.setSelectedDays()`

**Comment by onetyb** [comment]
我现在就是这么干的，但是触发返回之后，onShow里再次调用this.calendar.setSelectedDays()  没有任何变化

**Comment by treadpit** [comment]
那需要调试看下，我这边测了下没有发现问题

![s](https://user-images.githubusercontent.com/10692855/68731761-1e8aab80-060c-11ea-9721-4255224ba390.gif)
