### ISSUE TITLE
日历点击事件先点击当前月，再点击其他月不会报错，直接点击其他月份会报错

### ISSUE THREAD

**Issue by hepeng-ice** [treadpit/wx_calendar#21]
![qq 20180531145843](https://user-images.githubusercontent.com/19882255/40766781-38a7eabc-64e3-11e8-81fe-be4fb308dbf7.png)
![qq 20180531145922](https://user-images.githubusercontent.com/19882255/40766782-39094e4c-64e3-11e8-8d68-770dfd4ba114.png)

**Comment by treadpit** [comment]
@hepeng-ice 你好，感谢反馈，是个`bug`，已修复
