### ISSUE TITLE
根据日期不同状态设置不同的样式

### ISSUE THREAD

**Issue by guanmu666** [treadpit/wx_calendar#210]
如题

**Comment by treadpit** [comment]
单独的样式是指全部自定义，还是部分？因小程序组件的 `externalClasses` 属性暂时不支持动态设置，所以如果要自定义需要采用 `style` 实现。但日期的的 `wxml` 结构不只是一个元素，所以采取 `style` 方式不能很好的控制各个元素的样式（提供各个元素操作 `style` 的方法太过繁琐）

**Comment by guanmu666** [comment]
比如 这个月的15，16日设置成忙碌状态（灰色），19，20设置成休息（红色）

**Comment by guanmu666** [comment]
> 单独的样式是指全部自定义，还是部分？因小程序组件的 `externalClasses` 属性暂时不支持动态设置，所以如果要自定义需要采用 `style` 实现。但日期的的 `wxml` 结构不只是一个元素，所以采取 `style` 方式不能很好的控制各个元素的样式（提供各个元素操作 `style` 的方法太过繁琐）

比如 这个月的15，16日设置成忙碌状态（灰色），19，20设置成休息（红色）

**Comment by treadpit** [comment]
简单理解为日期具有不同状态，不同状态字体颜色不一致，可以提供一个 `API` 做控制

**Comment by treadpit** [comment]
[`experimental` 分支](https://github.com/treadpit/wx_calendar/tree/experimental) 增加了实验性 API: ` setDateStyle()`。

> 注：该 `API` 只会对日期生效。

因使用 `style` 注入的方式过于繁重，组件样式隔离采用了 `apply-shared` 方案，此模式下页面样式会影响组件样式，使用时需注意页面样式对日历组件样式的覆盖。

使用方法如下：

```js
// 页面 js 文件
const toSet = [
   {
        year: 2019,
        month: 11,
        day: 19,
        class: 'blue-date other-class' // 页面定义的 class，多个 class 由空格隔开
    },
    {
        year: 2019,
        month: 11,
        day: 28,
        class: 'orange-date'
     }
];
this.calendar.setDateStyle(toSet);
```

```css
/* 页面 css 文件 */
.blue-date {
   color: blue;
}

.orange-date {
   color: #f40
}
```

如下图所示：

![image](https://user-images.githubusercontent.com/10692855/68987616-2cd40400-0866-11ea-9464-9ac9bce3824d.png)

**Comment by kk9955** [comment]
let  toSet1 = [
            {
                year: 2019,
                month: 12,
                day: 29,
                class: 'orange-date other-class' // 页面定义的 class，多个 class 由空格隔开
            },
            {
                year: 2019,
                month: 12,
                day: 30,
                class: 'orange-date other-class' // 页面定义的 class，多个 class 由空格隔开
            }
        ];


let  toSet2 = [
            {
                year: 2019,
                month: 12,
                day: 30,
                class: 'orange-date other-class' // 页面定义的 class，多个 class 由空格隔开
            },
            {
                year: 2019,
                month: 12,
                day: 31,
                class: 'orange-date other-class' // 页面定义的 class，多个 class 由空格隔开
            }
        ];
        this.calendar.setDateStyle(toSet1);
        this.calendar.setDateStyle(toSet2);       

请问这么连续调用  第二个      this.calendar.setDateStyle(toSet2);      不起作用吗

**Comment by treadpit** [comment]
@kk9955 `setDateStyle()` 目前未支持增量

**Comment by treadpit** [comment]
同步 `experimental` 分支，`setDateStyle` 已支持增量更新。

**Comment by kk9955** [comment]
setDateStyle    箭头切换月份和年份，  setDateStyle（）之前设置的标记就没了

**Comment by treadpit** [comment]
> setDateStyle 箭头切换月份和年份， setDateStyle（）之前设置的标记就没了

已知 `BUG`，我提交一下
