### ISSUE TITLE
请问怎么默认选中周视图？

### ISSUE THREAD

**Issue by kk9955** [treadpit/wx_calendar#215]
请问怎么默认选中周视图？

**Comment by treadpit** [comment]
结合 `afterCalendarRender()` 使用 `this.calendar.switchView('week')`

**Comment by kk9955** [comment]
但是   是不是又触发了afterCalendarRender 事件

**Comment by treadpit** [comment]
`afterCalendarRender()` 只会在页面初次进入后第一次初始化日历时触发

**Comment by callmesoul** [comment]
这样子又个问题，会先渲染成月视图然后再渲染成周试图，会有很明显的闪动啊，又没有办法初始化时就直接周试图呢？
