### ISSUE TITLE
请教下，能否实现将当天日期替换为“今”，如果可以，怎么实现？

### ISSUE THREAD

**Issue by amyhuangxbd** [treadpit/wx_calendar#218]
![image](https://user-images.githubusercontent.com/4026511/69033917-ff7c8700-0a1a-11ea-982b-374931996877.png)

**Comment by treadpit** [comment]
最快的方法，可以在 `wxml` 中修改渲染日期那里：

```xml
{{item.day}} => {{item.isToday ? '今' : item.day}}
```
