### ISSUE TITLE
能阻止左滑右滑的时候切换月份吗？

### ISSUE THREAD

**Issue by wupopo** [treadpit/wx_calendar#224]

**Comment by treadpit** [comment]
目前没有做相关配置，若急需该功能可自行临时修改处理：

打开 [/src/component/calendar/index.js](https://github.com/treadpit/wx_calendar/blob/master/src/component/calendar/index.js) 文件，在 `calendarTouchmove` 函数中阻止处理滑动事件。或者删除 `wxml` 中对日历的 `touch` 事件的绑定

**Comment by treadpit** [comment]
```js
calendarConfig: {
     preventSwipe: true, // 是否禁用日历滑动切换月份
}
```

**Comment by wupopo** [comment]
> ```js
> calendarConfig: {
>      preventSwipe: true, // 是否禁用日历滑动切换月份
> }
> ```

谢谢啦
