### ISSUE TITLE
this.calendar 为什么未定义？

### ISSUE THREAD

**Issue by Tanglan123** [treadpit/wx_calendar#229]

**Comment by Tanglan123** [comment]
> 设置了选中日期，但是页面上没有选中的状态
> `setSelectedDays(["2019-11-11", "2019-11-12"]);`

应写成：
`setSelectedDays([
            //已经签到过的日期
            { year: 2019, month: 11, day: 11 },
            { year: 2019, month: 11, day: 13 },
        ]);`

**Comment by treadpit** [comment]
#213

**Comment by Tanglan123** [comment]
preventSwipe: true, // 是否禁用日历滑动切换月份
这个参数好像不起作用

**Comment by treadpit** [comment]
是否为最新的代码，如果不是，请同步 `master` 代码，这个是后来新增的功能

**Comment by Tanglan123** [comment]
> 是否为最新的代码，如果不是，请同步 `master` 代码，这个是后来新增的功能

最新的代码可以限制开始和结束日期么？

**Comment by treadpit** [comment]
功能都更新在文档里了，[可以参考下文档](https://treadpit.github.io/wx_calendar)。这个issue已关闭，就不在这里讨论了，如果有 `bug`或者 `feature` 反馈，可新开 `issue`。
