### ISSUE TITLE
treadpit：您好，能否给出一个完整的调用此日历组件的demo？谢谢感激不尽

### ISSUE THREAD

**Issue by zbebe** [treadpit/wx_calendar#230]
treadpit：
您好！
也不知道怎么称呼您，我是一名刚接触小程序的新手，以前接触过java和一点儿的C语言，还有MySQL数据库，现在对小程序特别感兴趣，看到您编写开发的这个微信小程序日历组件特别好，功能特别强大，于是就下载了您的这个日历组件，但是由于是新手不知道怎么使用，我是按照您的说明也不得要领，不会用，您能否给我一个完整的引用这个完美组件的源码，就是我用微信开发工具直接打开就能调试运行的，能否给我实现一个功能就行，就是实现在选中日期下面标记“事情代办”的标记，并且改变该选中日期的背景颜色。不胜感激，万分感谢，这几天来我就一直研究您的组件，想实现该组件提供的各项功能，但是苦于拙笨，始终不得要领，痛苦至极，请您赐教，谢谢您了，感激不尽！
热切盼复……

**Comment by zbebe** [comment]
在线苦等您的指教……谢谢

**Comment by treadpit** [comment]
`/src/pages/calendarComponent` 文件夹里就是使用的具体例子，其他的都是 `js` 的方法调用

**Comment by zbebe** [comment]
treadpit：好的，多谢指点，您不说我都不知道还有具体例子，按照您的指点我打开了，正在研究，有不懂的地方再向您请教，谢谢，谢谢
