### ISSUE TITLE
treadpit老师：如何实现用按钮控制农历的显示和隐藏？

### ISSUE THREAD

**Issue by zbebe** [treadpit/wx_calendar#231]
如题，如何在调用日历组件的页面中设置一个按钮，点击按钮使日历显示农历，再次点击按钮就不再显示农历，我知道showLunar这个参数来控制农历显示，但我不知道怎么用按钮改变这个参数的true和false值，我在页面中加了个按钮，<button bindtap='displaynongli'>是否显示农历</button>,然后是不是应该在页面的JS文件中加入下面这段代码？这个setData函数究竟应该怎么写？一直都弄不懂，求treadpit老师指教，谢谢
displaynongli() {
    this.setData({
  
    })
  },
还有一个问题，就是如何实现在日历组件上只能点选两个日期，在点选第二个日期后在日历上把两个日期之间的所有日期背景色连成一片？

**Comment by treadpit** [comment]
同步 `master` 代码，[参考文档配置](https://treadpit.github.io/wx_calendar/?id=_15-%E8%AE%BE%E7%BD%AE%E6%97%A5%E5%8E%86%E9%85%8D%E7%BD%AE)

**Comment by zbebe** [comment]
好的，谢谢您的指点，祝新年快乐！

在 2019-12-09 10:40:09，imfu <notifications@github.com> 写道：


Closed #231.
