### ISSUE TITLE
您好，请问有实现选择多个日期吗？自定义配置的功能是已经实现的还是未实现的

### ISSUE THREAD

**Issue by wyying** [treadpit/wx_calendar#234]

**Comment by treadpit** [comment]
1. 选中多个日期参考文档[设置选中多个日期](https://treadpit.github.io/wx_calendar/?id=_12-%E8%AE%BE%E7%BD%AE%E9%80%89%E4%B8%AD%E5%A4%9A%E4%B8%AA%E6%97%A5%E6%9C%9F)

2. 这个是指什么意思？

> 自定义配置的功能是已经实现的还是未实现的 ？
