### ISSUE TITLE
this.selectComponent("#calender")获取到对象，但是拿不到方法，我想要根据日期不同设置不同的样式，用的也是那个实验版本

### ISSUE THREAD

**Issue by OneDreamhou** [treadpit/wx_calendar#235]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by treadpit** [comment]
拿不到方法是指什么方法？日历组件提供的方法？

**Comment by OneDreamhou** [comment]
我昨天已经解决了就是按照样例，把this.calendar写在page外面可用，我之前使用selectcomponent（''）获取不到对象，然后我在使用setstyle那个方法发现有问题，等会我截图给你发过去


 
---原始邮件---
发件人: "imfu"<notifications@github.com&gt;
发送时间: 2019年12月3日 09:59:36
收件人: "treadpit/wx_calendar"<wx_calendar@noreply.github.com&gt;;
抄送: "OneDreamhou"<982515234@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [treadpit/wx_calendar] this.selectComponent("#calender")获取到对象，但是拿不到方法，我想要根据日期不同设置不同的样式，用的也是那个实验版本 (#235)



拿不到方法是指什么方法？日历组件提供的方法？

**Comment by treadpit** [comment]
好的，感谢反馈。`setDateStyle()` 这个方法因为没有比较全面的测试，放在实验性分支里面的，所以可能存在bug

**Comment by OneDreamhou** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "imfu"<notifications@github.com&gt;; 
发送时间: 2019年12月3日(星期二) 上午10:07
收件人: "treadpit/wx_calendar"<wx_calendar@noreply.github.com&gt;; 
抄送: "李文志"<982515234@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [treadpit/wx_calendar] this.selectComponent(&quot;#calender&quot;)获取到对象，但是拿不到方法，我想要根据日期不同设置不同的样式，用的也是那个实验版本 (#235)




好的，感谢反馈。setDateStyle() 这个方法因为没有比较全面的测试，放在实验性分支里面的，所以可能存在bug
