### ISSUE TITLE
treadpit老师：您好！请问此日历组件实现日期多选的功能的思路是什么？

### ISSUE THREAD

**Issue by zbebe** [treadpit/wx_calendar#237]
如题，看了您的代码，由于我是个新手，日期多选功能是真看不懂啊，感谢您的指教！

**Comment by treadpit** [comment]
数据驱动视图，改变对应的数据对象中的值即可

**Comment by zbebe** [comment]
谢谢！我过年期间按您的方法再试试，祝鼠年大吉，新春快乐！

在 2019-12-09 10:41:22，imfu <notifications@github.com> 写道：


数据驱动视图，改变对应的数据对象中的值即可
