### ISSUE TITLE
日历页面隐藏/显示

### ISSUE THREAD

**Issue by xiaodong86** [treadpit/wx_calendar#239]
目前使用wx:if 可切换 但每次都会重新初始化日历(之前选择的时间都重置了)
使用wx:hidden 切换无作用
有没有好的解决方法啊

**Comment by treadpit** [comment]
仔细阅读微信开发者文档 `hidden` 的使用就可以解决了哈

**Comment by xiaodong86** [comment]
嗯嗯 找到了,解决了 抱歉哈哈
