### ISSUE TITLE
wepy中引用插件，calendarConfig的配置不生效

### ISSUE THREAD

**Issue by nowpast** [treadpit/wx_calendar#241]
**BUG描述**

**复现步骤**
<template>
  <view class="container">
    <calendar calendarConfig="{{calendarConfig}}"></calendar>
  </view>
</template>
----------------------------------------
usingComponents: {
        'van-button': '../../components/vant/button/index',
        "calendar": "../../components/calendar/index"
      }

-----------------------------------------
data = {
      calendarConfig: {
        multi: true,
        theme: 'elegant'
      }
    }
**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/18032533/71073060-a12dfa00-21ba-11ea-82f2-1d9309c35e64.png)
![image](https://user-images.githubusercontent.com/18032533/71073103-b4d96080-21ba-11ea-9b5c-62e12aa7a2c8.png)

**Comment by chaseway** [comment]
同问

**Comment by treadpit** [comment]
`wxml` 中配置是否传入组件，使用最近的`wepy` 用如下代码测试没问题，
```vue
<template>
  <div class="container">
    <calendar :calendarConfig="calendarConfig"></calendar>
  </div>
</template>

<script>
import wepy from '@wepy/core'

wepy.page({
  data: {
    calendarConfig: {
      multi: true,
      theme: 'elegant'
    }
  }
})
</script>
<config>
{
    navigationBarTitleText: 'WePY 2.0 Feature Demo',
    usingComponents: {
      calendar: '../components/calendar/index'
    }
}
</config>

```
![image](https://user-images.githubusercontent.com/10692855/71139477-37106600-2249-11ea-9f67-0aaeedb2a9fc.png)
