### ISSUE TITLE
请问支持mpvue吗？在mpvue里如何使用，目前在mpvue里使用无法触发事件

### ISSUE THREAD

**Issue by tanhualang** [treadpit/wx_calendar#242]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**Comment by treadpit** [comment]
无法触发事件是指什么？

[参考此处引入wepy](https://github.com/treadpit/wx_calendar/issues/241#issuecomment-567301142)

**Comment by tanhualang** [comment]
> 无法触发事件是指什么？
> 
> [参考此处引入wepy](https://github.com/treadpit/wx_calendar/issues/241#issuecomment-567301142)

如onTapDay,afterCalendarRender等事件都无法触发

**Comment by treadpit** [comment]
> > 无法触发事件是指什么？
> > [参考此处引入wepy](https://github.com/treadpit/wx_calendar/issues/241#issuecomment-567301142)
> 
> 如onTapDay,afterCalendarRender等事件都无法触发

绑定事件的代码能否贴一下

**Comment by tanhualang** [comment]
> > > 无法触发事件是指什么？
> > > [参考此处引入wepy](https://github.com/treadpit/wx_calendar/issues/241#issuecomment-567301142)
> > 
> > 
> > 如onTapDay,afterCalendarRender等事件都无法触发
> 
> 绑定事件的代码能否贴一下
<calendar
      @onTapDay="onTapDay"
      @afterCalendarRender="afterCalendarRender"
    ></calendar>

onTapDay(e) {
    console.log(e)
  }
afterCalendarRender(e) {
    console.log(e)
  }
无法打印出e，换成bind:onTapDay，bind:afterCalendarRender也打印不出来。

**Comment by treadpit** [comment]
组件内部是采用小程序原生的 `triggleEvent` 来触发传入的事件，可查询 `mpvue` 是否原生组件及其`triggleEvent` 方法。
