### ISSUE TITLE
多日历组件无法跳转到指定日期

### ISSUE THREAD

**Issue by bighuangbee** [treadpit/wx_calendar#245]
this.calendar.jump(2020, 2, 1, '#calendar2'); // 跳转至某日

**Comment by treadpit** [comment]
关于多日历组件有有提供一个demo，详情见： `pages/calendarMoreComponent`，你试下这个是否有效，我这边测试OK

![image](https://user-images.githubusercontent.com/10692855/71565279-27fea300-2ae8-11ea-8ebc-f8eea81fdf46.png)

**Comment by bigHuangBee** [comment]
这样的配置不行    
calendarConfig1 : {
      multi: true, // 是否开启多选,
      theme: 'elegant', // 日历主题，目前共两款可选择，默认 default 及 elegant，自定义主题在 theme 文件夹扩展
      showLunar: false, // 是否显示农历，此配置会导致 setTodoLabels 中 showLabelAlways 配置失效
      inverse: 1, // 单选模式下是否支持取消选中,
      defaultDay: '2019-1-11', // string|boolean，string: 默认选中某天/boolean: 不自动选中任何日期
      highlightToday: false, // 是否高亮显示当天，区别于选中样式（初始化时当天高亮并不代表已选中当天）
      takeoverTap: true, // 是否完全接管日期点击事件（日期不会选中），配合 onTapDay() 使用
      disablePastDay: false, // 是否禁选当天之前的日期
      disableLaterDay: false, // 是否禁选当天之后的日期
      firstDayOfWeek: 'Mon', // 每周第一天为周一还是周日，默认按周日开始
      onlyShowCurrentMonth: true, // 日历面板是否只显示本月日期
      hideHeadOnWeekMode: true, // 周视图模式是否隐藏日历头部
  },

**Comment by treadpit** [comment]
你需要这么多的配置？

**Comment by bigHuangBee** [comment]
是的，做一个日历表，显示全年的月份

**Comment by treadpit** [comment]
因为这么多配置可能存在互斥的情况，我中午看下

**Comment by bigHuangBee** [comment]
好的

**Comment by treadpit** [comment]
请问 `this.calendar.jump(2020, 2, 1, '#calendar2');` 调用的上下文是什么
/是在 `afterCalendarRender` 之后调用的么？

**Comment by bigHuangBee** [comment]
在afterCalendarRender里面调用的

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: imfu <notifications@github.com&gt;
发送时间: 2020年1月2日 18:28
收件人: treadpit/wx_calendar <wx_calendar@noreply.github.com&gt;
抄送: weihua <1191352688@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[treadpit/wx_calendar] 多日历组件无法跳转到指定日期 (#245)




请问 this.calendar.jump(2020, 2, 1, '#calendar2'); 调用的上下文是什么
 /是在 afterCalendarRender 之后调用的么？

**Comment by treadpit** [comment]
因这里涉及的点稍多，如果急用可以先暂时使用宏任务，如下方法处理试试：

```js
afterCalendarRender() {
  setTimeout(() => {
    this.calendar.jump(2019, 7, 23, '#start');
  }, 100);
}
```
