### ISSUE TITLE
开启日期范围选择模式，配置文件defaultDay为true，点击日历报错

### ISSUE THREAD

**Issue by xichunjie** [treadpit/wx_calendar#246]
**BUG描述**
开启日期范围选择模式，点击日历报错
**复现步骤**
配置文件defaultDay为true或者 this.calendar.chooseDateArea(['2019-12-30', '2019-12-30']).then(dates => {
          console.log('choosed dates: ', dates);
        });选择日期段为同一天
**期望结果**
设置后可以选时间段
**实际结果**
配置文件defaultDay为true或者chooseDateArea(['2019-12-30', '2019-12-30'])后，当天被选择，不过点击别的日期时，报错“utils.js? [sm]:161 Uncaught (in promise) TypeError: Cannot read property 'year' of undefined
    at GetDate.toTimeStr (utils.js? [sm]:161)
    at Object.gotoSetContinuousDates (main.js? [sm]:212)”
**截图**

**Comment by treadpit** [comment]
已知 `bug`，中午修复提交

**Comment by xichunjie** [comment]
日期范围选择模式麻烦能不能可以选择同一天，因为项目里面进去首先是查询当天的，譬如2019-12-30--2019-12-30

**Comment by treadpit** [comment]
> 日期范围选择模式麻烦能不能可以选择同一天，因为项目里面进去首先是查询当天的，譬如2019-12-30--2019-12-30

这个晚上抽时间支持，中午先修复这个报错的问题哈

**Comment by treadpit** [comment]
> > 日期范围选择模式麻烦能不能可以选择同一天，因为项目里面进去首先是查询当天的，譬如2019-12-30--2019-12-30
> 
> 这个晚上抽时间支持，中午先修复这个报错的问题哈

```js
// 当连续时间为单天时
this.calendar.chooseDateArea(['2019-12-12']);
```
