### ISSUE TITLE
可以实现日历是一周一周进行滑动的吗

### ISSUE THREAD

**Issue by DuyinLoo88** [treadpit/wx_calendar#249]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/32253223/71663086-c875f100-2d8e-11ea-8bc4-0c26d38d956e.png)

**Comment by treadpit** [comment]
周视图模式下的滑动就是按周来滑动的，不太清楚你的这个具体是指什么。

**Comment by DuyinLoo88** [comment]
![image](https://user-images.githubusercontent.com/32253223/71666874-bfd8e700-2d9d-11ea-9ebd-2f579872a3f4.png)
你好，我想要的效果是高度只有一周这样，然后左右滑动。现在是一个月都在显示，

**Comment by DuyinLoo88** [comment]
> 周视图模式下的滑动就是按周来滑动的，不太清楚你的这个具体是指什么。

![image](https://user-images.githubusercontent.com/32253223/71667036-573e3a00-2d9e-11ea-9abe-41381075e280.png)
你好，我想要的效果是高度只有一周这样，然后左右滑动。现在是一个月都在显示，

**Comment by DuyinLoo88** [comment]
> 周视图模式下的滑动就是按周来滑动的，不太清楚你的这个具体是指什么。

能实现吗

**Comment by treadpit** [comment]
> > 周视图模式下的滑动就是按周来滑动的，不太清楚你的这个具体是指什么。
> 
> 能实现吗

那就是周视图吧，可以调用方法切换为周视图就只会展示单周的日期

**Comment by DuyinLoo88** [comment]
> > > 周视图模式下的滑动就是按周来滑动的，不太清楚你的这个具体是指什么。
> > 
> > 
> > 能实现吗
> 
> 那就是周视图吧，可以调用方法切换为周视图就只会展示单周的日期

你好，不知道你那里有没有这个问题，选中的日期没有背景色了，我选的是3号
![image](https://user-images.githubusercontent.com/32253223/71668999-2eba3e00-2da6-11ea-91a9-9434e4bca04b.png)

**Comment by treadpit** [comment]
文档有说明，你这样配置会全面接管点击事件，不会触发选中逻辑
