### ISSUE TITLE
multi 模式能否设置默认选中几天或者清除被选中的那几天数据呢

### ISSUE THREAD

**Issue by LR-account** [treadpit/wx_calendar#250]
![image](https://user-images.githubusercontent.com/43976681/71971866-79283880-3246-11ea-86c6-4c7737d9001a.png)
点击下月需要清空选中的数据

**Comment by LR-account** [comment]
第一次提问不知道咋整抱歉(⊙﹏⊙)

**Comment by treadpit** [comment]
设置选中多个日期参考方法：[setSelectedDays](https://treadpit.github.io/wx_calendar/?id=_12-%E8%AE%BE%E7%BD%AE%E9%80%89%E4%B8%AD%E5%A4%9A%E4%B8%AA%E6%97%A5%E6%9C%9F)

```js
const toSet = [
  {
    year: '2019',
    month: '3',
    day: '15'
  },
  {
    year: 2019,
    month: 3,
    day: 18
  }
];
this.calendar.setSelectedDays(toSet);
```
