### ISSUE TITLE
Uncaught (in promise) TypeError: (0 , o.default)(...).buildDate is not a function

### ISSUE THREAD

**Issue by janrone** [treadpit/wx_calendar#255]
**BUG描述**

Uncaught (in promise) TypeError: (0 , o.default)(...).buildDate is not a function

**复现步骤**

afterCalendarRender(e) {
    console.log('afterCalendarRender', e);
    this.calendar.switchView('week').then(() => { });
  },
**期望结果**

切换周视图 
**实际结果**

**截图**

**Comment by treadpit** [comment]
已修复，请同步 `master` 代码

**Comment by janrone** [comment]
> 已修复，请同步 `master` 代码

多谢，已经同步 。
