### ISSUE TITLE
周模式左右切换时间混乱呀。。。

### ISSUE THREAD

**Issue by janrone** [treadpit/wx_calendar#257]
**BUG描述**
周模式下左右切换日历显示混乱。
**复现步骤**

**期望结果**

**实际结果**

**截图**

**Comment by treadpit** [comment]
滑动手势判断逻辑错误，已修复

**Comment by janrone** [comment]
> 滑动手势判断逻辑错误，已修复

1.2k的start   太经不起考验了 😄
