### ISSUE TITLE
enableArea 和 disablePastDay 搭配bug

### ISSUE THREAD

**Issue by xiaodong86** [treadpit/wx_calendar#258]
**BUG描述**
enableArea 和 disablePastDay:true 搭配 出现可以选择之前的时间
**复现步骤**
初始化  calendarConfig  disablePastDay: true 表示不选择今天之前时间
afterCalendarRender中设置  this.calendar.enableArea(['2020-01-13', '2020-01-16']); 表示可选时间为2020-01-13 到 2020-01-16; 今天为2020-01-15;
**期望结果**
只能选择 今天之后的(2020-01-15 ~ 2020-01-16)
**实际结果**
初次进入为(2020-01-13 ~ 2020-01-16) , 然后选择下一个月 在选择上一个月 (返回到本月)后;
时间才固定为(2020-01-15 ~ 2020-01-16)
**截图**
初始化页面
![1579059182](https://user-images.githubusercontent.com/51738920/72402692-e0844200-378a-11ea-8f8c-91d9156f1a36.png)
点击下个月再返回当月后
![image](https://user-images.githubusercontent.com/51738920/72402717-f265e500-378a-11ea-9153-c5c74e3b83a5.png)

**Comment by treadpit** [comment]
这里涉及一个优先级的问题，可能是初始化的时候没有处理到这种情况，我抽时间看看，谢谢
