### ISSUE TITLE
setDateStyle 无效

### ISSUE THREAD

**Issue by zhongshankaka** [treadpit/wx_calendar#266]
**BUG描述**
调用 this.calendar.setDateStyle 没有效果，在调用的时候已经能拿到this.calendar 实例了，参数也有传，但是 dom 没有插入class
**复现步骤**

**期望结果**
dom 上插入设置的 class
**实际结果**
dom 上还是只有默认的class
**截图**
调用this.calendar.setDateStyle前打印设置21号样式：
![1582180622645](https://user-images.githubusercontent.com/17596583/74907581-9ed06200-53ee-11ea-80c5-19ae0409ead5.jpg)

dom: 
![image](https://user-images.githubusercontent.com/17596583/74907729-e7881b00-53ee-11ea-9497-a1b9ac191822.png)

**Comment by treadpit** [comment]
测试了下没有复现，能否提供最小 Demo 供排查

![image](https://user-images.githubusercontent.com/10692855/74995372-ab56c800-548b-11ea-994e-4707325c2027.png)

**Comment by zhongshankaka** [comment]
> 测试了下没有复现，能否提供最小 Demo 供排查
> 
> ![image](https://user-images.githubusercontent.com/10692855/74995372-ab56c800-548b-11ea-994e-4707325c2027.png)



> 测试了下没有复现，能否提供最小 Demo 供排查
> 
> ![image](https://user-images.githubusercontent.com/10692855/74995372-ab56c800-548b-11ea-994e-4707325c2027.png)

我发现是因为在企业微信开发模式下会有问题，切到小程序模式下就好了，是否和基础库有关系？

**Comment by zhongshankaka** [comment]
> 测试了下没有复现，能否提供最小 Demo 供排查
> 
> ![image](https://user-images.githubusercontent.com/10692855/74995372-ab56c800-548b-11ea-994e-4707325c2027.png)

我发现是因为在企业微信开发模式下会有问题，切到小程序模式下就好了，是否和基础库有关系？

**Comment by treadpit** [comment]
这个不太清楚呢，因为没有企业微信开发模式的测试环境，不太好去 debug。企业微信下的所有基础库都有问题么？
