### ISSUE TITLE
设置多个日期下的待办事项，怎么可以让不同日期圆点标记显示不同的颜色

### ISSUE THREAD

**Issue by wangrihui** [treadpit/wx_calendar#270]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**Comment by treadpit** [comment]
参考：https://github.com/treadpit/wx_calendar/pull/254

**Comment by wangrihui** [comment]
afterCalendarRender在这方法里面调用了 that.calendar.setTodoLabels 设置不同日期显示不同颜色，生效，但是切换到下一个月 颜色又都重置成默认的了？这个怎么解决

**Comment by treadpit** [comment]
> afterCalendarRender在这方法里面调用了 that.calendar.setTodoLabels 设置不同日期显示不同颜色，生效，但是切换到下一个月 颜色又都重置成默认的了？这个怎么解决

设置日期的是当月的还是也包含了下一个月的？

```js
    this.calendar.setTodoLabels({
      days: [
        { year: 2020, month: 2, day: 9, todoLabelColor: 'red' },
        { year: 2020, month: 2, day: 23, todoLabelColor: 'blue' },
        { year: 2020, month: 3, day: 23, todoLabelColor: 'blue' }
      ]
    });
```

**Comment by wangrihui** [comment]
> > afterCalendarRender在这方法里面调用了 that.calendar.setTodoLabels 设置不同日期显示不同颜色，生效，但是切换到下一个月 颜色又都重置成默认的了？这个怎么解决
> 
> 设置日期的是当月的还是也包含了下一个月的？
> 
> ```js
>     this.calendar.setTodoLabels({
>       days: [
>         { year: 2020, month: 2, day: 9, todoLabelColor: 'red' },
>         { year: 2020, month: 2, day: 23, todoLabelColor: 'blue' },
>         { year: 2020, month: 3, day: 23, todoLabelColor: 'blue' }
>       ]
>     });
> ```

包含下个月的 ，但是我左右滑动后，颜色就全部都初始成默认的了

**Comment by treadpit** [comment]
我使用的是上面的代码测试，滑动后没有出现颜色重置的问题，能提供最小复现 demo 不？
？
![Kapture 2020-02-28 at 15 29 27](https://user-images.githubusercontent.com/10692855/75519899-47aa3d00-5a3f-11ea-9f27-356226efb014.gif)
