### ISSUE TITLE
两个页面两个日历组件的周视图和月视图切换问题

### ISSUE THREAD

**Issue by liser1426** [treadpit/wx_calendar#271]
**BUG描述**小程序的两个页面中分别有一个日历组件，当从页面一跳转到页面二，在返回到页面一时，页面一中的日历切换周视图和月视图效果无效，that.calendar.switchView('month').then(() => {
          console.log('我进来了') });
该方法还可以调用，希望您能帮忙找找问题，两个日历我用了不同的ID，还是无法处理该问题

**复现步骤**

**期望结果**

**实际结果**

**截图**

**Comment by liser1426** [comment]
图片

**Comment by liser1426** [comment]
![1582716264780](https://user-images.githubusercontent.com/43568975/75342393-507d0080-58d1-11ea-898f-f73dcdd23f06.jpg)

**Comment by liser1426** [comment]
![1582716297827](https://user-images.githubusercontent.com/43568975/75342417-5d99ef80-58d1-11ea-909a-497ed11ad1bb.jpg)

**Comment by liser1426** [comment]
![1582717033894](https://user-images.githubusercontent.com/43568975/75342529-920dab80-58d1-11ea-85bf-09036e142c19.jpg)
![1582717009523](https://user-images.githubusercontent.com/43568975/75342549-9934b980-58d1-11ea-9151-71f487a8f8d8.jpg)

**Comment by treadpit** [comment]
这样使用确实可能存在问题，我排查下

**Comment by liser1426** [comment]
ok,谢谢了

**Comment by treadpit** [comment]
因设计问题调整较大，目前可尝试传入日历组件ID。

```xml
页面A:

<calendar id="c1"  calendarConfig="{{calendarConfig1}}" ></calendar>
```
```xml
页面B:

<calendar id="c2"  calendarConfig="{{calendarConfig2}}" ></calendar>
```
***在调用方法时传对应日历指定 ID***

```js
this.calendar.switchView('week', '#c1').then(() => {})

this.calendar.switchView('', '#c2').then(() => {})
```

**Comment by liser1426** [comment]
好的，我试试

在 2020-02-29 11:05:36，imfu <notifications@github.com> 写道：


因设计问题调整较大，目前可尝试传入日历组件ID。

页面A:



<calendarid="c1"calendarConfig="{{calendarConfig1}}" ></calendar>
页面B:



<calendarid="c2"calendarConfig="{{calendarConfig2}}" ></calendar>

在调用方法时传对应日历指定 ID

this.calendar.switchView('week', '#c1').then(() => {})



this.calendar.switchView('', '#c2').then(() => {})

**Comment by liser1426** [comment]
测试后发现可以解决问题，谢谢



在 2020-02-29 11:05:36，"imfu" <notifications@github.com> 写道：

因设计问题调整较大，目前可尝试传入日历组件ID。

页面A:



<calendarid="c1"calendarConfig="{{calendarConfig1}}" ></calendar>
页面B:



<calendarid="c2"calendarConfig="{{calendarConfig2}}" ></calendar>

在调用方法时传对应日历指定 ID

this.calendar.switchView('week', '#c1').then(() => {})



this.calendar.switchView('', '#c2').then(() => {})
