### ISSUE TITLE
期望周视图下能提供只显示本月本周的日期

### ISSUE THREAD

**Issue by Zohnson** [treadpit/wx_calendar#272]
**功能建议**
你好，期望周视图下能提供只显示本月本周的日期，
比如，周日周一为上个月的30号和31号，不在当前页面显示

**需求背景**
周视图下，每次日历滑动时，只显示本月某一周的日期
![周视图](https://user-images.githubusercontent.com/19889662/75610492-811c9e80-5b4c-11ea-8999-a427307221a6.png)

**Comment by treadpit** [comment]
这种情况比较特殊，如果那一周只有一天，这个显示效果就太差了，暂不支持哈，可以在 `week.js` 内设置页面数据前自行扩展一下。

**Comment by Zohnson** [comment]
好的， 已经跟产品沟通需求， 感谢你的插件分享




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "imfu"<notifications@github.com&gt;; 
发送时间: 2020年3月2日(星期一) 上午10:42
收件人: "treadpit/wx_calendar"<wx_calendar@noreply.github.com&gt;; 
抄送: "朱镇盛"<369728544@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [treadpit/wx_calendar] 期望周视图下能提供只显示本月本周的日期 (#272)




这种情况比较特殊，如果那一周只有一天，这个显示效果就太差了，暂不支持哈，可以在 week.js 内设置页面数据前自行扩展一下。

**Comment by treadpit** [comment]
好的，感谢支持。
