### ISSUE TITLE
请教一下，是否可以直接设置展示一整年的日历，还是需要遍历12个月份

### ISSUE THREAD

**Issue by Zohnson** [treadpit/wx_calendar#274]
**问题描述**
请教一下，是否可以直接设置展示一整年的日历，还是需要遍历12个月份，麻烦了~
![image](https://user-images.githubusercontent.com/19889662/75749634-33c34b80-5d5d-11ea-8222-e736dabd9e17.png)

**Comment by treadpit** [comment]
不支持
