### ISSUE TITLE
请问选择起始日期和结束日期中间能不能用颜色全部标识中间日期，取消后能不能把禁止日期去掉

### ISSUE THREAD

**Issue by wyying** [treadpit/wx_calendar#278]
**问题描述**
1.选择起止日期和结束日期之后，再次选择只能选择两个日期中间的，不能选两个日期之外的日期，
2.两个起止日期选择之后能否让两个之间的日期用特殊的颜色或者样式标识

**Comment by treadpit** [comment]
![Kapture 2020-03-07 at 9 44 48](https://user-images.githubusercontent.com/10692855/76134363-99af1c00-6058-11ea-8af5-3a8a29d864a1.gif)

**Comment by wyying** [comment]
你好，是这种效果的，能告知实现的demo吗

**Comment by treadpit** [comment]
这个就只是个配置项 [参考文档](https://treadpit.github.io/wx_calendar/?id=_3-%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE)

```js
calendarConfig: {
  showLunar: true,
  chooseAreaMode: true, // 开启日期范围选择模式，该模式下只可选择时间段
  ......
}
```

**Comment by wyying** [comment]
calendarConfig: {
      showLunar: true,
      multi: true,
      disablePastDay: true,
      weekTap: true,
      quantum: true,
      chooseAreaMode: true,
![share](https://user-images.githubusercontent.com/15809193/76179962-87b7af80-61f7-11ea-99d4-69590d2d08b9.gif)

    },

**Comment by treadpit** [comment]
日期区域选择模式需要关闭 `multi`
