### ISSUE TITLE
周视图下，跳转指定的日期，onSwipe获取数据年份不正确问题

### ISSUE THREAD

**Issue by Zohnson** [treadpit/wx_calendar#281]
**BUG描述**
在周视图下， 跳转到指定的日期后，滑动面板，面板周末颜色不对，还有就会获取的面板日期数据不正确(年份)
**复现步骤**
在周视图下， 跳转到指定的日期后，滑动面板，面板周末颜色不对，还有就会获取的面板日期数据不正确(年份)
**期望结果**

**实际结果**

**截图**
          bind:onTapDay="onTapDay_month"
![image](https://user-images.githubusercontent.com/19889662/76176445-ab74f880-61eb-11ea-9ad5-3410a459d6b3.png)

**Comment by treadpit** [comment]
能否提供更多的信息，或者最小复现demo。

![image](https://user-images.githubusercontent.com/10692855/76178129-5a680300-61f1-11ea-897d-79fbb61526a7.png)
