### ISSUE TITLE
如何能够不选中好几个日期

### ISSUE THREAD

**Issue by cc77hhh** [treadpit/wx_calendar#282]
（刚开始学，有点小白）
怎么才能点到哪个日期，就切换到哪个日期变颜色，而不是很多选中的都变颜色呢？而且我发现在切换到其它日期的时候那个上面的日期会变也不知道怎么回事

![issue1](https://user-images.githubusercontent.com/59923735/76313467-f1c37800-630f-11ea-9d55-98a18eabf3b0.png)

**Comment by treadpit** [comment]
仔细看下文档，里面有关于选择模式配置的

**Comment by cc77hhh** [comment]
> 仔细看下文档，里面有关于选择模式配置的

哦哦好的，谢谢啦
