### ISSUE TITLE
在ipad air上面3月份日期仅显示六天的第七天没有显示

### ISSUE THREAD

**Issue by yzphp** [treadpit/wx_calendar#283]
在ipad air上面3月份日期仅显示六天的第七天没有显示

**Comment by yzphp** [comment]
![图片](https://user-images.githubusercontent.com/25123188/76484449-c4341700-6454-11ea-8649-937d8502b61c.png)

**Comment by treadpit** [comment]
能否贴一下配置或最小复现demo？

在模拟器ipad下测试OK

![image](https://user-images.githubusercontent.com/10692855/76516297-22351e80-6496-11ea-96ff-9ce4e1f722b2.png)

**Comment by yzphp** [comment]
模拟器测试也是ok的，正式运行上 ipad air是只显示6天  另外说明就是目前只看到3月份只显示6天。

**Comment by treadpit** [comment]
#310
