### ISSUE TITLE
日期范围选择后不跳转以及显示bug

### ISSUE THREAD

**Issue by xichunjie** [treadpit/wx_calendar#284]
**BUG描述**
日期范围选择后不跳转以及其他月份也被选中
**复现步骤**
譬如现在在2020年3月的页面，然后我设置this.calendar.chooseDateArea(['2020-01-07', '2020-01-19'])，设置后页面不会跳转到1月份，这时将页面往前翻，到2月份时发现2月份日期全部选中，继续往前翻，翻到1月份时显示正常，这时再往后翻，翻到2月份，2月份日期也显示正常，没被选择
**期望结果**
希望范围选择时能跳转到开始日期的年月
**实际结果**
如复现步骤中显示异常
**截图**
![QQ截图20200312143859](https://user-images.githubusercontent.com/19978806/76494196-51846500-646f-11ea-964e-fa976df74593.png)
![QQ截图20200312143911](https://user-images.githubusercontent.com/19978806/76494198-534e2880-646f-11ea-97fe-f52dbfa84793.png)

**Comment by treadpit** [comment]
范围选择时自动跳转到开始日期的年月，这个属于业务需求，根据实际情况自行处理（jump）

**Comment by xichunjie** [comment]
嗯嗯，我现在是先jump到范围选择的开始时间，然后再范围选择，就没上面的显示问题了

**Comment by treadpit** [comment]
不跳转情况下的显示问题也已修复，需同步 `master` 代码
