### ISSUE TITLE
How to integrate with kbone

### ISSUE THREAD

**Issue by zairl23** [treadpit/wx_calendar#288]
I just add the wx_calendar component into a project base on kbone, it's work fine,  the ui  render properly, but i can't use the `this.calendar` in a vue component like in a normal miniprogram's Page. So how can i inject the calendar instance in a vue component?

**Comment by treadpit** [comment]
`this` means the instance of current page in miniprogram. so if you what use `this.calendar`, you must ensure `this` points to miniprogram's Page.

**Comment by zairl23** [comment]
Well, thank you! I have  injected the calendar instance into a vue component following below, although it's a little hackable.

In the vue component:

```js
      ...
      data() {
            return {
                 calendar: {},
            }
      },
      ....
      
      afterCalendarRender(e) {
          this.calendar = this.getCurrentPage().calendar
          // Now it works!
           const ym = this.calendar.getCurrentYM()
     },
      // Get the current  miniprogram's Page instance
     getCurrentPage() {
          const pages = getCurrentPages();
          const last = pages.length - 1;
          return pages[last];
     }
```

**Comment by treadpit** [comment]
yes, all methods of plugin are mounted  on the Page, just make sure that `this` points to the page.

**Comment by zairl23** [comment]
@treadpit , Thank you, i think the problem has been solved, thank for your greate job again!
