### ISSUE TITLE
为什么我在 自定义组件里面 调用 这个 组件 无法调方法

### ISSUE THREAD

**Issue by bybeep** [treadpit/wx_calendar#289]
(0 , _index.setTodoLabels) is not a function; [Component] Event Handler Error @ pages/work/work#ctrl_click
TypeError: (0 , _index.setTodoLabels) is not a function

**Comment by bybeep** [comment]
afterCalendarRender {type: "afterCalendarRender", timeStamp: 12087, target: {…}, currentTarget: {…}, mark: {…}, …}
work.js? [sm]:1758 渲染完毕

已经显示渲染完毕了 
之后调用的方法

**Comment by bybeep** [comment]
是不是因为  我在自定义组件里面   调用的这个 组件   的原因

**Comment by a1252822413** [comment]
我也遇到了这个问题，在组件中调用这个插件，就获取不到this.calendar

**Comment by IvanNguyen** [comment]
Hi @treadpit ,
I'm using this wx_calendar plugin with Taro and i don't know how to get `this.calendar`
Thank you in advance :(

**Comment by treadpit** [comment]
@bybeep @a1252822413 

![image](https://user-images.githubusercontent.com/10692855/77400883-d9ab2880-6de6-11ea-8608-d6cfff60ce75.png)

**Comment by treadpit** [comment]
`this` means the instance of current page. first, you need to get the instance of current page

 or you can import the methods, like this:

```js
import { jump } from '../../component/calendar/main.js';
```

**Comment by qmc2017** [comment]
我的问题是，我获取到了calendar，但是仍然报calendar.enableArea is not a function

**Comment by IvanNguyen** [comment]
> @IvanNguyen
> 
> `this` means the instance of current page. first, you need to get the instance of current page
> 
> or you can import the methods, like this:
> 
> ```js
> import { jump } from '../../component/calendar/main.js';
> ```

Hi @treadpit , i tried your way, but it does not work !
I found this way, all methods of plugin are inside `this.$scope`
That means you guys have to call `this.$scope.calendar`

**Comment by treadpit** [comment]
`this` means the instance of page in miniprogram, all methods of plugin are mounted on the page.

`this.$scope` means an instance of component in `Taro`, and a page is a concrete implementation of a component in Taro, so u can use `this.$scope.calendar`.

**Comment by yizuochengchi** [comment]
我有一个好主意 data中设置一下 通过 this.data.calendar 调用方法就可以  哇咔咔！

**Comment by wuxinwei240** [comment]
> 通过
在taro 上获取小程序实例
/**
   * 日历初次渲染完成后触发事件，如设置事件标记
   */
  afterCalendarRender = (e) => {
    const pageList = Taro.getCurrentPages();
    const calendar = pageList[pageList.length - 1].calendar;
    this.setState({calendar});
  }

**Comment by wuxinwei240** [comment]
微信小程序官方有获取当前页面实例的方法，可以通过实例找到calendar对象
/**
   * 日历初次渲染完成后触发事件，如设置事件标记
   */
  afterCalendarRender = (e) => {
    const pageList = Taro.getCurrentPages();
    const calendar = pageList[pageList.length - 1].calendar;
    this.setState({calendar});
  }

**Comment by yangjie21** [comment]
afterCalendarRender  在 taro 里怎么调用 有代码吗

**Comment by yangger6** [comment]
> afterCalendarRender 在 taro 里怎么调用 有代码吗

用到组件的页面文件加上

```
 Taro.eventCenter.on('afterCalendarRender', (calendar) => {
      console.log(calendar)
      debugger
    })
``` 

日历组件文件夹下的`render.js`最底下加上一句`Taro.eventCenter.trigger('afterCalendarRender', rst)`

![image](https://user-images.githubusercontent.com/23329645/144739919-9d5db23f-6ab0-4d7b-bcef-288400e1c261.png)

**Comment by yangger6** [comment]
记得引入Taro

**Comment by sunWhereCode** [comment]
> afterCalendarRender 在 taro 里怎么调用 有代码吗

taro-vue3可以用吗
