### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by MusicGo** [treadpit/wx_calendar#29]
指定日期待办事项标记：日期不在本地写死，而是从接口获取的情况下，点击待办事项后，标记点会消失

**Comment by treadpit** [comment]
@MusicGo hi，点击待办事项，该天的待办事项标记点是会隐藏的，当点击其他日期的时候会再次自动显示出来。你这里的标记点消失是指所有的待办事项标记点都消失了？

**Comment by MusicGo** [comment]
日期从后台获取的情况下，点击待办事项，该天的待办事项标记点隐藏，这个没问题，问题是当点击其他日期的时候会不会再次自动显示了

**Comment by treadpit** [comment]
我这边试了下没有问题，点击其他日期该有事件标记的会再次显示出来

![s](https://user-images.githubusercontent.com/10692855/41768930-3e049afa-7640-11e8-820b-b4b6be0aff64.gif)

**Comment by MusicGo** [comment]
days: [{
            year: 2018,
            month: 6,
            day: 12,
          }, {
            year: 2018,
            month: 6,
            day: 15,
          }]
days里边的日期数组不要这样写死，从后台获取试下就会出现我说的问题了

**Comment by MusicGo** [comment]
afterCalendarRender() {
            setTodoLabels({
              pos: 'bottom',
              dotColor: '#cc5226',
              days: res.data.content,
            });
}
这样

**Comment by treadpit** [comment]
你的接口是在哪里请求的，接口是异步的，你这样只要`res.data.content`数据格式是对的，那跟本地写死有和区别呢，唯一的区别就在于调用`setTodoLabels`的时机而已

**Comment by MusicGo** [comment]
afterCalendarRender() {
        wx.request({
          url: 'http://127.0.0.1:8080/student_json', 
          header: {
            'content-type': 'application/json'
          },
          success: function (res) {
            setTodoLabels({
              pos: 'bottom',
              dotColor: '#DC143C',
              days: res.data,
            });
          }
 })

        /*这是接口返回的数据结构（res.data）
[{
year: "2018",
month: "6",
day: "15",
}]
*/
      },
    });

**Comment by MusicGo** [comment]
2539172542方便加下

**Comment by treadpit** [comment]
类型要求的是数字，因为你这里传入的是字符串，所以这里出现了问题，是底层处理疏忽了用户传入的类型导致，已修复。

```js
{
    year: "2018",
    month: "6",
    day: "15",
}
```

**Comment by MusicGo** [comment]
嗯，我是在点击待办项时重新渲染，也能解决这个问题，只是性能欠佳，给作者点赞。
