### ISSUE TITLE
周视图模式下，有时候月末几天后面日期都显示空白

### ISSUE THREAD

**Issue by wangrihui** [treadpit/wx_calendar#294]

**Comment by wangrihui** [comment]
我看了下 您的demo也是这样的，您可以在月视图点击 3月30号 然后 月视图转成周视图 看下 ，后面的日期都显示空白了

**Comment by wangrihui** [comment]
这个是个必出现的bug，而且我在滑动后，在返回来3月 30号变成周五了，本来应该是周一

**Comment by wangrihui** [comment]
希望您看到邮件后 能第一时间回复下 太感谢了

**Comment by wangrihui** [comment]
![微信图片_20200330194911](https://user-images.githubusercontent.com/7884855/77909243-9b6aa900-72bf-11ea-9105-082cc692d596.png)

**Comment by treadpit** [comment]
你这边这个包是什么时候的代码包呢？是否为最新的呢？

![screen_shot](https://user-images.githubusercontent.com/10692855/78867741-2ee86a80-7a74-11ea-9c7e-4d8afddb492b.gif)

**Comment by wangrihui** [comment]
> 你这边这个包是什么时候的代码包呢？是否为最新的呢？
> 
> ![screen_shot](https://user-images.githubusercontent.com/10692855/78867741-2ee86a80-7a74-11ea-9c7e-4d8afddb492b.gif)

我运行您的demo是最新下载的 就是这个问题， 我项目中的代码包还是之前的办版本

**Comment by treadpit** [comment]
demo 中就是上面那个 gif 运行的情况呢，点击3.30号之后，切换为周视图后，后面几天是正常显示的呢

**Comment by wangrihui** [comment]
> demo 中就是上面那个 gif 运行的情况呢，点击3.30号之后，切换为周视图后，后面几天是正常显示的呢
刚才下载最新的试了下 问题修复了，以前版本确实存在这个问题，谢谢 辛苦了

**Comment by treadpit** [comment]
好的
