### ISSUE TITLE
能不能设置两个代办事项内容？  因为有个需求是要把节令加上。 现在只能添加一个代办标记

### ISSUE THREAD

**Issue by xujiacheng333** [treadpit/wx_calendar#295]
**功能建议**
你期望提供或修改什么功能

**需求背景**
描述是什么场景下需要支持该功能

**Comment by wangrihui** [comment]
一直都支持多个待办标记啊  this.calendar.setTodoLabels({
  // 待办点标记设置
  pos: 'bottom', // 待办点标记位置 ['top', 'bottom']
  dotColor: '#40', // 待办点标记颜色
  circle: true, // 待办圆圈标记设置（如圆圈标记已签到日期），该设置与点标记设置互斥
  showLabelAlways: true, // 点击时是否显示待办事项（圆点/文字），在 circle 为 true 及当日历配置 showLunar 为 true 时，此配置失效
  days: [
    {
      year: 2018,
      month: 1,
      day: 1,
      todoText: '待办'
    },
    {
      year: 2018,
      month: 5,
      day: 15
    }
  ]
});

**Comment by xujiacheng333** [comment]
我这边做的是一个旅游行程选择，有节日的同时需要显示每天的价格，所以希望一个日期上有两个代办标记

**Comment by treadpit** [comment]
> 我这边做的是一个旅游行程选择，有节日的同时需要显示每天的价格，所以希望一个日期上有两个代办标记

显示节日又显示每天的价格，设计上是如何处理的，感觉有点拥挤

**Comment by heroofchina** [comment]
> > 我这边做的是一个旅游行程选择，有节日的同时需要显示每天的价格，所以希望一个日期上有两个代办标记
> 
> 显示节日又显示每天的价格，设计上是如何处理的，感觉有点拥挤

他说的这种 其实不需要你来进行修改 你把目前的，日历渲染模版那块（wxml）结构写的清楚一些可以让他自己自定义就行了，我之前遇见过这种要求，我把日历渲染模版那块（渲染单个日期和待办哪里），的align-items，justify-content都去掉了 ，让day的按照瀑布的方式进行排版，day上面特殊的部分自己用定位。
