### ISSUE TITLE
this.calendar 报错

### ISSUE THREAD

**Issue by Loonging** [treadpit/wx_calendar#296]
console.log(this.calendar) 时 undefined    ？？？？？？？？？

**Comment by LxL-Loong** [comment]
console.log(this)中有calendar 实例

**Comment by LxL-Loong** [comment]
Unhandled promise rejection TypeError: Cannot read property 'enableDays' of undefined

**Comment by treadpit** [comment]
执行上下文中的 `this` 是指向哪里的
