### ISSUE TITLE
做成template 是不是更实用呢

### ISSUE THREAD

**Issue by KissWorld** [treadpit/wx_calendar#3]
做成template 是不是更实用呢

**Comment by treadpit** [comment]
@KissWorld 是的，这个demo因为比较早了，只是个例子，作为template确实更方便集成到项目里

**Comment by treadpit** [comment]
@KissWorld  已增加日历模板 [见 release/v1.1.0](https://github.com/treadpit/wx_calendar/releases/tag/v1.1.0)，可通过模板引入，初始化方法见 README
