### ISSUE TITLE
建议增加一个禁止当天之前或者之后的日期禁止选中

### ISSUE THREAD

**Issue by yzphp** [treadpit/wx_calendar#300]
作者增加了disableMode配置选项非常好，只是date需要设定具体的日期。在具体项目中常常用到禁止今天之前或者之后的日期禁选，仅仅提下建议，仅供作者参考！

**Comment by treadpit** [comment]
这个之前做的时候有考虑， `date` 为空时则默认当天，稍后我提交一个版本
