### ISSUE TITLE
设置待办日期为今天(或者是当前选中日期)todoText内容不显示

### ISSUE THREAD

**Issue by heroofchina** [treadpit/wx_calendar#301]
我也遇见这个问题，比如
1.我设置了今天有一个待办事件
2.但是默认会不显示待办事件的todoText
3.当点击了其他日期才会出现原先设置日期下的todoText
和#158的描述本质上一样的，您说描述的解决办法我拉取了代码，运行以后还是一样的。

**Comment by treadpit** [comment]
是指默认当天选中的情况下设置的 `todoText` 不显示？设置的代办的时机是什么时候，是否为日历渲染完成后？

![image](https://user-images.githubusercontent.com/10692855/79106345-e64aed00-7da4-11ea-85e0-dc09080d4cc3.png)

**Comment by heroofchina** [comment]
> 是指默认当天选中的情况下设置的 `todoText` 不显示？设置的代办的时机是什么时候，是否为日历渲染完成后？
> 
> ![image](https://user-images.githubusercontent.com/10692855/79106345-e64aed00-7da4-11ea-85e0-dc09080d4cc3.png)

1.对的 默认选当天为待办的时候，todotext不显示。

**Comment by heroofchina** [comment]
当前描述的问题是最新master版存在的。
我目前本地使用的版本是去年4月份的wx_calendar的版本，也同样有这样的问题，但是去年4月份这个版本的问题我目前已经在本地进行了修复。

**Comment by fang635295364** [comment]
所以这个问题解决了么? 我也出现了 今日待办没有出现 必须再点击才可以显示

**Comment by treadpit** [comment]
测试了下默认当天，设置 `TODO` ，下方是有显示代办标记的呢

![image](https://user-images.githubusercontent.com/10692855/80302829-06d06980-87df-11ea-8190-683f35e2b0d0.png)

**Comment by copysunday** [comment]
> 当前描述的问题是最新master版存在的。
> 我目前本地使用的版本是去年4月份的wx_calendar的版本，也同样有这样的问题，但是去年4月份这个版本的问题我目前已经在本地进行了修复。

我也遇到这个问题，有修复版本吗？

**Comment by treadpit** [comment]
> > 当前描述的问题是最新master版存在的。
> > 我目前本地使用的版本是去年4月份的wx_calendar的版本，也同样有这样的问题，但是去年4月份这个版本的问题我目前已经在本地进行了修复。
> 
> 我也遇到这个问题，有修复版本吗？

日历配置和设置代办的内容能贴一下不，能否发给个最小复现demo呢？

**Comment by JiangHaiYang01** [comment]
> 我也遇见这个问题，比如
> 1.我设置了今天有一个待办事件
> 2.但是默认会不显示待办事件的todoText
> 3.当点击了其他日期才会出现原先设置日期下的todoText
> 和#158的描述本质上一样的，您说描述的解决办法我拉取了代码，运行以后还是一样的。

![image](https://user-images.githubusercontent.com/24311760/104899018-49615400-59b5-11eb-8c71-b0ad8534f455.png)

**Comment by JiangHaiYang01** [comment]
> 我也遇见这个问题，比如
> 1.我设置了今天有一个待办事件
> 2.但是默认会不显示待办事件的todoText
> 3.当点击了其他日期才会出现原先设置日期下的todoText
> 和#158的描述本质上一样的，您说描述的解决办法我拉取了代码，运行以后还是一样的。

试一下 修改这边可以

**Comment by treadpit** [comment]
> > 我也遇见这个问题，比如
> > 1.我设置了今天有一个待办事件
> > 2.但是默认会不显示待办事件的todoText
> > 3.当点击了其他日期才会出现原先设置日期下的todoText
> > 和#158的描述本质上一样的，您说描述的解决办法我拉取了代码，运行以后还是一样的。
> 
> 试一下 修改这边可以

能贴一下是怎么使用的么，我使用的是如下配置，设置当天代办事项：

```js
// config
calendarConfig: {
      theme: 'elegant'
},

// set todo
afterCalendarRender(e) {
    const calendar = this.selectComponent('#calendar').calendar
    calendar.setTodos({
      pos: 'bottom',
      dotColor: 'orange',
      showLabelAlways: true,
      dates: [
        {
          year: 2021,
          month: 1,
          date: 18,
          todoText: '待办',
          color: 'blue'
        },
      ]
   })
},
```

![image](https://user-images.githubusercontent.com/10692855/104911748-4b7fde80-59c6-11eb-8244-fe65eaf936a1.png)

**Comment by JiangHaiYang01** [comment]
> > > 我也遇见这个问题，比如
> > > 1.我设置了今天有一个待办事件
> > > 2.但是默认会不显示待办事件的todoText
> > > 3.当点击了其他日期才会出现原先设置日期下的todoText
> > > 和#158的描述本质上一样的，您说描述的解决办法我拉取了代码，运行以后还是一样的。
> > 
> > 
> > 试一下 修改这边可以
> 
> 能贴一下是怎么使用的么，我使用的是如下配置，设置当天代办事项：
> 
> ```js
> // config
> calendarConfig: {
>       theme: 'elegant'
> },
> 
> // set todo
> afterCalendarRender(e) {
>     const calendar = this.selectComponent('#calendar').calendar
>     calendar.setTodos({
>       pos: 'bottom',
>       dotColor: 'orange',
>       showLabelAlways: true,
>       dates: [
>         {
>           year: 2021,
>           month: 1,
>           date: 18,
>           todoText: '待办',
>           color: 'blue'
>         },
>       ]
>    })
> },
> ```
> 
> ![image](https://user-images.githubusercontent.com/10692855/104911748-4b7fde80-59c6-11eb-8244-fe65eaf936a1.png)

使用还是文档上的使用方式。是在其框架内部直接修改的。具体为什么要写成那样。需要作者去fix.一下。我这边直接修改源码使用的。
