### ISSUE TITLE
现在的设置代办下面的圆点只能统一颜色，能不能可以设置成自定义多个圆点，自定义每个圆点的颜色

### ISSUE THREAD

**Issue by sunning2** [treadpit/wx_calendar#303]
**功能建议**
你期望提供或修改什么功能

**需求背景**
描述是什么场景下需要支持该功能

**Comment by treadpit** [comment]
你是想表达每个日期下面可以有多个圆点且颜色可各自配置，还是单个圆点但是可以有不同的颜色。

**Comment by sunning2** [comment]
我想表达的是，每个日期下面可以有多个圆点且颜色可各自配置




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"imfu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 中午11:50
收件人:&nbsp;"treadpit/wx_calendar"<wx_calendar@noreply.github.com&gt;;
抄送:&nbsp;"夏鱼*"<2456988613@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [treadpit/wx_calendar] 现在的设置代办下面的圆点只能统一颜色，能不能可以设置成自定义多个圆点，自定义每个圆点的颜色 (#303)





 
你是想表达每个日期下面可以有多个圆点且颜色可各自配置，还是单个圆点但是可以有不同的颜色。

**Comment by treadpit** [comment]
多个圆点目前是不支持的

**Comment by yh1234561** [comment]
多个颜色可配置支持吗

**Comment by treadpit** [comment]
> 多个颜色可配置支持吗

https://github.com/treadpit/wx_calendar/pull/254
