### ISSUE TITLE
获取当前选择的日期，返回数据能否增加农历？

### ISSUE THREAD

**Issue by adyhwang** [treadpit/wx_calendar#305]
**功能建议**
calendar.getSelectedDay()，返回的数据能否增加农历？

**Comment by treadpit** [comment]
是在哪种情况下调用没有农历信息呢？

![image](https://user-images.githubusercontent.com/10692855/79740375-27f20f80-8332-11ea-8267-1f6ae6a8956c.png)

**Comment by adyhwang** [comment]
afterTapDay内调用calendar.getSelectedDay()，返回 lunar为null

**Comment by adyhwang** [comment]
我找到原因了，如果showLunar设置为false，调用getSelectedDay()时，lunar返回null。。。希望能优化一下。

**Comment by treadpit** [comment]
```js
const options = {
  lunar: true // 在配置showLunar为false, 但需返回农历信息时使用该选项
}
const selectedDay = this.calendar.getSelectedDay(options);
console.log(selectedDay);
```
