### ISSUE TITLE
周视图下左右滑动切换切换一周数据，可以吗？

### ISSUE THREAD

**Issue by lishaoh** [treadpit/wx_calendar#31]

**Comment by lishaoh** [comment]
有这个需求，类似钉钉日历那种，周视图也能左右滑动

**Comment by treadpit** [comment]
这个可以考虑后续加入

**Comment by lishaoh** [comment]
我 try again

**Comment by treadpit** [comment]
OK，加油👍。如果写好了，可以提个MR不？😆

**Comment by lishaoh** [comment]
老哥，看看这个代码

`js


  calendarTouchmove(e) {
        if (isLeftSlide.call(this, e)) {
            if (this.weekMode) {

                const { days, curYear, curMonth } = this.data.calendar;
                const maxDays = conf.getThisMonthDays(curYear, curMonth);
                let newYear = curYear,
                    newMonth = curMonth;
                const lastDay = days[days.length - 1].day;
                if (lastDay + 7 > maxDays) {
                    if (newMonth > 11) {
                        newYear = newYear + 1;
                        newMonth = 1;
                    } else {
                        newMonth = newMonth + 1;
                    }

                    for (let i = lastDay; i < maxDays; i++) {
                        days.push({
                            day: i + 1,
                            choosed: false,
                            year: newYear,
                            month: newMonth
                        })
                    }

                    for (let i = 0; i < lastDay + 7 - maxDays; i++) {
                        days.push({
                            day: i + 1,
                            choosed: false,
                            year: newYear,
                            month: newMonth
                        })
                    }
                } else {
                    for (let i = 0; i < 7; i++) {
                        days.push({
                            day: lastDay + i + 1,
                            choosed: false,
                            year: newYear,
                            month: newMonth
                        })
                    }
                }
                console.log(days)
                let newDays = days.slice(days.length - 7, days.length);
                console.info('year', newYear, 'month', newMonth, 'days', newDays)
                conf.renderCalendar.call(this, newYear, newMonth, newDays[0].day);
                conf.selectedDayWeekAllDays.call(this, { year: newYear, month: newMonth, day: newDays[0].day });

                console.warn('周左滑', this.data.calendar)
            } else {
                conf.chooseNextMonth.call(this);
            }
        }
        if (isRightSlide.call(this, e)) {
            if (this.weekMode) {} else {
                conf.choosePrevMonth.call(this);
            }
        }

        if (isUpSlide.call(this, e)) {
            conf.switchWeek.call(this, 'week');
        }

        if (isDownSlide.call(this, e)) {
            conf.switchWeek.call(this, 'month');
        }
    },
`

现在每次在跨月处渲染就不对了，例如6月底-7月初，就不对了，老哥你瞅瞅

**Comment by lishaoh** [comment]
找到原因了，没写这个
 this.setData({
                    'calendar.curYear': newYear,
                    'calendar.curMonth': newMonth
                });
现在基本能用了

**Comment by lishaoh** [comment]
用conf.renderCalendar.call(this, 2018, 7, 1);渲染日历时，日历会抖动一下，过程好像是变成月视图再变成周视图了，why 楼主？

**Comment by treadpit** [comment]
真机还是模拟器呢？`renderCalendar` 里面没有处理周视图相关的呢？

ps: 另外周视图已支持左右滑动切换切换一周数据，`pull` 最新的 `master` 代码

**Comment by treadpit** [comment]
该 issue 已解决，若有其他问题另开 issue， 这个就先关掉了
