### ISSUE TITLE
afterCalendarRender 的机制问题

### ISSUE THREAD

**Issue by fang635295364** [treadpit/wx_calendar#313]
**问题描述**
具体描述使用过程中有不明白或者疑惑的地方

我使用的是这个 去遍历每个待办   但是执行完 console.log('afterCalendarRender', e);  去获取月份 获取不到 打印出来是空白 之后才能获取到月份 但是不会显示在页面上了   添加了改变月份时间去上个月 待办正常 在返回本月才能显示 

怎么样做才能一初始化完成就直接渲染本月待办

```js
afterCalendarRender(e) {
    console.log('afterCalendarRender', e);
    console.log(this.data.nowMonth)
    http.calendar({
      data: {
        userId: wx.getStorageSync('userLoginId'),
        companyId: wx.getStorageSync('userCompanyId'),
        thisUserId: this.data.thisUserId,
        'recordDate': '',
        'recordMonth': this.data.nowMonth
      },
      success: res => {
        console.log(this.data.nowMonth)
       if(res.data!==undefined){
        console.log(res)
        res.data.forEach(ele => {
          this.data.aa.push(ele)
        });
        // 遍历数组名
        var len = res.data.length;
        for (var i = 0; i < len; i++) {
          let bb = this.data.aa[i].recordDate.split("-")
          var obj = {};
          obj.year = bb[0]
          if (bb[1] < 10) {
            obj.month = bb[1].split("0")[1]
          } else {
            obj.month = bb[1]
          }
          if (bb[2] < 10) {
            obj.day = bb[2].split("0")[1]
          } else {
            obj.day = bb[2]
          }
          obj.todoLabelColor = res.data[i].recordResult
        this.data.arr.push(obj)
        }
        this.setData({
          arr: this.data.arr
        })
        console.log(this.data.arr)
        this.calendar.setTodoLabels({
          // circle: true,
          days: this.data.arr
        })
        // console.log(this.data.days)
       }
      }
    })
    console.log(this.data.nowMonth)
    this.calendar.setTodoLabels({
      days: this.data.arr
    });
    // console.log(this.data.days)

  },
```

**Comment by fang635295364** [comment]
补充下 调用whenChangeMonth(e) 这个去点击左右切换月份回来才可以正确的渲染  
所以想问下执行顺序 或者怎样可以优先获取本月时间 在执行这个   我在afterCalendarRender 中打印data中的月份打印的是空白

**Comment by chenhua19940128** [comment]
> 补充下 调用whenChangeMonth(e) 这个去点击左右切换月份回来才可以正确的渲染
> 所以想问下执行顺序 或者怎样可以优先获取本月时间 在执行这个 我在afterCalendarRender 中打印data中的月份打印的是空白

在afterCalendarRender的时候，this.data数据还没生成，无法使用onLoad中的数据，暂时没有解决

**Comment by fang635295364** [comment]
我现在想的解决办法是 跳转到这个页面的时候把年月传过来 可以获取到 但是这样会造成切换上个月的时候数据无法遍历 所以只好在whenChangeMonth(e) 的时候获取日期 在执行一次afterCalendarRender里面的循环操作 感觉这样不对 现在只有2个月可以这样写 月数多了就不能这样写了

**Comment by fang635295364** [comment]
whenChangeMonth(e){
    this.setData({
      month:e.detail.next.year+'-'+'0'+e.detail.next.month
    })
    let that = this
    http.calendar({
      data: {
        userId: wx.getStorageSync('userLoginId'),
        companyId: wx.getStorageSync('userCompanyId'),
        thisUserId:this.data.thisUserId,
        'recordDate': '',
        'recordMonth':that.data.month
      },
      success: res => {
        // console.log(res)
        res.data.forEach(ele => {
          this.data.aaa.push(ele)
        });
        // console.log(this.data.aaa)
        // 遍历数组名
        var lens = res.data.length;
        for (var i = 0; i < lens; i++) {
          let bbb = this.data.aaa[i].recordDate.split("-")
          var objj = {};
          objj.year = bbb[0]
          if (bbb[1] < 10) {
            objj.month = bbb[1].split("0")[1]
          } else {
            objj.month = bbb[1]
          }
          if (bbb[2] < 10) {
            objj.day = bbb[2].split("0")[1]
          } else {
            objj.day = bbb[2]
          }
          objj.todoLabelColor = res.data[i].recordResult
          // console.log(obj)
        this.data.arrr.push(objj)
        // console.log(this.data.arrr)
        }
        this.setData({
          arrr: that.data.arrr
        })
        this.calendar.setTodoLabels({
          // circle: true,
          days: that.data.arrr
        })
      }
    })
    this.calendar.setTodoLabels({
      days: this.data.arr
    })
  },
这样写  感觉代码无限重复 无限冗余

**Comment by treadpit** [comment]
好的，我抽时间看下

**Comment by treadpit** [comment]
> 补充下 调用whenChangeMonth(e) 这个去点击左右切换月份回来才可以正确的渲染
> 所以想问下执行顺序 或者怎样可以优先获取本月时间 在执行这个 我在afterCalendarRender 中打印data中的月份打印的是空白

***在afterCalendarRender 中打印data中的月份打印的是空白？*** 这个是怎么获取的？

```js
afterCalendarRender(e) {
    console.log('currentYM', this.calendar.getCurrentYM());
}
```

**Comment by treadpit** [comment]
> > 补充下 调用whenChangeMonth(e) 这个去点击左右切换月份回来才可以正确的渲染
> > 所以想问下执行顺序 或者怎样可以优先获取本月时间 在执行这个 我在afterCalendarRender 中打印data中的月份打印的是空白
> 
> 在afterCalendarRender的时候，this.data数据还没生成，无法使用onLoad中的数据，暂时没有解决

`afterCalendarRender` 在调用的时候依赖 `afterCalendarRender` 函数之外调用的异步请求的数据，可参考使用订阅的方式

**Comment by chenhua19940128** [comment]
请问一下大佬说的订阅方式是指哪种

**Comment by chenhua19940128** [comment]
> > > 补充下 调用whenChangeMonth(e) 这个去点击左右切换月份回来才可以正确的渲染
> > > 所以想问下执行顺序 或者怎样可以优先获取本月时间 在执行这个 我在afterCalendarRender 中打印data中的月份打印的是空白
> > 
> > 
> > 在afterCalendarRender的时候，this.data数据还没生成，无法使用onLoad中的数据，暂时没有解决
> 
> `afterCalendarRender` 在调用的时候依赖 `afterCalendarRender` 函数之外调用的异步请求的数据，可参考使用订阅的方式

请问一下大佬说的订阅方式是指哪种

**Comment by treadpit** [comment]
> > > > 补充下 调用whenChangeMonth(e) 这个去点击左右切换月份回来才可以正确的渲染
> > > > 所以想问下执行顺序 或者怎样可以优先获取本月时间 在执行这个 我在afterCalendarRender 中打印data中的月份打印的是空白
> > > 
> > > 
> > > 在afterCalendarRender的时候，this.data数据还没生成，无法使用onLoad中的数据，暂时没有解决
> > 
> > 
> > `afterCalendarRender` 在调用的时候依赖 `afterCalendarRender` 函数之外调用的异步请求的数据，可参考使用订阅的方式
> 
> 请问一下大佬说的订阅方式是指哪种

 `EventEmitter`，在 `afterCalendarRender` 中使用 `onLoad` 中异步的数据时，先判断是否存在，存在则直接执行，不存在则先订阅，等 `onLoad` 中的数据返回时再触发相关逻辑
