### ISSUE TITLE
退出小程序再次进入首页，页面不执行afterCalendarRender事件

### ISSUE THREAD

**Issue by sunning2** [treadpit/wx_calendar#314]
**问题描述**
具体描述使用过程中有不明白或者疑惑的地方
在使用小程序时，将小程序关闭，然后打开微信在我的小程序列表中再次打开小程序，首页不执行afterCalendarRender事件

**Comment by treadpit** [comment]
这个要根据小程序来做排查，小程序是否执行了相对应生命周期

**Comment by sunning2** [comment]
问题已解决，是我自己的代码问题
