### ISSUE TITLE
日期显示可以单独设置在这个月中周六日日期的样式吗？

### ISSUE THREAD

**Issue by sunning2** [treadpit/wx_calendar#315]
**问题描述**
具体描述使用过程中有不明白或者疑惑的地方

**Comment by treadpit** [comment]
单独设置是指什么意思？每个月可以不一致？

**Comment by sunning2** [comment]
需求要求是：月当中，周六日那一行的日期的字体显示为红色，其他日期为黑色。

**Comment by treadpit** [comment]
> 需求要求是：月当中，周六日那一行的日期的字体显示为红色，其他日期为黑色。

那一行？

![image](https://user-images.githubusercontent.com/10692855/81374108-0ca84200-9131-11ea-89d2-3a4a685afe54.png)

**Comment by sunning2** [comment]
不好意思说错了，应该是周六日那一列，我看示例中，可以设置颜色，但是不知道在那里设置
![image](https://user-images.githubusercontent.com/37064838/81374357-aa9c0c80-9131-11ea-8275-b980389bc973.png)

**Comment by treadpit** [comment]
```js
calendarConfig: {
      // 日历主题，目前共两款可选择，默认 default 及 elegant，自定义主题在 theme 文件夹扩展
      theme: 'elegant'
  }
```
