### ISSUE TITLE
周视图模式下，使用this.calendar.jump()会切回月视图

### ISSUE THREAD

**Issue by zhang1024899756** [treadpit/wx_calendar#316]
**BUG描述**
周视图模式下，使用this.calendar.jump()会切回月视图
**复现步骤**
1.设置周视图模式
2.this.calendar.jump()
**期望结果**
周视图除非主动设置，否则不自动切换

**Comment by treadpit** [comment]
是否为最新的代码？使用的组件代码是什么时候的呢?

**Comment by zhang1024899756** [comment]
应该是19年11月份的组件，我试试最新的代码吧
