### ISSUE TITLE
周视图下选择月份，然后再切换周/月视图时第一次点击没效果

### ISSUE THREAD

**Issue by lishaoh** [treadpit/wx_calendar#32]

**Comment by treadpit** [comment]
你用的是我提供的那个周月视图切换么？

**Comment by treadpit** [comment]
😂 我那个提供的示例判断是有点问题哈，那个只是示范，不用管它，因为如果当前视图和下次调用的如果是一个视图，如 `month`，则会直接 `return`，所以会出现看起来没效果，需要点击两次。对使用者而言，只管调用 `switchView()` 就行，其他逻辑需要自行处理
