### ISSUE TITLE
华为手机使用中，出现最后一列没有日期直接换行

### ISSUE THREAD

**Issue by sundongrui** [treadpit/wx_calendar#321]
**BUG描述**
设置每周第一天为周一、指定范围日期可选、指定特定日期可选
在华为手机使用中，每月的周日列没有日期，到周六直接换行到下周了，日期还是连续的
**复现步骤**

**期望结果**
修复Bug
**实际结果**

**截图**
![13581589958497_ pic](https://user-images.githubusercontent.com/53344084/82416879-5be55f80-9aad-11ea-9137-fd2fc040d3b5.jpg)

**Comment by treadpit** [comment]
应该是日期格子宽度在华为手机上的计算有点兼容问题，格子放不下后换行了，手边没有华为手机，麻烦试下调整日期格子宽度样式试试呢？

**Comment by sundongrui** [comment]
改了一下父元素的宽度，解决掉了，非常感谢！

**Comment by treadpit** [comment]
好的

**Comment by anihCevol** [comment]
怎么调整，我有点懵，可以详细说一下嘛
