### ISSUE TITLE
不能切换周视图

### ISSUE THREAD

**Issue by Lyqxyz** [treadpit/wx_calendar#323]
**问题描述**
具体描述使用过程中有不明白或者疑惑的地方
当前月份未选中日期下切换为周视图，不能明确该展示哪一周的日期，故此情况不允许切换？？

**Comment by yuanbolin** [comment]
同问,月视图已经点击了日期,切换周视图提示:当前月份未选中日期下切换为周视图，不能明确该展示哪一周的日期，故此情况不允许切换？？

**Comment by treadpit** [comment]
> 同问,月视图已经点击了日期,切换周视图提示:当前月份未选中日期下切换为周视图，不能明确该展示哪一周的日期，故此情况不允许切换？？

已经选中了如果提示这个应该是个bug，能否贴下具体的操作步骤

**Comment by yuanbolin** [comment]
周视图==>月视图==>点击换个月份==>选中日子==>周视图(报错:没有选中日期,不明确切换哪个周)

**Comment by treadpit** [comment]
> 周视图==>月视图==>点击换个月份==>选中日子==>周视图(报错:没有选中日期,不明确切换哪个周)

这个步骤测试了下：

![week](https://user-images.githubusercontent.com/10692855/87867565-b8d39800-c9c0-11ea-89cf-1aad1f05c4ac.gif)
