### ISSUE TITLE
切换年月会改变样式?

### ISSUE THREAD

**Issue by AnKangZhouWei** [treadpit/wx_calendar#324]
当我对日期设置了样式，当切换年月的时候，样式会发生变化。
比如：2020-6-1 到2020-6-20日 我设置了背景色，当我切换年月再返回当前月份的时候，样式会发生改变，块状的背景色会变成圆形的背景色

>>这是我设置的样式
![1590656871(1)](https://user-images.githubusercontent.com/34094293/83122750-a5195d00-a106-11ea-99af-a634bf75966b.png)

>>这是切换年月后返回当前月

![1590656886(1)](https://user-images.githubusercontent.com/34094293/83122762-a8ace400-a106-11ea-9297-60de3c3663a9.png)

**Comment by treadpit** [comment]
文档里面有：

[日历事件使用说明](https://treadpit.github.io/wx_calendar/?id=%E6%97%A5%E5%8E%86%E4%BA%8B%E4%BB%B6%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)
![image](https://user-images.githubusercontent.com/10692855/82980741-c1d96600-a01c-11ea-9dbe-a3101b7af41c.png)

[设置待办事项](https://treadpit.github.io/wx_calendar/?id=_9-1-%E8%AE%BE%E7%BD%AE%E5%BE%85%E5%8A%9E%E4%BA%8B%E9%A1%B9)

**Comment by AnKangZhouWei** [comment]
能不能详细点啊？我想知道的是这个this.calendar哪里引入的，怎么挂载的？

**Comment by treadpit** [comment]
`this` 代指当前页面实例

```
const allPages = [...getCurrentPages()];
const currentPage = allPages.pop();

currentPage.calendar.jump()

```

**Comment by AnKangZhouWei** [comment]
我问的是这个calendar 丛哪里import
如果直接使用this.calendar.setTodoLabels会报错找不到该方法





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"imfu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月27日(星期三) 中午1:28
收件人:&nbsp;"treadpit/wx_calendar"<wx_calendar@noreply.github.com&gt;;
抄送:&nbsp;"我就笑了"<317860559@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [treadpit/wx_calendar] this.calendar (#324)





 
this 代指当前页面实例
 const allPages = [...getCurrentPages()]; const currentPage = allPages.pop(); currentPage.calendar.jump()

**Comment by AnKangZhouWei** [comment]
我知道this是当前实例 ，这个calendar是在page里面声明？
如果直接使用this.calendar.setTodoLabels 会找不到该方法

**Comment by AnKangZhouWei** [comment]
(1) 调用当前页面实例上的方法（方法均已挂载至小程序页面实例的 calendar 对象上）
这个怎么挂载的？

**Comment by treadpit** [comment]
报错按文档和其他的相关 `issue` 查下问题。

看看你的 `this` 是不是指向当前页面，如果不是，那这么调用肯就报错
