### ISSUE TITLE
切换日期会改变我设置的样式?

### ISSUE THREAD

**Issue by AnKangZhouWei** [treadpit/wx_calendar#326]
**BUG描述**
当我对日期设置了样式，当切换年月的时候，样式会发生变化。

**复现步骤**

比如我设置了一段日期的背景色，当我切换年月再返回当前月份的时候，样式会发生改变，块状的背景色会变成圆形的背景色

**期望结果**
![1590656871(1)](https://user-images.githubusercontent.com/34094293/83125301-f0813a80-a109-11ea-819c-087d453b429c.png)

**实际结果**
![1590656886(1)](https://user-images.githubusercontent.com/34094293/83125317-f37c2b00-a109-11ea-956f-84a076e0db7d.png)

**截图**

**Comment by treadpit** [comment]
怎么设置的样式？

**Comment by AnKangZhouWei** [comment]
就设置了背景色

**Comment by treadpit** [comment]
直接用 CSS 样式覆盖的？

**Comment by AnKangZhouWei** [comment]
直接使用this.calendar.setDateStyle(toSet)
