### ISSUE TITLE
非本月数据多显示了一行

### ISSUE THREAD

**Issue by TheMonsterSTAN** [treadpit/wx_calendar#333]
![image](https://user-images.githubusercontent.com/30610541/84629171-74b22b00-af1c-11ea-9b58-488ee9472f77.png)

如图,最后一行感觉是多余的,有什么方法去掉吗

**Comment by treadpit** [comment]
这个是为了保证每个月面板显示的日期一致，去掉后会出现日期有的月份5排，有的6排

**Comment by TheMonsterSTAN** [comment]
> 这个是为了保证每个月面板显示的日期一致，去掉后会出现日期有的月份5排，有的6排

我试了一下发现有些月份还是会出现5排的情况（2022-04）,是算法上有什么问题吗？
还有, 我发现就算都是6排的情况下,日历的整体高度也会发生变化,是不是本月数据和非本月数据的高度设置不一样？

**Comment by treadpit** [comment]
> 现就算都是6排的

不一样的话，可能是算有点问题
