### ISSUE TITLE
日期错乱

### ISSUE THREAD

**Issue by cxbf9306** [treadpit/wx_calendar#335]
**BUG描述**    组件在安卓机测试时出现bug，日期错乱，请看附件图片
![1592965515(1)](https://user-images.githubusercontent.com/34080641/85490808-039e0200-b605-11ea-9858-b00582860c51.jpg)

**复现步骤**

**期望结果**

**实际结果**

**截图**

**Comment by treadpit** [comment]
https://github.com/treadpit/wx_calendar/issues/321#issuecomment-631358064
