### ISSUE TITLE
默认显示周视图

### ISSUE THREAD

**Issue by yiyezhiqiu1024** [treadpit/wx_calendar#337]
请问如何配置日历默认显示周视图，可以在 calendarConfig 里面可以设置属性吗？

**Comment by helloRenie** [comment]
配置周视图的时候， weekMode: true,第二次进入的时候整个日历都不显示，是为什么呢

**Comment by treadpit** [comment]
> 配置周视图的时候， weekMode: true,第二次进入的时候整个日历都不显示，是为什么呢

已修复
