### ISSUE TITLE
有时候日历一片空白

### ISSUE THREAD

**Issue by wjp001** [treadpit/wx_calendar#338]
**BUG描述**
undefined is not an object (evaluating 'this.calendar.setTodoLabels')
settl@https://miniprogram:///pages/index/index.js:124:10
https://miniprogram:///pages/index/index.js:161:17
success@https://miniprogram:///app.js:187:24
https://lib/WASubContext.js:2:1583499
https://lib/WASubContext.js:2:111762
k@https://lib/WASubContext.js:2:453648
https://lib/WASubContext.js:2:628283
emit@https://lib/WASubContext.js:2:516578
x@https://lib/WASubContext.js:2:629245
https://lib/WASubContext.js:2:630573
https://lib/WASubContext.js:2:508916
https://lib/WAServiceMainContext.js:2:250179
_@https://lib/WAServiceMainContext.js:2:77927
1.这是微信小程序运维中心错误查询的错误
2.报错的代码：
  settl (a, b, c) {
    const days = [
      {
        year: a,
        month: b,
        day: c,
        todoText: ''
      }
    ];
    this.calendar.setTodoLabels({
      showLabelAlways: true,
      days
    });
    console.log('set todo labels: ', days);
  },
3.我需要用到农历和待办，所以开启了农历和待办
4.有时候日历一片空白，不知道是不是因为上面的错误导致的

**复现步骤**
这个还真不好复现，当小程序长时间不用，从最近使用打开有时候就是白色的，删除小程序，重新进入又好了。。。
**期望结果**
正常显示，不要有时候出现空白页面
**实际结果**
有时候出现空白页面
**截图**

![image](https://user-images.githubusercontent.com/40925476/86469838-cf48e500-bd6c-11ea-8f5b-3052c364e275.png)

**Comment by treadpit** [comment]
https://github.com/treadpit/wx_calendar/issues/337#issuecomment-658560978

**Comment by wjp001** [comment]
额，我更新到最新版本了1.5.0，上面的错误问题还没有出现，
另外当首页是日历，首页是小程序第一个页面，
用户首次进到首页，然后判断登录，跳转登录页面，
用户登录后，跳转首页，这时候日历显示空白。
我改成登录页面是小程序第一个页面。就没有这个问题了

**Comment by treadpit** [comment]
1.5.0 上是老版本的代码，master 是最新的，可同步 master代码，新的 tag 会在之后打。
