### ISSUE TITLE
您好，请问我自定义组件里面怎么获取this.calendar

### ISSUE THREAD

**Issue by Darren301510** [treadpit/wx_calendar#339]
我在自定义组件里进行了二次封装，获取不到this.calendar，求助大神

**Comment by Darren301510** [comment]
看了文档 手动引入  方式  1.5.0版本已经无main.js，我引入inde.js  但是jump()  方法未暴露

**Comment by treadpit** [comment]
`calendar` 挂在当前页面实例上的，在组件内获取页面的实例也可调用

> 1.5.0版本已经无main.js 是什么意思？查看了下 `release/1.5.0` 上有main.js文件呢？
