### ISSUE TITLE
日历单选时，afterTapDay函数返回空值

### ISSUE THREAD

**Issue by sevenPr** [treadpit/wx_calendar#34]
`
Page({
    onShow: function() {
        const conf = {
            /*multi: true, // 是否开启多选,*/
            afterTapDay: (currentSelect) => {
                console.log(currentSelect)  //  return {}
            },
        }
        initCalendar(conf); // 使用默认配置初始化日历
    }

});`

**Comment by treadpit** [comment]
感谢反馈，已修复
