### ISSUE TITLE
getSelectedDay获取的时间不是当前选中的，而是上一次选中的日期

### ISSUE THREAD

**Issue by maple3051** [treadpit/wx_calendar#342]
**BUG描述**
获取的时间不是当前选中的，而是上一次选中的日期
**复现步骤**
首先点击16号，再次点击17号
**期望结果**
首先点击16号，打印出16号，再次点击17号，显示出17号
**实际结果**
首先点击16号，打印出15号，再次点击17号，显示出16号
**截图**
![1](https://user-images.githubusercontent.com/35554377/87412389-95dd6880-c5fb-11ea-8ba3-8673d548e82d.png)
![2](https://user-images.githubusercontent.com/35554377/87412409-9970ef80-c5fb-11ea-81d4-41657110a675.png)

**Comment by treadpit** [comment]
此处文档有误。

`afterTapDay ` 是击日期后立即触发（单选且不支持反选时点击同一日期，不会执行后续逻辑，如 `setData`），`getSelectedDay` 获取的是组件 `data` 中的值。

如果需要马上获取选中的日期，可通过 `afterTapDay` 参数拿到。 

```js
 afterTapDay(currentSelect) {
    console.log('当前点击的日期', currentSelect);
  }
```
