### ISSUE TITLE
真机调试自定义事件全部消失

### ISSUE THREAD

**Issue by danderCN** [treadpit/wx_calendar#344]
在开发者工具一切正常，但是到真机调试的时候，日历组件的自定义事件属性全部消失了。
真机调试直接看渲染的页面wxml。
不知道什么原因呢。
![微信图片_20200715003322](https://user-images.githubusercontent.com/28424130/87451748-e3c19300-c632-11ea-9cc8-fc7d5018dc12.png)

**Comment by treadpit** [comment]
和该小程序组件无关
