### ISSUE TITLE
节假日提醒

### ISSUE THREAD

**Issue by burningii** [treadpit/wx_calendar#345]
可以显示节假日标识吗

**Comment by treadpit** [comment]
节假日标识需要和假日办的数据对接，目前不支持

**Comment by treadpit** [comment]
> 节假日标识需要和假日办的数据对接，目前不支持

[节假日插件 | 小历同学](https://treadpit.github.io/wx_calendar/v2/api.html#%E8%8A%82%E5%81%87%E6%97%A5)
