### ISSUE TITLE
markToday 配置不生效

### ISSUE THREAD

**Issue by Galaxy-Rigel** [treadpit/wx_calendar#346]
**BUG描述**
calendarConfig:{
        theme: 'red', // 日历主题，目前共两款可选择，默认 default 及 elegant，自定义主题在 theme 文件夹扩展
        markToday: '今', // 当天日期展示不使用默认数字，用特殊文字标记
        highlightToday: true, // 是否高亮显示当天，区别于选中样式（初始化时当天高亮并不代表已选中当天）
        onlyShowCurrentMonth: false, // 日历面板是否只显示本月日期
        hideHeadOnWeekMode: false, // 周视图模式是否隐藏日历头部
        showHandlerOnWeekMode: false, // 周视图模式是否显示日历头部操作栏，hideHeadOnWeekMode 优先级高于此配置
 }
**复现步骤**

**期望结果**

**实际结果**
  
**截图**
![image](https://user-images.githubusercontent.com/25069759/87743655-fe0a9500-c81b-11ea-8d86-bde0e1644d8f.png)

**Comment by treadpit** [comment]
使用该配置测试生效，能否提供最小复现  `demo`。

ps: 组件是什么时候引入项目的，是否有更新

![image](https://user-images.githubusercontent.com/10692855/87865469-48b91800-c9a8-11ea-844b-8338cdcd5753.png)
