### ISSUE TITLE
不能设置多选

### ISSUE THREAD

**Issue by roukuai** [treadpit/wx_calendar#348]
已经设置多选 ，但回显的时候没有起作用，用的设置设置多选日期的方法： 
const toSet = [
  {
    year: 2019,
    month: 3,
    day: '5
  },
  {
    year: 2019,
    month: 3,
    day: 18
  }
];
this.calendar.setSelectedDays(toSet);

此方法没有生效

**Comment by treadpit** [comment]
`setSelectedDays` 需要在多选模式下使用，查看是否开启了多选模式

```js
{
  multi: true
}
```

> Warn: 单选模式下不能设置多日期选中，请配置 multi

**Comment by roukuai** [comment]
calendarConfig: {
      multi: true, // 是否开启多选,
      theme: 'elegant', // 日历主题，目前共两款可选择，默认 default 及 elegant，自定义主题在 theme 文件夹扩展
      noDefault:true,//不默认选中
      firstDayOfWeek: 'Mon', // 每周第一天为周一还是周日，默认按周日开始
      disableMode: {  // 禁用某一天之前/之后的所有日期
        type: 'before',  // [‘before’, 'after']
        date: formatDate.getNowFormatDate(), // 无该属性或该属性值为假，则默认为当天
      },
    },


我设置了，我想实现的是，点击弹出日历，然后让日历回显的的时候让把选中的日期在回显一下，日历的显示用的wx-if，再次显示的时候日历又被初始化了！

**Comment by treadpit** [comment]
`wx:if` 会销毁组件重新初始化组件

**Comment by roukuai** [comment]
那怎么设置，打开日历的时候，默认选中多个日期呢？

**Comment by treadpit** [comment]
使用 show 控制组件显示隐藏试试
