### ISSUE TITLE
禁选

### ISSUE THREAD

**Issue by Ben199011** [treadpit/wx_calendar#35]
请问怎么禁选部分日期的

**Comment by treadpit** [comment]
你好，目前只是提供了禁选过去的所有日期，如果你是需要禁选指定的某些天的话，目前还是没有这个功能，但思路是一样的，如果着急可以自己扩展一下，不着急的话，下个版本我把这个功能加上

**Comment by Ben199011** [comment]
@treadpit 好的谢谢，我想问一下，你这个兼容mpvue的不，最好开发一下多选和禁选，mpvue-calendar，参考一下这个的功能，我喜欢你这个组件的样式，

**Comment by treadpit** [comment]
禁选日期功能已加，使用方式请[参考文档](http://isfeer.com/?id=_6-%E7%A6%81%E9%80%89%E6%8C%87%E5%AE%9A%E6%97%A5%E6%9C%9F)
