### ISSUE TITLE
切换周月视图时，已选中的日期会短暂闪动到另外一个日期

### ISSUE THREAD

**Issue by slimvan** [treadpit/wx_calendar#354]
[**BUG描述**](url
[日历选中框跳动.mp4.zip](https://github.com/treadpit/wx_calendar/files/4969919/mp4.zip)

)

**复现步骤**

**期望结果**

**实际结果**

**截图**

**Comment by slimvan** [comment]
![image](https://user-images.githubusercontent.com/17959299/88369144-fcb00e00-cdc1-11ea-9b16-e17bec0162a7.png)
![image](https://user-images.githubusercontent.com/17959299/88369160-033e8580-cdc2-11ea-9568-d4524965f931.png)
已解决，resetDates的加载时机放在calculateEmptyGrids中效果会更好点，然后就是reset给了30的长度，这样避免了日历高度跳动的问题

**Comment by jerossh** [comment]
有更多的解决代码可以参考吗，这个问题还是存在的

**Comment by cywcd** [comment]
去掉组件里日期.date的css动画就好了
`.date {
    position: relative;
    left: 0;
    top: 0;
    width: 60rpx;
    height: 60rpx;
    text-align: center;
    line-height: 60rpx;
    font-size: 36rpx;
    font-weight: 200;
    border-radius: 16rpx;
    /* transition: all 0.3s;
    animation-name: choosed;
    animation-duration: 0.5s;
    animation-timing-function: linear;
    animation-iteration-count: 1; */
}`
