### ISSUE TITLE
设置代办标注时无法设置不同颜色

### ISSUE THREAD

**Issue by lishikang** [treadpit/wx_calendar#358]
**BUG描述**
 在设置代办标注时，不同天无法设置不同颜色，执行两次代办时，会把之前设置的颜色变成当前设置的颜色，业务上无法做到区分。
**复现步骤**
calendar['setTodoLabels']({
      showLabelAlways: true,
      dotColor: 'blue',
      days: [{year:2020,month:8,day:4,todoText: ''}]
    });
calendar['setTodoLabels']({
      showLabelAlways: true,
      dotColor: 'red',
      days: [{year:2020,month:8,day:5,todoText: ''}]
    });
这样执行后，会把4号的蓝色变成5号的红色。
**期望结果**
期望能设置不同颜色代办标注
**实际结果**

**截图**

**Comment by treadpit** [comment]
`dotColor` 是代办全局配置，若想单独配置每天，请[参考文档](https://treadpit.github.io/wx_calendar/?id=_9-1-%E8%AE%BE%E7%BD%AE%E5%BE%85%E5%8A%9E%E4%BA%8B%E9%A1%B9)

```js
this.calendar.setTodoLabels({
  days: [
    {
      year: 2018,
      month: 1,
      day: 1,
      todoText: '待办',
      color: '#f40' // 单独定义代办颜色 (标记点、文字)
    }
  ]
});
```

**Comment by lishikang** [comment]
ok, 感谢

**Comment by lishikang** [comment]
但是文档地址打不开，请问还有地方可以看到文档内容吗？

**Comment by treadpit** [comment]
打不开？文档地址为：[https://treadpit.github.io/wx_calendar](https://treadpit.github.io/wx_calendar/) ，被q了？
