### ISSUE TITLE
是否有wepy的使用方法

### ISSUE THREAD

**Issue by anonymous-qsh** [treadpit/wx_calendar#36]

**Comment by treadpit** [comment]
#35， 目前还没有移植到 `wepy`

**Comment by devzhujiang** [comment]
请问现在可以在wepy中使用了吗？

**Comment by treadpit** [comment]
因目前小程序框架太多，暂时无将其适应至各个平台的计划。代码逻辑是一样的，可以自己尝试兼容迁移

**Comment by bigmeow** [comment]
在组件中操作了页面数据，数据是放页面里而不是组件私有，这一点导致了很难适配其它小程序框架

**Comment by xiaoshuiwei** [comment]
> 请问现在可以在wepy中使用了吗？
请问你用wepy封装好了吗

**Comment by treadpit** [comment]
`wepy 1.7.1`  [已支持直接接入原生组件](https://github.com/Tencent/wepy/blob/2.0.x/CHANGELOG.md) 

使用参考：[issues#241](https://github.com/treadpit/wx_calendar/issues/241#issuecomment-567301142)
