### ISSUE TITLE
真机调试 待办事项不遍历月份

### ISSUE THREAD

**Issue by wuzongqi** [treadpit/wx_calendar#360]
**BUG描述**
真机调试待办事项不遍历月份 不执行点击日历方法
在开发者工具中可以执行
**复现步骤**

**期望结果**

**实际结果**

**截图**
电脑端
![image](https://user-images.githubusercontent.com/63346166/89409330-7a760100-d754-11ea-8f52-ce5297fb4ec6.png)
手机端
![image](https://user-images.githubusercontent.com/63346166/89409467-b01aea00-d754-11ea-8de4-1892ebe6739c.png)

![image](https://user-images.githubusercontent.com/63346166/89409507-c4f77d80-d754-11ea-83f1-6c5f39055724.png)

**Comment by treadpit** [comment]
> 真机调试待办事项不遍历月份

这个是指什么意思呢？能提供最小复现 `demo` ？

**Comment by wuzongqi** [comment]
微信小程序真机调试&nbsp; &nbsp;日历事件不管用&nbsp;不触发事件&nbsp; &nbsp;周日历样式不对，但是体验版可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "imfu"<notifications@github.com&gt;; 
发送时间: 2020年8月6日(星期四) 下午4:26
收件人: "treadpit/wx_calendar"<wx_calendar@noreply.github.com&gt;; 
抄送: "&amp;#x1F43E;"<1587343329@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [treadpit/wx_calendar] 真机调试 待办事项不遍历月份 (#360)





  
真机调试待办事项不遍历月份
  
这个是指什么意思呢？能提供最小复现 demo ？

**Comment by treadpit** [comment]
开发工具真机调试与真机表现不符不属于日历组件问题，需要排查是否为微信侧原因
