### ISSUE TITLE
自定义配置 data 中设置defaultDay显示

### ISSUE THREAD

**Issue by caishengmao** [treadpit/wx_calendar#362]
自定义配置在页面 data 中设置defaultDay给了默认显示的具体日期，在日历中调用afterTapDay事件选择了其他事件，然后从导航组件tabBar第二次进入defaultDay默认日期失效，求解？

**Comment by treadpit** [comment]
> 在日历中调用afterTapDay事件选择了其他事件

这个是指什么意思？

**Comment by caishengmao** [comment]
在小程序组件中调用afterTapDay事件，选择了想要选择日期时间，第二次进入defaultDay默认日期就失效了

**Comment by treadpit** [comment]
> 在小程序组件中调用afterTapDay事件，选择了想要选择日期时间，第二次进入defaultDay默认日期就失效了

是在 afterTapDay 事件中通过函数去选中的想要的日期，而非通过点击选中的是吧？能将大致的逻辑贴一下么？

**Comment by caishengmao** [comment]
比如进入页面在日历上使用defaultDay默认设置选中了下一天时间值，然后点击选中了其他时间，此时返回其他页面，再从tabBar进入这个页面，日历上显示了此前点击选择的时间，并不是defaultDay默认设置选中了下一天时间的值

**Comment by treadpit** [comment]
日历页面为一个tabbar所在页？

**Comment by caishengmao** [comment]
对 tabBar之间对切换

**Comment by treadpit** [comment]
> 对 tabBar之间对切换

微信小程序tabbar的切换，页面是不会销毁，日历组件也是不会销毁的
