### ISSUE TITLE
用组件引入该组件，如何使用调用日历实例

### ISSUE THREAD

**Issue by wuxinwei240** [treadpit/wx_calendar#363]
目前用组件方式引入进来， 但是实例没有找到， 也尝试过ref 没找到对应的方法

**Comment by wuxinwei240** [comment]
目前使用的是taro

**Comment by wuxinwei240** [comment]
问题已经解决，可以获取到当前小程序页面的实例， calendar挂在实例上
/**
   * 日历初次渲染完成后触发事件，如设置事件标记
   */
  afterCalendarRender = (e) => {
    const pageList = Taro.getCurrentPages();
    const calendar = pageList[pageList.length - 1].calendar;
    this.setState({calendar});
  }

**Comment by treadpit** [comment]
> 问题已经解决，可以获取到当前小程序页面的实例， calendar挂在实例上
> /**
> 
> * 日历初次渲染完成后触发事件，如设置事件标记
>   */
>   afterCalendarRender = (e) => {
>   const pageList = Taro.getCurrentPages();
>   const calendar = pageList[pageList.length - 1].calendar;
>   this.setState({calendar});
>   }

如果需要直接使用 `this.calendar`，则需要明确 `this` 指向的是当前页面实例。
直接调用 `Taro.getCurrentPages()` 去取得当前页面实例也OK。

`Taro3.0.5` 中提供了获取当前页面实例的方法 `getCurrentInstance`。
