### ISSUE TITLE
我是少配置了啥么？显示错误

### ISSUE THREAD

**Issue by zeopean** [treadpit/wx_calendar#370]
**BUG描述**
正常的载入进去，有报错，但是显示正常
**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/12742992/92342012-1eefb800-f0f2-11ea-843f-a4e9f74ed97f.png)
![image](https://user-images.githubusercontent.com/12742992/92342034-30d15b00-f0f2-11ea-9a6a-32897099b4e7.png)

**Comment by treadpit** [comment]
这个能提供下你的demo么？
