### ISSUE TITLE
v2文件链接地址错误

### ISSUE THREAD

**Issue by seventhZhao** [treadpit/wx_calendar#371]
**BUG描述**
https://treadpit.github.io/wx_calendar/v2/guide.html#%E5%BC%95%E5%85%A5%E7%BB%84%E4%BB%B6
文档错误：
calendar配置参数应该是calendarConfig，v2文档还未替换
![image](https://user-images.githubusercontent.com/3162278/92342886-d5549c80-f0f4-11ea-8dee-14c9201ba482.png)

calendar内plugins文件地址饮用错误
![image](https://user-images.githubusercontent.com/3162278/92342941-0503a480-f0f5-11ea-9bbb-1753f0260c6a.png)
render文件不存在，正确地址反而为demo内的src目录内文件

**复现步骤**

**期望结果**

**实际结果**

**截图**

**Comment by treadpit** [comment]
已知问题，昨晚已修复，还未合并，跟另外一个版本一起上。
