### ISSUE TITLE
calendarConfig：{ defaultDay: false,}

### ISSUE THREAD

**Issue by WchHxl** [treadpit/wx_calendar#373]
this.calendar.setCalendarConfig({
       defaultDay: this.data.peakOrderInfo.startDate,
});
默认不选择时间，然后页面加载完成设置默认时间，点选择日历，日历打开并没有选中我设置的时间是怎么回事。

**Comment by treadpit** [comment]
这里文档没补全，`setCalendarConfig` 只会对部分配置生效，`defaultDay` 是日历初始化的时候读取的，需要日历加载完成跳转至某天，可调用  'jump'
