### ISSUE TITLE
defaultDate设置为true或者写为固定时间都不生效了

### ISSUE THREAD

**Issue by anjularzwl** [treadpit/wx_calendar#374]
**BUG描述**defaultDate设置为true或者写为固定时间都不生效了

**复现步骤**1.x版本也不生效，2.x版本也不生效

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/27289513/92715317-e836cd80-f38f-11ea-9ce2-139c849cbd8a.png)

![image](https://user-images.githubusercontent.com/27289513/92715271-d9e8b180-f38f-11ea-91c5-9dbbe6d19e3a.png)

**Comment by treadpit** [comment]
v1版本是defaultDAy字段

**Comment by anjularzwl** [comment]
我看了文档，v1版本字段是defaultDay为啥不生效了？是给去掉了吗我用的v1版本目前，能否解释下。。。。。。。。。。。。。。v2版本字段是defaultDate，dom绑定改为了config依旧不生效，而且还是粉色主题。。。裂开
![image](https://user-images.githubusercontent.com/27289513/92880918-0f010c80-f441-11ea-9b6a-27f22be58e6b.png)
![image](https://user-images.githubusercontent.com/27289513/92880971-1a543800-f441-11ea-9707-c4822a1a149d.png)

**Comment by anjularzwl** [comment]
v1版本也不生效
![image](https://user-images.githubusercontent.com/27289513/92882309-605dcb80-f442-11ea-8fb9-ff23024ce5ac.png)
![image](https://user-images.githubusercontent.com/27289513/92882345-69e73380-f442-11ea-8ef7-f30bb20f6534.png)

**Comment by anjularzwl** [comment]
我用的是uni-app框架，在之前v1版本是没有问题的，线上的日历突然选中就不生效了，我看了下文档，更新了，是不是更新的问题导致v1出现问题，还是和uni-app兼容问题？
![image](https://user-images.githubusercontent.com/27289513/93034349-5ae3c980-f66c-11ea-908b-cbb4c7bda94a.png)
![image](https://user-images.githubusercontent.com/27289513/93034358-620ad780-f66c-11ea-80f8-3ceff021da60.png)
![image](https://user-images.githubusercontent.com/27289513/93034366-6a631280-f66c-11ea-96bb-d1fb8f454578.png)
好像都是不生效的，其他字段也都不生效了，小程序基础库版本也都调到最高版本了，dom的话都在图里，因为不是原生，所以我用原生的dom调试了下，发现是生效的。但是在uni-app里面不生效
，作者大大是否使用过框架里面引入测试

**Comment by treadpit** [comment]
其他配置也都不生效的话，你需要看下 `uni-app` 对原生组件的支持是否有变动，是否是数据没有传入到原生日历组件内部
