### ISSUE TITLE
不勾选es6转ES5就一堆报错呢？

### ISSUE THREAD

**Issue by zldai** [treadpit/wx_calendar#376]
由于要使用其他 异步转同步的插件，es6转es5不勾选，加入这个日历组件，已进入就一堆报错呢。这个怎么解决？

MiniProgramError
Unexpected token export
SyntaxError: Unexpected token export
console.error @ VM291:1
errorReport @ VM298 WAService.js:2
thirdErrorReport @ VM298 WAService.js:2
(anonymous) @ VM298 WAService.js:2
f @ VM298 WAService.js:2
o @ VM298 WAService.js:2
(anonymous) @ VM298 WAService.js:2
value @ VM298 WAService.js:2
(anonymous) @ VM298 WAService.js:2
error (async)
(anonymous) @ VM298 WAService.js:2
(anonymous) @ VM298 WAService.js:2
(anonymous) @ VM298 WAService.js:2

MiniProgramError
Unexpected identifier
SyntaxError: Unexpected identifier

**Comment by treadpit** [comment]
这个应该是开发者工具本身是不支持某些 `es6` 的特性，不转换是不能使用的。

虽然可以不勾选，但你的代码打包后在开发者工具中运行的最终也应该转为 `es5` 的
