### ISSUE TITLE
JS报错找不到todayDate()

### ISSUE THREAD

**Issue by cqlicheng** [treadpit/wx_calendar#377]
**BUG描述**
配置禁用某一天之前/之后的所有日期时，JS报错找不到todayDate()，自行研究后发现components\calendar\utils\index.js内确无此函数，而todayFMD()似乎可以起到应有的效果

`calendarConfig: {
      theme: 'elegant',
      multi: true,
      firstDayOfWeek: 'Mon',
      disableMode: {
        // 禁用某一天之前/之后的所有日期
        type: 'before', // [‘before’, 'after']
        date: false// 无该属性或该属性值为假，则默认为当天
      },
    },`

即将components\calendar\index.js中setDefaultDisableDate()部分的dateUtil.todayDate()更改为dateUtil.todayFMD()，问题解决

**截图**
![QQ截图20200915231010](https://user-images.githubusercontent.com/30280770/93229169-dea2d080-f7a8-11ea-9bcf-b9c8c2a69fe0.png)

**Comment by cqlicheng** [comment]
对了是V2版本

**Comment by treadpit** [comment]
不好意思，迁移过程中遗漏了这个，造成了错误，我修复一下
