### ISSUE TITLE
示例图片中某些日期下的“领奖日”功能怎样才能实现？

### ISSUE THREAD

**Issue by blackblue** [treadpit/wx_calendar#379]
可以针对某一天进行内容编辑吗？比如像示例图片中，给几个日期下面加上“领奖日”几个字，怎样才能实现呢？

**Comment by treadpit** [comment]
[设置待办事项](https://treadpit.github.io/wx_calendar/v2/api.html#%E8%AE%BE%E7%BD%AE%E5%BE%85%E5%8A%9E%E4%BA%8B%E9%A1%B9)
