### ISSUE TITLE
多选状态下设置事件标记BUG

### ISSUE THREAD

**Issue by suyuqian** [treadpit/wx_calendar#38]
想在多选状态下把getSelectedDay（）得到的数据赋给days，但setTodoLabels设置无效

**Comment by treadpit** [comment]
没太懂你的操作步骤，取到 `getSelectedDay()` 的 `days` 后，`setTodoLabels()` 又是设置的什么数据呢，就是取出的 `days`?

**Comment by treadpit** [comment]
暂无反馈，先关闭
