### ISSUE TITLE
日历渲染问题

### ISSUE THREAD

**Issue by caishengmao** [treadpit/wx_calendar#380]
进入页面加载渲染完成后，初始化定义显示选中今天的日期，之后进入下个月的某一天，点击切换tabBar再次进入，怎样才能回到初始化的状态？

**Comment by treadpit** [comment]
小程序tab切换不会销毁页面组件，如果需要重新初始化日历，用 wx:if 来控制试试

**Comment by caishengmao** [comment]
没太明白，可以具体讲一下吗

**Comment by treadpit** [comment]
```xml
<Calendar wx:if="{{showCalendar}}" />
```

```js
Page({
   onShow() {
     this.setData({
       showCalendar: true
     })
   },
   onHide() {
     this.setData({
       showCalendar: false
     })
   }
})
```

[条件渲染 | 微信开放文档](https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/conditional.html)

[页面路由 | 微信开放文档](https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/route.html#%E8%B7%AF%E7%94%B1%E6%96%B9%E5%BC%8F)

**Comment by caishengmao** [comment]
明白了，这种方式可以解决。
