### ISSUE TITLE
master分支是哪个版本？1.x还是2.0？calendar实例无法获取。

### ISSUE THREAD

**Issue by ChrisZou** [treadpit/wx_calendar#382]
**BUG描述**
calender实例无法获取，无论是使用1.x还是2.0的方法。
`afterCalendarRender(e)`方法不会回调，而在onShow或onReadly里面使用 `const calendar = this.selectComponent('#calendar').calendar` 获取到的calendar也是undefined。
wxml里面的定义： 
`<calendar id="calendar"/>`

**Comment by treadpit** [comment]
`v1` 版本的周视图不刷新 #366 
`v2` 版本目前不支持直接配置 `weekMode: true`, `V2` 目前支持的配置以文档为准

`master` 分支包含 `v1` 及 `v2` 版本。

![image](https://user-images.githubusercontent.com/10692855/95089347-a0b91c80-0756-11eb-9c9d-a74955cbbb6f.png)
