### ISSUE TITLE
周视图模式下，9月到10月间出现了31号

### ISSUE THREAD

**Issue by august-lion** [treadpit/wx_calendar#383]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/54350196/95036145-9d437800-06f9-11eb-8d09-eee1ee927c9f.png)

**Comment by treadpit** [comment]
使用的是插件版本，还是 `v1` 的老版本呢？

两个版本测试了下是OK的，是最新的 `master` 代码么? 能否提供最小复现demo？

![image](https://user-images.githubusercontent.com/10692855/95088964-2ab4b580-0756-11eb-9367-eec316b5b895.png)

**Comment by august-lion** [comment]
![image](https://user-images.githubusercontent.com/54350196/95093141-06a7a300-075b-11eb-94c2-47bb9b6410dd.png)
哪个才是V2版？示例的V2版是出现这个情况

**Comment by treadpit** [comment]
`/src/component/*` 文件夹内有两个版本

**Comment by august-lion** [comment]
我截图就是master里面的V2示例，没有改动任何东西

**Comment by treadpit** [comment]
确实不复现这个东西，能给我发个你下载的代码压缩包不？

**Comment by treadpit** [comment]
暂无反馈，仍有问题再开 `issue`
