### ISSUE TITLE
afterTapDay里e.target显示为空?

### ISSUE THREAD

**Issue by lily2088** [treadpit/wx_calendar#387]
**问题描述**
afterTapDay里面e.target显示为空? 然后我console.log(e)看两个target都是空? 是不可以用这个还是使用的不对?

afterTapDay(e) {
    console.log(e.target);
   console.log(e);
}
![image](https://user-images.githubusercontent.com/43135059/95836199-bdb2a880-0d71-11eb-8e30-188257ede33e.png)

**Comment by treadpit** [comment]
这个是 `triggerEvent` 触发的，数据在 `detail` 里面

**Comment by lily2088** [comment]
> 这个是 `triggerEvent` 触发的，数据在 `detail` 里面

好的,谢谢.
我是想获取点击日期的位置. 那估计是不支持.

**Comment by treadpit** [comment]
> > 这个是 `triggerEvent` 触发的，数据在 `detail` 里面
> 
> 好的,谢谢.
> 我是想获取点击日期的位置. 那估计是不支持.

获取位置是指什么？是出于什么需求考虑的呢？

**Comment by lily2088** [comment]
> > > 这个是 `triggerEvent` 触发的，数据在 `detail` 里面
> > 
> > 
> > 好的,谢谢.
> > 我是想获取点击日期的位置. 那估计是不支持.
> 
> 获取位置是指什么？是出于什么需求考虑的呢？

就是日历有todo的点了以后, 在日期附近显示对应日期的内容.

**Comment by treadpit** [comment]
这个目前是不支持的，你可以采用 `slot` 的方式来扩展下。

```js
Page({
  afterTapDate(e) {
    console.log('afterTapDate', e.detail) 

   // 伪代码 
   ...
    const popupData = await asyncRequest(date_param)
   ....
    this.setData({
      popup: popupData
   })
  }
})
```

```xml
<Calendar>
  <view slot="popup">{{popup}}</view>
</Calendar>

<view class="date b ac pc">
  ...
  <slot name="popup"></slot>
  ...
</view>

```
