### ISSUE TITLE
2.x版本报错calendar.chooseDateArea is not a function

### ISSUE THREAD

**Issue by ideagay** [treadpit/wx_calendar#388]
**问题描述**
使用的是v2版本，选择日期范围报错

**代码**
afterCalendarRender(e) {
    const calendar = this.selectComponent('#calendar').calendar
    calendar.chooseDateArea(['2020-10-10', '2020-10-20']).then(dates => {
      console.log('choosed dates: ', dates);
    });
},

**报错**
控制台报错
MiniProgramError
calendar.chooseDateArea is not a function
TypeError: calendar.chooseDateArea is not a function

**Comment by treadpit** [comment]
对应插件 `/component/v2/plugins/time-range` 是否引入？

**Comment by ideagay** [comment]
> 对应插件 `/component/v2/plugins/time-range` 是否引入？

引入了，替换成1.x版本，可以用，但是不支持多段连续时间范围，就没有办法了

**Comment by treadpit** [comment]
> > 对应插件 `/component/v2/plugins/time-range` 是否引入？
> 
> 引入了，替换成1.x版本，可以用，但是不支持多段连续时间范围，就没有办法了

测试了一下 `v2` 是可以使用的，能否把你的 `demo` 发我看看？

***多个连续时间段没有还没有支持。***
