### ISSUE TITLE
v2版本 使用自定义配置不生效

### ISSUE THREAD

**Issue by DackKnight** [treadpit/wx_calendar#391]
**问题描述**
具体描述使用过程中有不明白或者疑惑的地方
你好 我在js的page里面的data加上了相关的配置 标签也引入了对应的字段 打印取值是可以取到的 但是组件修饰改变，请问这是什么原因呢？ 谢谢！

**Comment by treadpit** [comment]
可否贴下代码，是否和 `demo` 做过对比，有什么不一样的不？

**Comment by DackKnight** [comment]
> 可否贴下代码，是否和`demo`做过对比，有什么不一样的不？
![image](https://user-images.githubusercontent.com/29497199/97134065-01041280-1787-11eb-954b-b8336a33c680.png)
![image](https://user-images.githubusercontent.com/29497199/97134075-095c4d80-1787-11eb-904d-5e8a74906664.png)


你好 这是页面和js的代码 对比demo后未发现有什么不一样 我js配置了两个字段 但是均未生效。

**Comment by DackKnight** [comment]
> 可否贴下代码，是否和 `demo` 做过对比，有什么不一样的不？

你好 已经找到问题所在，是json配置组件路径错误导致的 应该配相对路径 我配的是绝对路径，打扰了 感谢~

**Comment by huihuilovekuikui** [comment]
> > 可否贴下代码，是否和 `demo` 做过对比，有什么不一样的不？
> 
> 你好 已经找到问题所在，是json配置组件路径错误导致的 应该配相对路径 我配的是绝对路径，打扰了 感谢~

我也出现了这个问题。配置相对路径指的是组件引入的路径吗？我改成相对路径还是无法生效
