### ISSUE TITLE
2.0文档自定义配置描述可能有误

### ISSUE THREAD

**Issue by huihuilovekuikui** [treadpit/wx_calendar#392]
**问题描述**
![image](https://user-images.githubusercontent.com/66559869/97389012-5ae61300-1914-11eb-9053-c26492f0b567.png)
今天第一次使用小历同学，根据文档发现自定义配置不生效，然后查看了1.x的文档，发现组件传值地方的名字不一样，改了之后就可以用了
![image](https://user-images.githubusercontent.com/66559869/97389146-ad273400-1914-11eb-9ae6-8505839e4765.png)
刚开始以为自己可能下错版本了，确认后下的确实是最新版，望作者确认一下

**Comment by huihuilovekuikui** [comment]
下载的确实是最新的版本，但是2.x以上版本的属性无法使用
![image](https://user-images.githubusercontent.com/66559869/97398293-e7e59800-1925-11eb-9f57-68a8697d7e31.png)
比如这个高亮显示周末
![image](https://user-images.githubusercontent.com/66559869/97398010-6c83e680-1925-11eb-99ce-ca4f5f23ba05.png)
现在是只有1.x的文档的功能吗？

**Comment by huihuilovekuikui** [comment]
![image](https://user-images.githubusercontent.com/66559869/97398538-5fb3c280-1926-11eb-8aff-eeb6479fa6e3.png)

**Comment by huihuilovekuikui** [comment]
问题已经解决了，因为我没有引入v2的文件，直接把首页的calender复制进了组件，应该去src中寻找，高亮应该是主题的问题，黑白的主题没有效果

**Comment by treadpit** [comment]
1. `calendarConfig` 在 `v2` 中更正为了 `config`，组件本身为 `<calendar />`，所以`calendarConfig`有点重复。
2. `elegant` 主题周末高亮颜色值和正常日期色值一样了 (`BUG`)
