### ISSUE TITLE
module "components/calendar/core" is not defined

### ISSUE THREAD

**Issue by hank205** [treadpit/wx_calendar#393]
基本的日历已经可以显示出来了，然后在js里加了
`import plugin from '../../components/calendar/plugins/index'`
之后就报错了：`components/calendar/plugins/preset/base.js:
 Error: module "components/calendar/core" is not defined`

看了下 ‘calendar/plugins/preset/base.js’ 开头
`import { calcJumpData } from '../../core'`
`import { renderCalendar } from '../../render'`

我寻思着GitHub的calendar文件夹里确实没有这两个文件，这是怎么调用的？
是我哪里没用对吗？

**Comment by treadpit** [comment]
`calendar` 文件夹打包的是 `v1` 版本的，`v2` 版本使用的按需引入没有单独打包，这里没有标识出来，我修改下。
