### ISSUE TITLE
为什么我的模拟器种展示是好的，到手机样式好像就挤到了一起

### ISSUE THREAD

**Issue by WchHxl** [treadpit/wx_calendar#394]
**问题描述**
具体描述使用过程中有不明白或者疑惑的地方
![image](https://user-images.githubusercontent.com/26077184/98660349-2ba5bc00-2380-11eb-84d4-957ef3707bf1.png)
这是小程序开发工具的
![image](https://user-images.githubusercontent.com/26077184/98660593-7293b180-2380-11eb-9969-096d8011fa4f.png)
这个是手机上

**Comment by WchHxl** [comment]
@treadpit

**Comment by treadpit** [comment]
排查一下外层容器样式（真机调试）

**Comment by WchHxl** [comment]
查到了  我外层的position影响了
