### ISSUE TITLE
默认时间配置问题

### ISSUE THREAD

**Issue by WchHxl** [treadpit/wx_calendar#397]
**BUG描述**
![image](https://user-images.githubusercontent.com/26077184/99233924-d4e02c80-282e-11eb-96e8-1770b350343c.png)
默认时间我选的false
![image](https://user-images.githubusercontent.com/26077184/99234053-035e0780-282f-11eb-8613-dbb30b2935e5.png)
打开日历为啥还是默认选中了~

**复现步骤**

**期望结果**

**实际结果**

**截图**

**Comment by WchHxl** [comment]
@treadpit 大佬来看下这个问题吧~

**Comment by WchHxl** [comment]
是因为我用enableDays()这个方法吗？设置的那几天可选

**Comment by WchHxl** [comment]
解决了~
1、点击日历日期，我会暂存到一个数组toSet，因为下次打开要默认选中之前选择的日期。
2、每次打开日历，先判断toSet长度。为0则为第一次打开，就调用cancelSelectedDates()方法，清空所有选中，不为0则代表已经选过日期，则其他逻辑
暂时规避了 配置defaultDay：false，但是不生效的问题，猜测是我点击显示日历初始化时候的毛病。

**Comment by treadpit** [comment]
使用的是 `v1` 版本？
