### ISSUE TITLE
月最后一天是周日时，点击最后一天，再切换周日历不成功。v2版本

### ISSUE THREAD

**Issue by Ft-Zhang88** [treadpit/wx_calendar#398]
**BUG描述**

版本：v2

当出现月最后一天是周日时，比如2021-01-31，2021-02-28均为周日，在月日历视图下点击最后一天，然后再去切换周日历，切换后不成功，周日历的日期不显示。

**复现步骤**

**期望结果**

**实际结果**

**截图**

**Comment by treadpit** [comment]
测试的代码是什么时候的包呢？

**Comment by Ft-Zhang88** [comment]
> 测试的代码是什么时候的包呢？

10月19日下载的代码，使用的V2。

**Comment by treadpit** [comment]
> > 测试的代码是什么时候的包呢？
> 
> 10月19日下载的代码，使用的V2。

用最新 `master` 代码测试没有问题，拉下最新的，这个应该和 #395 是一个原因造成的

**Comment by Ft-Zhang88** [comment]
又重新验证了，应该是firstDayOfWeek: 'Mon'后的问题。具体现象如下：
1、星期日在最后一列，2021-01-31，2021-02-28均为周日，且为最后一列时，切换日历不成功。
2、其他时间切换日历的时候，没有按照星期一是第一天进行切换，而是仍按照星期日为第一天进行切换的，所以切换到了下一周。
