### ISSUE TITLE
onTapDay事件添加后，日期选中效果没有了

### ISSUE THREAD

**Issue by michael2043** [treadpit/wx_calendar#40]
不加onTapDay事件，选择一个日期后会有背景色选中效果，添加之后没有了。。。
如何保持选中效果
还有如何更改选中背景色

**Comment by treadpit** [comment]
`onTapDay()` 会完全接管点击事件，模板不会再对点击做任何处理；

`afterTapDay ()` 为日历点击选中后执行的函数，此时选中效果存在；

ps: 更改背景选中颜色，在下一个版本中，可传入自定义 class
