### ISSUE TITLE
为啥我设置日历里面的待办事项数据更新了 但是视图并没有更新？

### ISSUE THREAD

**Issue by davidgww** [treadpit/wx_calendar#400]
that.calendar.setTodoLabels({
              // 待办点标记设置
              pos: 'top', // 待办点标记位置 ['top', 'bottom']
              dotColor: 'purple', // 待办点标记颜色
              // circle: true, // 待办圆圈标记设置（如圆圈标记已签到日期），该设置与点标记设置互斥
              showLabelAlways: true, // 点击时是否显示待办事项（圆点/文字），在 circle 为 true 及当日历配置 showLunar 为 tru时，此配置失效
              days: that.data.luckDay  为甚么这个地方的数据源更新了 但是日历视图没有更新？？？？？
            });

**Comment by treadpit** [comment]
`that.data.luckDay` 这个数据源本身的变动并不会更新视图，需要重新设置

**Comment by davidgww** [comment]
如何重新设置 我没看到有重载日历的方法啊？麻烦告知一下 谢谢

**Comment by treadpit** [comment]
更新后重新调用 `setTodoLabels`

**Comment by davidgww** [comment]
我就是这么用的  因为我这个有点特殊  待办事项不是分为两种吗 我的默认就是其中一种  然后我点击设置 要把它换成另外一种 然后也从新setTodoLabels 了 但是视图就是不更新 刷新下页面也是正常的

**Comment by davidgww** [comment]
![image](https://user-images.githubusercontent.com/48271866/101580500-64839000-3a15-11eb-968b-e19f7c9a8030.png)

**Comment by treadpit** [comment]
两种是指圈标记和点标记？能不能给个最小  `demo` 我调试下

**Comment by davidgww** [comment]
方便加个wx吗 我来发个小demo 给您？ jbjb00cs

**Comment by davidgww** [comment]
其实就是本来 今天是圆圈标记的 然后我要改成点标记  然后从新 setTodoLabels 不生效  如果是普通的日子 本来是没有标记的  我这边 setTodoLabels 是生效的

**Comment by treadpit** [comment]
已加，也可发我邮箱。
