### ISSUE TITLE
页面布局错误

### ISSUE THREAD

**Issue by kvgnt** [treadpit/wx_calendar#408]
**BUG描述**
分辨率1080*2244, 华为 Mate 20 X 
星期天的数据会被换行
**复现步骤**

**期望结果**

**实际结果**

**截图**
https://s3.ax1x.com/2020/12/30/rqzndH.png

<a href="https://imgchr.com/i/rqzndH"><img src="https://s3.ax1x.com/2020/12/30/rqzndH.png" alt="rqzndH.png" border="0" /></a>

**Comment by occumacy** [comment]
华为荣耀V20，分辨率2310*1080，也有同样的问题

**Comment by kvgnt** [comment]
index.wxss 里的 .grid,.week{ width 改  14% } 解决了.
