### ISSUE TITLE
微信老版本无法显示

### ISSUE THREAD

**Issue by BleachCC** [treadpit/wx_calendar#409]
**BUG描述**
微信版本6.7上使用，日历无法显示，也没看到报错
**复现步骤**
微信版本6.7上使用
**期望结果**

**实际结果**

**截图**

**Comment by treadpit** [comment]
这个需要具体的排查基础库版本了，看下6.7微信的小程序基础库版本然后在开发工具上切换为对应版本测试下呢

**Comment by BleachCC** [comment]
是的，使用的1.x版本基础库测试，对应微信版本6.6以上，无法显示，也无报错



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: imfu <notifications@github.com&gt;
发送时间: 2021年1月20日 19:38
收件人: treadpit/wx_calendar <wx_calendar@noreply.github.com&gt;
抄送: BleachCC <799102285@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[treadpit/wx_calendar] 微信老版本无法显示 (#409)





 
这个需要具体的排查基础库版本了，看下6.7微信的小程序基础库版本然后在开发工具上切换为对应版本测试下呢
