### ISSUE TITLE
部分机型日期错位

### ISSUE THREAD

**Issue by ZZHJohn** [treadpit/wx_calendar#410]
**BUG描述**
部分机型日期错位，只修改了主题颜色，没有改动其他样式

**复现步骤**
已在项目上使用，部分小米系机型反馈日期错位，详情见图，一周最后一天那一列都为空
目前正在联系出问题的部分用户测试
**期望结果**

**实际结果**

**截图**

![微信图片_20210127170050](https://user-images.githubusercontent.com/39553151/105968103-9a61fe00-60c1-11eb-83a2-7432887399bd.jpg)

**Comment by treadpit** [comment]
#321

**Comment by LBCook** [comment]
我手上会出现这个问题的是小米5，还有微信小程序开发工具选择机型（iPad(768X1024|Dpr :2)）
