### ISSUE TITLE
日期选择问题

### ISSUE THREAD

**Issue by Niannian512** [treadpit/wx_calendar#411]
**问题描述**

takeoverTap设置为false的时候，点击某个日期有选中样式，设置为true的时候，能捕获选中的日期却没有样式。对组件的使用实在是有点迷惑。另外年份切换，月份切换可以自定义配置吗，我没找到。

我的需求是实现一个可以展示30-40天的预约日历（某天是否约满是否可约）。可以单选日期，并可以自定义选中日期的样式。

**Comment by treadpit** [comment]
`takeoverTap` 根据文档描述会完全接管点击，日历不会做任何操作反馈
