### ISSUE TITLE
使用代办事项之后，再进行jump，之前的代办事项被清空了

### ISSUE THREAD

**Issue by selectDele** [treadpit/wx_calendar#418]
我一个页面有两个日历组件，分别使用两个对象接收实例。在我初始化结束之后加上一个代办事项数据，之后进行jump操作，待办事项的页面展示就没有了，再次之后我去查询所有代办事项数据中有数据存在，就是没有展示在页面上。如果我不做jump操作就没有问题。

**Comment by treadpit** [comment]
数据应该是存在组件内部的，照理说是隔离的，这个我看下原因

**Comment by selectDele** [comment]
谢谢，目前我的解决方案是每次jump都之后都进行了一次setToDos

**Comment by WilliamCheen** [comment]
我在周视图模式下设置后，当前日期会显示 dot，可是一旦滑动到下一页或上一页再回来就没了。使用 Demo 里的设置待办也一样，滑动之后就没啦

**Comment by WilliamCheen** [comment]
啊，我想采用 selectDele 的方式在 onSwipe 里重设一遍 todos 结果发现 onSwipe 始终不调用，然后试了一下 Demo 发现也不调用，哭惹 😭

**Comment by treadpit** [comment]
> 啊，我想采用 selectDele 的方式在 onSwipe 里重设一遍 todos 结果发现 onSwipe 始终不调用，然后试了一下 Demo 发现也不调用，哭惹 😭

这个问题我跟进下，`onSwipe` 不生效，使用 `whenChangeWeek`

**Comment by WilliamCheen** [comment]
啊，我在 handleSwipe 里加了一段触发代码，强制触发了 onSwipe 事件。事件算是触发了，不过有几率重设 todos 后 dot 也加载不出来。另外看代码 whenChangeMonth 和 whenChangeWeek 是不兼容的，实际上周视图模式下也能触发月份改变，目前我还没想好怎么修改这段代码。主要是我们的待办事件是按月获取的，如果周视图模式下不能获知月份改变的话也就无法请求数据，木得办法

`handleSwipe(direction) {
      let swipeKey = 'calendar.leftSwipe'
      if (direction === 'right') {
        swipeKey = 'calendar.rightSwipe'
      }
      this.setData({
        [swipeKey]: 1
      })
      const { calendar } = this.data
      let calendarData = calendar
      const { curYear, curMonth } = calendarData
      const getMonthInfo = calcTargetYMInfo()[direction]
      const target = getMonthInfo({
        year: +curYear,
        month: +curMonth
      })
      target.direction = direction
      this.renderCalendar(target)

      this.triggerEvent('onSwipe', {
        directionType: direction,
      })
    }`

**Comment by treadpit** [comment]
同步最新代码试试 @WilliamCheen

**Comment by selectDele** [comment]
请问下解决了吗？

**Comment by treadpit** [comment]
> 请问下解决了吗？

release/2.1.0
