### ISSUE TITLE
Hi, 请问周视图模式下支持隐藏年月 Header 吗？

### ISSUE THREAD

**Issue by WilliamCheen** [treadpit/wx_calendar#419]
**问题描述**
具体描述使用过程中有不明白或者疑惑的地方

日历周视图模式下支持隐藏年月 Header 吗？由于 UI 的需要，年月需要在其他位置显示，同时隐藏 Header 上的年月

**Comment by treadpit** [comment]
`1.x` 版本有个 `hideHeadOnWeekMode` 配置，但 `v2` 还没有挪过来，急用可以先自己修改下：

```xml
<view wx:if="{{!config.hideHeadOnWeekMode}}"></view>
```

```js
// 配置中增加配这个即可：

{
   hideHeadOnWeekMode: true
}
```

**Comment by WilliamCheen** [comment]
嗯，不太想切到 1.x 版本，我就在 v2 的 index.wxml 里加了一个配置
`<view class="handle {{config.theme}}_handle-color fs28 b lr ac pc" wx:if="{{ !config.hiddenYearMonthHeader }}">`
也算解决问题啦。

非常感谢 treadpit 积极仔细的回复！

还有一点就是如何自定义日历的 UI 显示呢，比如说文本颜色，选中颜色之类的。是自己新建一个主题还是覆盖 style 呢？新建主题的话类似这种 theme-custom.wxss 吗?

**Comment by treadpit** [comment]
参考 `theme` 文件夹下的 `theme-elegant.wxss` 文件，该文件下都是颜色相关的样式。

1. 复制一份  `theme-elegant.wxss`，重命名为 `theme-custom.wxss`
2. 替换其中的 `elegant` 为 `custom` 
3. 在 `index.wxss` 中引入 `theme-custom.wxss`（其他两个主题不需要可删除引用）
4. `config` 配置中配置 `{theme: 'custom'}`

**Comment by WilliamCheen** [comment]
嗯，非常感谢！我已经实现了修改颜色了，不过这个星期的 header 感觉有点透明度，是我的姿势不对吗 🤔️
![WX20210329-173348](https://user-images.githubusercontent.com/13784770/112817405-f989c200-90b4-11eb-912e-b519f806d097.png)

**Comment by treadpit** [comment]
原有样式有设置透明度，可自行覆盖或修改

```css
.weeks {
    height: 50rpx;
    line-height: 50rpx;
    opacity: 0.5;
}
```
