### ISSUE TITLE
 设置最大最小选择范围的时候 月份2018-08-12 和2018-8-12会有一天的偏差

### ISSUE THREAD

**Issue by kevinzl** [treadpit/wx_calendar#42]

**Comment by kevinzl** [comment]
发现个小bug 设置最大最小选择范围的时候 月份2018-08-12 和2018-8-12会有一天的偏差，2018-08-12只能从13号开始选，2018-8-12就可以从12号就开始选了

**Comment by kevinzl** [comment]
设置最大的时候就没问题，2018-8-30，2018-08-30 两种设置结果就是一样的，就是设置最小选择日期的时候有一天偏差的小Bug

**Comment by kevinzl** [comment]
wepy中貌似也可以直接套过去用，目前测试可以，问题不大

**Comment by treadpit** [comment]
@kevinzl 

关于BUG

>  设置最大最小选择范围的时候 月份2018-08-12 和2018-8-12会有一天的偏差

已修复

**Comment by kevinzl** [comment]
666
