### ISSUE TITLE
请问周视图模式下支持 Jump 到指定日期吗？

### ISSUE THREAD

**Issue by WilliamCheen** [treadpit/wx_calendar#422]
**问题描述**
具体描述使用过程中有不明白或者疑惑的地方

目前是这样的需求，在全屏日历页面选中某天后，前一个周视图的 wx_calendar 也需要选中到那天。我的做法是使用 Jump 到那天，可发现日历会被切换成月视图模式，而且也没又跳转。目前还不知道如何正确的设置周视图模式下的选中日期 😓

**Comment by treadpit** [comment]
使用 `calendar.weekModeJump()` 

![image](https://user-images.githubusercontent.com/10692855/113974153-07d39d00-9870-11eb-941c-feca52d6c701.png)

**Comment by WilliamCheen** [comment]
Thanks! 已可以跳转，不过依旧会存在跳转完成后丢失 events dots 的情况，我这里在跳转完成 then 里重新设置一下 events 就好了，算是解决问题了。有个地方我还是比较疑惑，就是 calendar 的布局，调试的时候发现 height 会比实际需要的高不少，不晓得哪里出了问题 🤔️

**Comment by treadpit** [comment]
丢失 events dots 的情况，这个是使用的 release/2.1.0的代码么？

**Comment by WilliamCheen** [comment]
没有使用 release/2.1.0，先前对源码做了一点点改动，等我有时间了再 pull 过来吧。就第二个布局问题有好的实践方案嘛，我需要再页面顶部 fixed 一下日历，下面放列表数据，如果不能获取到真实的高度怕是有问题呀。我的想法是在 afterRender 之后使用 createSelectorQuery 拿到 ` class = weeks  ` 和 ` class = wrap ` 这两个实例，然后计算一下高度，不知道合适不合适。

**Comment by treadpit** [comment]
样式问题这个得结合具体情况来做处理了，用 `flex` 试试，不用 `fixed`

**Comment by WilliamCheen** [comment]
😄，还是让我给克服了。发现 weekHeader: 50rpx , grid: 80rpx ，我通过计算一下当前月有几行来算整体的高度，目前看来没什么问题。

`
caclCalendarHeight: function(year, month) {
    const datesCount = new Date(Date.UTC(year, month, 0)).getUTCDate()
    const prevDatesCount = new Date(Date.UTC(year, month - 1, 1)).getUTCDay();
    const totalLength = datesCount + prevDatesCount;
    const rowCount = parseInt(totalLength / 7) + ((totalLength % 7 === 0) ? 0 : 1);
    const calenderViewHeight = 50 + rowCount * 80;
    this.setData({
      calendarViewHeight: calenderViewHeight
    });
  },
`

**Comment by WilliamCheen** [comment]
对于这点我其实建议在实现内部每次 render 完成之后 callback 出来当前日历的宽高信息，因为隐藏前月后月显示的时候高度会发生变化，这样便于外部调用者响应这个变化。
