### ISSUE TITLE
获取日历实例对象为undefined 

### ISSUE THREAD

**Issue by Breathing-J** [treadpit/wx_calendar#424]
const calendar = this.selectComponent('#calendar').calendar
获取不到。
wxml代码：<calendar 
id="calendar"
/>

**Comment by treadpit** [comment]
调用的上下文是什么？

**Comment by pengzhonghua** [comment]
1、页面 json 文件里，要引入v2文件夹下面的index
{
  "usingComponents": {
    "calendar": "/component/v2/index"
  }
}
2、wxml 的配置属性为 config
3、const calendar = this.selectComponent('#calendar').calendar
获取日历对象的语句，要放到 onReady 里执行。在 onLoad 和 onShow 阶段，日历节点还没有渲染完成。
