### ISSUE TITLE
使用2.0碰到的问题

### ISSUE THREAD

**Issue by okdin** [treadpit/wx_calendar#426]
用setSelectedDates设置指定日期后，只显示了当月的指定日期，切换其他月份，就不显示了，比如：
const toSet = [
      {year: 2021, month: 3, date: 15},
      {year: 2021, month: 3, date: 19},
      {year: 2021, month: 4, date: 15},
      {year: 2021, month: 4, date: 16},
      {year: 2021, month: 4, date: 17},
      {year: 2021, month: 4, date: 18},
      {year: 2021, month: 4, date: 19},
      {year: 2021, month: 5, date: 15},
      {year: 2021, month: 5, date: 16},
      {year: 2021, month: 5, date: 17},
      {year: 2021, month: 5, date: 18},
      {year: 2021, month: 5, date: 19}
    ]
    calendar.setSelectedDates(toSet)
只显示了4月份的日期，3月份和5月份都不显示了（没有choosed的class标签），请问如何显示其他月份的日期？

**Comment by okdin** [comment]
官方估计不管这个项目了，自己解决了

**Comment by dnjat** [comment]
怎么解决的

**Comment by yumo-mt** [comment]
我解决了这个问题，改点代码就行
