### ISSUE TITLE
version 2.x  calendar 获取方法不完整 ，plugins 下的方法无法调用。

### ISSUE THREAD

**Issue by songyunbiao** [treadpit/wx_calendar#427]
**BUG描述**
如标题
**复现步骤**
clone项目，将v2文件夹整体拷贝到基于taro 2.0.4的项目下进行编译
**期望结果**
calendar.setTodos 成功
**实际结果**
VM1605 WAService.js:2 TypeError: calendar.setTodos is not a function

**截图**
如下为clone 的demo打印calendar信息
<img width="1132" alt="WX20210422-171614@2x" src="https://user-images.githubusercontent.com/9216385/115690478-ac390180-a38f-11eb-972a-8c662312e879.png">
如下为我的项目引入calendar后打印的calendar信息
<img width="698" alt="WX20210422-171447@2x" src="https://user-images.githubusercontent.com/9216385/115690449-a6dbb700-a38f-11eb-9cbe-28d1f0ee09c4.png">
<img width="377" alt="WX20210422-172531@2x" src="https://user-images.githubusercontent.com/9216385/115690579-c2df5880-a38f-11eb-8406-c34f2ea9e30c.png">

**Comment by laienliang** [comment]
怎么解决？

**Comment by songyunbiao** [comment]
> 怎么解决？

在自己需要用到的地方，需要手动的引入。
<img width="801" alt="WX20210428-104647@2x" src="https://user-images.githubusercontent.com/9216385/116338904-14179e00-a80f-11eb-8130-29833fbe8b85.png">
<img width="276" alt="WX20210428-104655@2x" src="https://user-images.githubusercontent.com/9216385/116338918-1a0d7f00-a80f-11eb-985c-4c890b71c75a.png">
红色只是ide的警告，但是能正常使用。
 @laienliang

**Comment by weixioaxiao201803** [comment]
> > 怎么解决？
> 
> 在自己需要用到的地方，需要手动的引入。 <img alt="WX20210428-104647@2x" width="801" src="https://user-images.githubusercontent.com/9216385/116338904-14179e00-a80f-11eb-8130-29833fbe8b85.png"> <img alt="WX20210428-104655@2x" width="276" src="https://user-images.githubusercontent.com/9216385/116338918-1a0d7f00-a80f-11eb-985c-4c890b71c75a.png"> 红色只是ide的警告，但是能正常使用。 @laienliang

谢谢你，解决了
