### ISSUE TITLE
2.0版本，自定义配置字段disableMode禁用某一天之前/之后的所有日期，无效。

### ISSUE THREAD

**Issue by paopao-41** [treadpit/wx_calendar#428]
**问题描述**
![image](https://user-images.githubusercontent.com/68863463/116373874-5ad1bc00-a840-11eb-8c37-d68a447134a2.png)
![image](https://user-images.githubusercontent.com/68863463/116373934-6d4bf580-a840-11eb-8e71-a3a46663c633.png)
![image](https://user-images.githubusercontent.com/68863463/116374024-82c11f80-a840-11eb-97cb-cfa08200b0cc.png)

**Comment by treadpit** [comment]
禁用某一天之前需要明确具体是哪一天，如果是默认 `false`，则默认是当天为分界线

```js
calendarConfig: {
     disableMode: {
        type: 'before', // [‘before’, 'after']
        date: false
     }
},
```
![image](https://user-images.githubusercontent.com/10692855/116490341-b3996700-a8c9-11eb-9aa5-991fc5a45fde.png)


```js
calendarConfig: {
     disableMode: {
        type: 'before', // [‘before’, 'after']
        date: '2021-4-14'
     }
},
```
![image](https://user-images.githubusercontent.com/10692855/116490396-dc216100-a8c9-11eb-82a9-ca1a24a2888d.png)

**Comment by paopao-41** [comment]
您看我的截图，我就是这么写的。
想要的效果是  默认禁用当天之前的日期，所以date写的是false，但是日历上并没有效果。也试过传一个具体的日期进去，例如：type: 'before', date: '2021-4-29'，也还是没有效果，之前的日期依旧可以点击。
这边2.0使用的文件路径是wx_calendar-master/src/component/v2 这个文件夹，请问是否是我这边使用的文件夹弄错了？

**Comment by treadpit** [comment]
使用的文件是没有错的，试下这个 `demo`

[dist.zip](https://github.com/treadpit/wx_calendar/files/6395822/dist.zip)

**Comment by paopao-41** [comment]
这个  demo，运行是正常的。
那原因可能是因为我这边文件是用  .vue写的，组件是用 .wxml  之类写的。
请问除了使用自定义配置字段 disableMode 来限制今天之前不可选以外，还能通过其他方法去限制今天以前的日期不可选吗？

**Comment by treadpit** [comment]
目前方法就是这一个。但功能这个跟什么类型文件没有什么关系。可以打断点调试一下。

主要看下 `/src/component/v2/plugins/selectable.js` 中 `beforeRender` 函数内的逻辑。
