### ISSUE TITLE
enableArea 方法设置可选区间 每次动态设置的时候 在哪里设置才会每次点开都触发，afterCalendarRender() 方法里面触发 只能第一次出发

### ISSUE THREAD

**Issue by kevinzl** [treadpit/wx_calendar#43]

**Comment by kevinzl** [comment]
能否类似defaultDay 直接每次在conf 配置里面动态配置的方式设置 可选区间 ['2018-8-12', '2018-08-30']

**Comment by kevinzl** [comment]
貌似在conf 里面多加一个设置可选区间的 配置 optionalDateInterval：['2018-8-12', '2018-08-30']
然后在renderCalendar()方法的 最前面 去调enableArea(this.config.optionalDateInterval)方法，就可以实现在配置区每次点开动态设置可选区的配置了(注意要在页面渲染之前去掉，也就是renderCalendar()的最前面)

  /**
   * 渲染日历
   * @param {number} curYear
   * @param {number} curMonth
   * @param {number} curDate
   */
  renderCalendar(curYear, curMonth, curDate) {
    enableArea(this.config.optionalDateInterval); //每次动态设置选择范围

    conf.calculateEmptyGrids.call(this, curYear, curMonth);
    conf.calculateDays.call(this, curYear, curMonth, curDate);
    const { todoLabels } = this.data.calendar || {};
    const { afterCalendarRender } = this.config;
    if (todoLabels && todoLabels instanceof Array) conf.setTodoLabels.call(this);
    if (afterCalendarRender && typeof afterCalendarRender === 'function' && !this.firstRender) {
      afterCalendarRender();
      this.firstRender = true;
    }

  },

**Comment by kevinzl** [comment]
在conf设置里面添加一个配置属optionalDateInterval: ['2018-8-12', '2018-08-30'],
然后在renderCalendar() 方法的最前面调用 enableArea( this.config.optionalDateInterval ); 方法，基本可以实现根据选择的出发时间动态设置回程时间的可选区间值，但是当出发时间和回程时间选同一天的时候，貌似dom没有变化导致出现BUG，动态设置失效了，也就这个时候是没有执行renderCalendar()方法的，要选择不同的才会引起dom的重新渲染也就是这个时候才会进去renderCalendar()方法;
  /**
   * 渲染日历
   * @param {number} curYear
   * @param {number} curMonth
   * @param {number} curDate
   */
  renderCalendar(curYear, curMonth, curDate) {
    //每次动态设置选择范围
    enableArea( this.config.optionalDateInterval );

    conf.calculateEmptyGrids.call(this, curYear, curMonth);
    conf.calculateDays.call(this, curYear, curMonth, curDate);
    const { todoLabels } = this.data.calendar || {};
    const { afterCalendarRender } = this.config;
    if (todoLabels && todoLabels instanceof Array) conf.setTodoLabels.call(this);
    if (afterCalendarRender && typeof afterCalendarRender === 'function' && !this.firstRender) {
      afterCalendarRender();
      this.firstRender = true;
    }

  },

**Comment by kevinzl** [comment]
已解决

**Comment by treadpit** [comment]
`conf` 配置每次也只会在初始化日历的时候生效一次，和在`afterCalendarRender()`后调用一次没有区别哟
