### ISSUE TITLE
demo 中的2.0版本调用setCalendarConfig会出现“异常：未找到组件配置信息”

### ISSUE THREAD

**Issue by liyangSuperNb** [treadpit/wx_calendar#432]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

![QQ截图20210507135550](https://user-images.githubusercontent.com/28771495/117404262-3494d600-af3c-11eb-8803-903b46381e21.png)

**Comment by treadpit** [comment]
收到，已修复

**Comment by liyangSuperNb** [comment]
> 收到，已修复 [v2.1.1](https://github.com/treadpit/wx_calendar/releases/tag/release%2F2.1.1)
感谢
