### ISSUE TITLE
日期自定义属性

### ISSUE THREAD

**Issue by 578256945** [treadpit/wx_calendar#435]
能否给每个日期添加自定义属性，在点击日期时能获取这些自定义属性

**Comment by treadpit** [comment]
目前是不支持的。

设置自定义属性的时候也需要根据对应日期去设置，那么也可以在点击的时候根据日期去对应自定义数据吧。

[
  {
     '20220205': {a: 1, b: 2}
  },
  {
     '20220206': {a: 1, b: 2}
  }
]

**Comment by 578256945** [comment]
感谢





------------------ 原始邮件 ------------------
发件人: imfu ***@***.***&gt;
发送时间: 2021年5月7日 19:26
收件人: treadpit/wx_calendar ***@***.***&gt;
抄送: 578256945 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[treadpit/wx_calendar] 日期自定义属性 (#435)





 
目前是不支持的。
 
设置自定义属性的时候也需要根据对应日期去设置，那么也可以在点击的时候根据日期去对应自定义数据吧。
 
[
 {
 '20220205': {a: 1, b: 2}
 },
 {
 '20220206': {a: 1, b: 2}
 }
 ]

**Comment by treadpit** [comment]
不客气 🌝
