### ISSUE TITLE
v2版本中关于 enableDates 方法在文档中的示例参数格式不对，建议修改

### ISSUE THREAD

**Issue by SUN-TN** [treadpit/wx_calendar#439]
**问题描述**
我在使用V2版本的 enableDates  方法时按照V2文档中的使用方法进行传参使用时发现设置之后没有效果，之后发现
v2版本文档中关于 enableDates 方法人参数格式应该由字符串数组格式改为对象数组格式
参数格式应由 
['2021-6-23','2021-6-24']
改为：
[
  {
    year:'2021',
    month:'6',
    month:23
  },
  {
    year:'2021',
    month:'6',
    month:24
  }
]

**Comment by treadpit** [comment]
修复enableDates方法入参字符串数组不生效 [v2.1.2](https://github.com/treadpit/wx_calendar/releases/tag/release%2F2.1.2)
