### ISSUE TITLE
设置disableMode后再调用disableDates有冲突。

### ISSUE THREAD

**Issue by bolingsun** [treadpit/wx_calendar#445]
**BUG描述**
查看官方v2示例，默认禁用了2021-04-14之前的日期了。再点击禁选指定日期，会导致2021-04-14之前的日期又变成可选。
**复现步骤**
点击禁选指定日期后，再点击2021-04-14之前的日期，发现可选。
**期望结果**
2021-04-14之前的日期，应该还是禁用才对。
**实际结果**
2021-04-14之前的日期可选了。
**截图**
![图片](https://user-images.githubusercontent.com/33794781/124721328-991fe180-df3b-11eb-8e8d-7d3e174905ee.png)
![图片](https://user-images.githubusercontent.com/33794781/124721377-a63cd080-df3b-11eb-846f-193d5a77b194.png)

**Comment by treadpit** [comment]
[Merge #444](https://github.com/treadpit/wx_calendar/pull/444)
