### ISSUE TITLE
我按照教程获取组件实例，可结果返回的undefined

### ISSUE THREAD

**Issue by xiaoyu-666** [treadpit/wx_calendar#447]
**问题描述**
我按照教程获取组件实例，可结果返回的undefined
![image](https://user-images.githubusercontent.com/27267958/126726521-5292db05-abde-40de-94e0-e699c3187bfe.png)

![image](https://user-images.githubusercontent.com/27267958/126726540-12dbe795-ca7f-4009-9973-b8d22e8c7d6c.png)
![image](https://user-images.githubusercontent.com/27267958/126726603-2a2098f7-3b7c-4682-91b0-a7d5cd6f407d.png)

**Comment by Hermesshi** [comment]
大佬,你是怎么解决的?我也遇到了这个问题,你引入作为源码文件的是calendar还是v2?
