### ISSUE TITLE
月份改变时，事项加载错误

### ISSUE THREAD

**Issue by michael2043** [treadpit/wx_calendar#45]
setTodoLabels({
          pos: 'bottom',
          dotColor: '#40',
          days: [{
            year: 2018,
            month: 9,
            day: 12,
          }, {
            year: 2018,
            month: 9,
            day: 15,
          }, {
              year: 2018,
              month: 8,
              day: 5,
            }],
        });
当初始化时显示9月，9/12和9/15事项加载正确，但是切换到8月时，显示还是12号和15号事项

**Comment by treadpit** [comment]
你是最新的 `master` 代码么，这个问题在[上一个版本修复了](https://github.com/treadpit/wx_calendar/commit/e13097b23026817d67d7fa7be5136a226eb59c62)
