### ISSUE TITLE
页面切换到时候，数据没有清空

### ISSUE THREAD

**Issue by wChenone** [treadpit/wx_calendar#455]
**问题描述**
具体描述使用过程中有不明白或者疑惑的地方
![image](https://user-images.githubusercontent.com/37658262/133236260-b8ebc0b1-6384-41ee-a150-8b47365f83b7.png)
  我在这个日历页面，随便点击了下选择了一个日期，然后在切到其他页面，在返回到日历页面，这个日期还是在，感觉数据没有重制一样，我希望的是，我在切回到日历页面，跟新打开的一样。

**Comment by treadpit** [comment]
该日历点击处理为为选中行为，不能区分这次点击是随便点击的，还是需要选中的。如果点击不需要触发日历相关事件，可使用 `takeoverTap` 

![image](https://user-images.githubusercontent.com/10692855/133357921-f5879621-189c-4581-b0d6-852e56feac50.png)
