### ISSUE TITLE
setTodoLabels设置非当月日期后 无法显示

### ISSUE THREAD

**Issue by leifeng** [treadpit/wx_calendar#46]
当月是2018年9月11日
```javascript
setTodoLabels({
            pos: 'bottom',
            dotColor: '#40',
            days: [{
              year:2018,
              month:10,
              day:2
            }]
});
```
设置10月的待办，然后切换到10月，日历上不显示

但是如果同时标记了当前月和10月就可以显示
```javascript
 setTodoLabels({
            pos: 'bottom',
            dotColor: '#40',
            days: [{
              year:2018,
              month:10,
              day:2
            },{
              year:2018,
              month:9,
             day:10
             }]
         });
```

**Comment by leifeng** [comment]
https://github.com/treadpit/wx_calendar/blob/master/src/template/calendar/index.js#L397

感觉这里不能return，也需要执行
`
    const o = {
      'calendar.days': days,
      'calendar.todoLabels': uniqueTodoLabels(todoDays.concat(todoLabels)),
    };
    if (pos && pos !== todoLabelPos) o['calendar.todoLabelPos'] = pos;
    if (dotColor && dotColor !== todoLabelColor) o['calendar.todoLabelColor'] = dotColor;
    this.setData(o);
`

**Comment by treadpit** [comment]
是的，这是个 bug
