### ISSUE TITLE
使用calendar.chooseDateArea()跨年设置日期范围，再用calendar.getSelectedDates()获取选中的日期，获取到的日期不对

### ISSUE THREAD

**Issue by coder0309** [treadpit/wx_calendar#476]
**BUG描述**
使用calendar.chooseDateArea()设置日期范围后，再调用calendar.getSelectedDates()获取到的日期并不是设置的日期。

**复现步骤**
例如使用calendar.chooseDateArea(['2021-4-1','2022-4-16'])设置范围后，日历UI表现的正确的，在这个范围内的日期的确被选中了。但是再使用calendar.getSelectedDates()获取日期，获取的结果是['2022-4-1'... '2022-4-16']这个范围的日期，该月份之前的日期数据丢失了。但是跨月没有这个问题。
**期望结果**

**实际结果**

**截图**

**Comment by futianlili** [comment]
我也遇到了同样的问题，请问怎么解决，大神什么时候解决这个问题

**Comment by futianlili** [comment]
跨月会复现这个问题，例如选择5.5日到7.7日。calendar.getSelectedDate（）返回的是6.1日到7.7日

**Comment by coder0309** [comment]
> 跨月会复现这个问题，例如选择5.5日到7.7日。calendar.getSelectedDate（）返回的是6.1日到7.7日

我当时自测的时候没有发现跨月有问题。我这边的场景和功能是，有几个快捷选择日期范围的按钮，根据点击选项去设置日历选中的日期。快捷选项是不存在跨月或跨年的。但是用户也可以手动选中日期范围，因此发现了这个问题。解决方法就是监听日历上的日期点击事件即takeoverTap()，再data里面声明一个数组变量来存储用户当前选中的日期范围，通过chooseDateArea()去控制页面UI的变化，但是获取日期范围选择的值用声明的变量来获取，不用getSelectedDates()方法来获取。
