### ISSUE TITLE
月视图下，左滑切换月份的时候，缺少动画效果，能加上去么？

### ISSUE THREAD

**Issue by codisan** [treadpit/wx_calendar#55]
大神你好， 我现在用您开发的日历控件，非常好用，首先给您赞一个，
现在用户提了一个反馈，说那个左滑，或者右滑动的时候，没有动画效果，感觉非常生硬，
能抽空把这个实现不，谢谢啦！！

**Comment by lzt9977** [comment]
麻烦问下 现在有动画适配了么 谢谢

**Comment by wengxianxun** [comment]
这个滑动的问题作者老是不正面回答，总是打太极， 同样的问题转来转去就是没看到解决方案。
