### ISSUE TITLE
可选日期支持配置非区间的指定日期

### ISSUE THREAD

**Issue by ljxyaly** [treadpit/wx_calendar#63]
可否设置可选区域数组不为区间，而是一个固定数值的数组，通过遍历设置为可选为哪几项？

**Comment by treadpit** [comment]
[新增方法 `enableDays ()`](http://calendar.isfeer.com/?id=_8-%E6%8C%87%E5%AE%9A%E5%8F%AF%E9%80%89%E6%97%A5%E6%9C%9F)
