### ISSUE TITLE
获取当前选择的时间

### ISSUE THREAD

**Issue by chanjacv** [treadpit/wx_calendar#69]
如果获取当前的时间？我用你文档里面的引入方式就报错了，怎么回事？还有我想请教一下 怎么给当前时间上面赋值？要动态赋值对应的时间

**Comment by treadpit** [comment]
1、获取当前时间使用 `getSelectedDay ()`方法，报错是报什么错呢？我这边试了下没问题。

2、下面这个问题是指什么？

> 怎么给当前时间上面赋值

跳到指定时间？还是说给当前时间选择对象上增加其他属性？
