### ISSUE TITLE
是否能够支持 设置已选中日期

### ISSUE THREAD

**Issue by saiven00** [treadpit/wx_calendar#72]
情景1：多选状态下 有一个已选中的日期列表，想在日历中展示出来；
情景2：多选状态下 可以全选当月的可选日期

**Comment by treadpit** [comment]
设置已选中日期是指设置什么？

另外：

>多选状态下 可以全选当月的可选日期

这个可以提供一个方法

**Comment by saiven00** [comment]
> 设置已选中日期是指设置什么？
> 
> 另外：
> 
> > 多选状态下 可以全选当月的可选日期
> 
> 这个可以提供一个方法

“设置已选中日期”指的是 给一组可选日期 设置成选中状态

**Comment by saiven00** [comment]
![wechatimg93](https://user-images.githubusercontent.com/10445161/49912506-56054b00-fec5-11e8-8bf9-5680d8d1eb02.jpeg)
我对语法不熟悉，但是用下面比较笨的方法 解决了问题
![wechatimg94](https://user-images.githubusercontent.com/10445161/49912552-77663700-fec5-11e8-882e-de39522f0862.jpeg)
