### ISSUE TITLE
可以初始加载周视图吗

### ISSUE THREAD

**Issue by Asong1107** [treadpit/wx_calendar#74]
如何设置  初始加载周视图

**Comment by treadpit** [comment]
[可在初始化后调用视图切换](http://calendar.isfeer.com/?id=_9-%E5%91%A8%E6%9C%88%E8%A7%86%E5%9B%BE%E5%88%87%E6%8D%A2)

```js
initCalendar({
  afterCalendarRender: function() {
     switchView('week');
  }
});
```

**Comment by callmesoul** [comment]
问的时初始化周视图，
答的却是初始化后切换周视图
