### ISSUE TITLE
希望实现把已经打卡签到的标识出来,类似下图这样的。可以实现么？

### ISSUE THREAD

**Issue by 535944903** [treadpit/wx_calendar#85]
![_20190216000554](https://user-images.githubusercontent.com/1191371/52868995-a461ef00-317f-11e9-9e35-be9a3867c9b6.jpg)

**Comment by treadpit** [comment]
@535944903 需求类似设置待办标记，调用[设置代办方法，入参使用 `circle`](
http://calendar.isfeer.com/?id=_6-1-%E8%AE%BE%E7%BD%AE%E5%BE%85%E5%8A%9E%E6%A0%87%E8%AE%B0) 即可

```js
setTodoLabels({
  circle: true, 
  days: [{
    year: 2018,
    month: 1,
    day: 1
  }, {
    year: 2018,
    month: 5,
    day: 15,
  }],
 });
```
![image](https://user-images.githubusercontent.com/10692855/52940826-655fb380-33a2-11e9-9d9d-cf070779359a.png)

**Comment by 535944903** [comment]
@treadpit   非常感谢 好人一生平安

**Comment by fang635295364** [comment]
这个应该怎么写设置代办了 我其他方法都可以使用 这个设置代办没有效果
