### ISSUE TITLE
月视图下能否选择页面上的所有日期

### ISSUE THREAD

**Issue by ROLLKEYA** [treadpit/wx_calendar#87]
月视图下，能选择所有日期嘛？比如说灰色的日期。

**Comment by treadpit** [comment]
@ROLLKEYA 请参考文档 [选中指定日期](http://calendar.isfeer.com/?id=_9-%E9%80%89%E4%B8%AD%E6%8C%87%E5%AE%9A%E6%97%A5%E6%9C%9F)
