### ISSUE TITLE
是否有停留在“今天”的API

### ISSUE THREAD

**Issue by keyworldtony** [treadpit/wx_calendar#96]

**Comment by treadpit** [comment]
这个停留是指什么意思？

**Comment by keyworldtony** [comment]
> 这个停留是指什么意思？

一：jump()//不传，就跳到今天。{这个在您的demo，也无法实现}
jumpToToday()//这个api ，也不行。
都会报同样的问题，丢了某个模块，或者显示不是一个function。
 二:某天 待办 样式能否有直接改变数字颜色的，不是外面有个圆圈的。而是单独能修改这个数字样式的参数。
谢谢大佬

**Comment by treadpit** [comment]
第一个问题能否提供最小复现 demo，试了下master分支没发现问题

第二个问题每个人需求不一样，不太可能都兼顾上，这部分可以自己改动下
