### ISSUE TITLE
日期datapicker不支持enableDays

### ISSUE THREAD

**Issue by tTtangrui** [treadpit/wx_calendar#97]
期望日期选择器也能支持enableDays，选择日期可选区间

**Comment by treadpit** [comment]
日期选择器功能做了调整，配置参数及方法等参考日历组件，其他变动请 [参考文档](http://calendar.isfeer.com/?id=_3-%E6%97%A5%E6%9C%9F%E9%80%89%E6%8B%A9%E5%99%A8%E9%85%8D%E7%BD%AE)

![image](https://user-images.githubusercontent.com/10692855/56125175-e4d8c000-5faa-11e9-8702-29630d197ab9.png)
